### ISSUE TITLE
Map sorts above Sprite in rendering

### ISSUE THREAD

**Issue by tplans** [Seanba/SuperTiled2Unity#10]
When I import a map into my scene, all is well. But, when I put my sprite over the map, it disappears. I ended up fixing it by changing their order in the sorting layer, but I'm not sure what could be causing this.

**Comment by Dalqin** [comment]
Hi,
May I ask what you mean by "put your sprite over the map"?
Assuming you're using all 2D assets (and not 3D assets with a 2D locked camera) I would expect that, regardless of tools, you'd need to set layers or orders within a layer on each of your sprites / tile layers to have them rendered in the order you desire. So I'm not sure what you're expecting SuperTiled2Unity to automate for you.

**Comment by Seanba** [comment]
Depending on your Unity project it may take some work on your behalf to make sure everything is rendered in the proper order.

I've updated the SuperTiled2Unity documentation on this lately: https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html#how-supertiled2unity-implements-sorting
