### ISSUE TITLE
Namespace Issue

### ISSUE THREAD

**Issue by CoreyRailey** [Seanba/SuperTiled2Unity#100]
Unity 2018.3.12f1

Assets\SuperTiled2Unity\Editor\Importers\SuperImportContext.cs(24,16): error CS0246: The type or namespace name 'LayerIgnoreMode' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Seanba** [comment]
Hi there, @CoreyRailey. I just tried a clean Unity 2018.3.12f project with SuperTiled2Unity 1.7.0 and I am able to compile the code and run the example scene without any issue.

It sounds like you're missing `LayerIgnoreMode.cs` from your install of SuperTiled2Unity. Can you try to reimport the 1.7.0 Unity Package? Make sure all files are marked for import.

**Comment by CoreyRailey** [comment]
Sure thing I'll post back here when I get the results.

**Comment by CoreyRailey** [comment]
This script is definitely imported. I just re-imported everything again. Still has the same errors 4 of them all in the same script.

**Comment by CoreyRailey** [comment]
`namespace SuperTiled2Unity.Editor
{
    public enum LayerIgnoreMode
    {
        // Ingores nothing (layer is fully enabled)
        False,

        // Ignore everything on the layer
        True,

        // Ignores colliders on the layer (visuals are imported)
        Collision,

        // Ignores visuals on the layers (colliders still imported)
        Visual,
    }
}
`

**Comment by CoreyRailey** [comment]
It appears it was caused by it not removing the old SuperTiled2Unity.asmdef files.
