### ISSUE TITLE
Generate Tiled Map from string

### ISSUE THREAD

**Issue by Scoserix** [Seanba/SuperTiled2Unity#102]
Is there a way to generate the map and load it through script? I have the string with the full XML that represent the map. I've been able to do it in LIBGDX but doesn't seem to be a way in Unity tho.

**Comment by Seanba** [comment]
Hi there, @Scoserix. I imagine what you'd like to do is load a map at runtime within your game from an external source that provides the map string?

The problem with this in Unity is that the editor-specific functionality that allows us to build and manage assets is not available in runtime. Instead, what you should do is use [Asset Bundles](https://docs.unity3d.com/Manual/AssetBundlesIntro.html) (or maybe the newer [Addressable Assets tech](https://docs.unity3d.com/Packages/com.unity.addressables@0.4/manual/index.html)) to provide such maps as a DLC of sorts. This will still allow you to use the full pipeline for importing Tiled maps and tilesets for delivery to your game.

**Comment by Scoserix** [comment]
Hey @Seanba ! Yes exactly... what I was doing in LIBGDX was getting the object map from the server that had inside the string xml of the map and then load it at runtime.
I'm pretty new to unity so I didn't know about Asset Bundles and AAT. I'm going  to take a look at them! TY for the answer.

Digging into the web I also found that library that seems to do what I need  but it's really outdated. (https://bitbucket.org/Chaoseiro/x-unitmx/wiki/Home).

Thx again!

**Comment by Memorix101** [comment]
It is indeed possible to load resources in runtime. I'd like to know how you could use it with SuperTiled2Unity. 

Example:
```cs
private string _filePath;
void Start() 
{
#if UNITY_EDITOR
        _filePath = Application.dataPath + "/config.cfg";  // loading config.cfg from within editor assets folder
#else
        _filePath = Application.dataPath + "/../config.cfg"; // loading config.cfg from binary root folder
#endif

        if (File.Exists(_filePath))
        {
            // stuff
        }
        else
        {
            // other stuff
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1466920/72823780-83016100-3c74-11ea-8b24-0335f696a316.png)
