### ISSUE TITLE
Prefab import have a weird offset

### ISSUE THREAD

**Issue by beuted** [Seanba/SuperTiled2Unity#107]
Hello,
Thanks for this tool! I use to give a try to Tiled2unity and this one feels much nicer to use :)

I have this issue,
I have a tmx file with objects defined, with a Type "PlayerOnlyBlock" one at the position (0, 0) one at the position (16, 16)

![image](https://user-images.githubusercontent.com/2879233/68297950-7b301880-0098-11ea-8035-066c5272384c.png)

I have a prefab with this name, that gets imported fine, even with the property set and such. But the issue is that the position is FAR off. with a wierd offset compare to the map, that doesn't look like a scale issue (notice that both prefab appear at the right size and with the same alignement between each others).

![image](https://user-images.githubusercontent.com/2879233/68298081-c64a2b80-0098-11ea-8d8c-b611179633d0.png)

Here is my supertile2unity map:
![image](https://user-images.githubusercontent.com/2879233/68298172-001b3200-0099-11ea-8892-668a05ba870c.png)
(pixel per unit have been moved to 1 here)

Here is my tileset:
![image](https://user-images.githubusercontent.com/2879233/68298193-0b6e5d80-0099-11ea-9b65-cd57a9f5e546.png)
(pixel per unit have been moved to 1 here as well)

Here is my tile image:
![image](https://user-images.githubusercontent.com/2879233/68298295-4cff0880-0099-11ea-91b2-5bc9f3deb591.png)

Here is my super-tiled2unity config:
![image](https://user-images.githubusercontent.com/2879233/68298337-6011d880-0099-11ea-93e1-47df476e3d18.png)

Do you have an idea of where the issue might come from ?

Thanks a lot :)

**Comment by beuted** [comment]
Ok sometimes just documenting a question makes you realise the obvious answer.
My prefab had "this weird offset" by default, so super-tiled to unity just "pasted" the prefabs with an offset.

![image](https://user-images.githubusercontent.com/2879233/68298560-ffcf6680-0099-11ea-86a7-7d6fe670ece1.png)


You can close this issue sorry for the trouble :)

**Comment by Seanba** [comment]
Hi there, @beuted. No trouble at all. Glad you got it figured out. :)
