### ISSUE TITLE
Composite collider weird behavior

### ISSUE THREAD

**Issue by beuted** [Seanba/SuperTiled2Unity#108]
Hey,
I have a weird behavior with the collider generated by unity. It seems that my character's rigidbody is going through some of the polygons.
I've noticed that the composite collider generated by supertiled2unity has a geometry type set to "Polygons"
![image](https://user-images.githubusercontent.com/2879233/68857090-5c5a0380-06e2-11ea-871e-4880103241d9.png)

When I change that to "Outlines" the issue seems to disappear.
![image](https://user-images.githubusercontent.com/2879233/68857345-dd18ff80-06e2-11ea-9670-65200e5d7252.png)

I've done some search and unity seems to say that anyway the "Outline" type is the least efficient. https://docs.unity3d.com/ScriptReference/CompositeCollider2D.GeometryType.Polygons.html

My questions are :

* Do you have a reason to have this GeometryType set to "Polygons" by default ?
* How can I change that in my project to "Outlines" since it seems to fix the issue ?

Thanks again for the great tool :)

**Comment by Seanba** [comment]
Hi there, @beuted. Your collisions should probably word in using the polygon geometry type so there might be something with your sprite controller code you'd want to look into. However ...

1. I defaulted to polygons because the `CompositeCollider2D` in this case is wrapping up polygon colliders (and not edge colliders) and I assumed (perhaps unfairly) that all (most) users would want to use solid geometry.
2. Having control of the type of geometry generated is a reasonable ask so I added that to the ST2U project settings for [version 1.8.2](https://seanba.itch.io/supertiled2unity/devlog/110407/supertiled2unity-version-182).

![image](https://user-images.githubusercontent.com/6980630/69013238-7e05f580-0943-11ea-866f-a28577debb63.png)

Thanks!

**Comment by beuted** [comment]
Hey, thanks a lot for the (very) quick response to my problem 🥇 
I agree with you I probably have missed something (but that weird I'm using unity rigidbody for that see attached image at the end of my message)
I'll keep looking but what I've found so far is:
* It only seems to happen with polygon that have these "green lines" when looking at the "composite collider 2d" level. (These might be composite collider 2d collision lines !)
composite collider 2d:
![image](https://user-images.githubusercontent.com/2879233/69035628-6468ba80-09e4-11ea-94a5-251d6018c02f.png)
Polygon itself:
![image](https://user-images.githubusercontent.com/2879233/69035610-587cf880-09e4-11ea-86c2-550460752595.png)
* When I untick on the polygon "used by composite" the collision detection issue disapear on this polygon.
* This might be a bug with the composite collider "merging algo", I've found a 2016 issue talking about something similar: https://forum.unity.com/threads/composite-collider-2d-doesnt-really-work.428228/

If you have thought on this I'de be happy to ear them, If not anyway thanks again for the changes on supertiled2unity, and I think you can close the issue :)

PS: here is my character rigidbody and collider, nothing fancy I thought:
![image](https://user-images.githubusercontent.com/2879233/69036000-333cba00-09e5-11ea-8c80-f6eb7bc54a0f.png)

**Comment by Seanba** [comment]
@beuted Can you take another screenshot of that `CompositeCollider2D` but with the `SuperColliderComponent` gizmo turned off? I've run into problems before with the composite collider not generating the right geometry and your screenshot may help determine that.

![image](https://user-images.githubusercontent.com/6980630/69083065-fed9f580-0a06-11ea-9919-50575a9a317b.png)

**Comment by beuted** [comment]
Sure,
here it is:

![image](https://user-images.githubusercontent.com/2879233/69083795-2353c300-0a43-11ea-88da-a324e2b117c4.png)

But once again, not changing **anything** and moving to the beta version of unity 2019.11.3 seems to fix the issue. So my intuition is that the issue doesn't come from supertiled2unity but from the composite collider component itself

**Comment by Seanba** [comment]
Okay. It sounds like they've had some issues with the composite collider then that are hopefully resolved. I'll close the bug for now. Thanks again.
