### ISSUE TITLE
Cannot get it working as intended

### ISSUE THREAD

**Issue by Tyndall290** [Seanba/SuperTiled2Unity#109]
Hey, brand new to unity, tiled and this program. I've tried to create multiple test maps on tiled and then import them to unity using this program. 

The problem I'm having is that when i import every file (tmx, tsx, and the png) even from the same folder, it doesn't seem to "link" anything together. I can obviously drag the png onto the scene but not the big "T" tiled thing.  

Errors for each instance listed below

_SuperTiled2Unity version: 1.8.1, Unity version: 2019.2.10f1
Errors detected in tileset 'Dark Tokyo.tsx'. Check the tileset inspector for more details. Your map may be broken until these are fixed.
Could not find tile 339. Make sure the tilesets were successfully imported.
Could not find tile 364. Make sure the tilesets were successfully imported.
Could not find tile 414. Make sure the tilesets were successfully imported.
Could not find tile 340. Make sure the tilesets were successfully imported.
Could not find tile 413. Make sure the tilesets were successfully imported.
Could not find tile 438. Make sure the tilesets were successfully imported.
Could not find tile 439. Make sure the tilesets were successfully imported.
Could not find tile 437. Make sure the tilesets were successfully imported.
Could not find tile 466. Make sure the tilesets were successfully imported.

SuperTiled2Unity version: 1.8.1, Unity version: 2019.2.10f1
Missing texture asset: GuttyKreumDarkTokyov2/Tilemap/Tilemap.png
SuperTiled2Unity version: 1.8.1, Unity version: 2019.2.10f1
This asset is dependent on other files that either cannot be found or they failed to be imported.
Note that all Tiled assets must be imported to Unity in folder locations that keep their relative paths intact.
Reimport this asset once fixes are made.

Tip: Try opening Dark Tokyo.tsx in Tiled to resolve location of missing assets.

Assets/GuttyKreumDarkTokyov2/Tilemap/Tilemap.png_

I did open the tsx in tiled, that didn't change anything

I believe it's an error with the way I am are importing but due to a lack of tutorials online and a general lack of knowledge on how this all works, i can't seem to figure it out.

We are using a MAC and i have read that all the files need to be in the same folder, tried that and it did not work. 

Maybe if i could get a detailed run down of how to properly export from tiled and into unity using this program it would help because i can truly not find anything online except for one video that does not explain the export process from unity and the guy also just puts the png on the screen and not the actual tiled map.

**Comment by Seanba** [comment]
Hi there, @Tyndall290.

If you can send me your project (Right-click on the `Assets` directory in Unity and select `Export Package...`) I can take a look. Thanks.

**Comment by peachspit** [comment]
Hi @Seanba ,

This is Tyndall's gf (he wrote this concerning my project).
Here's the unity package, thanks so much for your help!

[Tekeke_Test.unitypackage.zip](https://github.com/Seanba/SuperTiled2Unity/files/3848695/Tekeke_Test.unitypackage.zip)

**Comment by Seanba** [comment]
Hi there @peachspit and hello again, @peachspit.

It looks to me like you imported `Map_01_Test.tmx` and `Dark Tokyo.tsx` into your Unity project but not the `GuttyKreumDarkTokyov2` folder which contains the `Tilemap.png` texture it is looking for.

You did import `Tilemap.png` into the same folder but that breaks the relative path to the texture that your TSX file was expecting. When I open your map in Tiled I see that Tiled also can't find the `Tilemap.png` (because you moved it relative to your map and tileset files).

![image](https://user-images.githubusercontent.com/6980630/68901241-2b39fd00-06fb-11ea-8b98-83d40dc2c556.png)

You probably just want to drag your `GuttyKreumDarkTokyov2` folder into  `Assets/Map` in your project (that's what I would do) but you can relocate the texture (in Tiled) to fix which I've done here ...

![image](https://user-images.githubusercontent.com/6980630/68901563-c501aa00-06fb-11ea-9b86-6ed75beac415.png)

Hope that helps.

**Comment by Seanba** [comment]
BTW, there's two other issues you'll want to look at:

1) It doesn't look like you're using pixel snapping in Tiled. That means the colliders you put down in the Tiled Collision Editor are going to most likely have sub-pixel coordinates ...

![image](https://user-images.githubusercontent.com/6980630/68901821-51ac6800-06fc-11ea-9e95-ee849bc05ab4.png)

![image](https://user-images.githubusercontent.com/6980630/68901880-79033500-06fc-11ea-9610-5b3d6956b650.png)

2) You have some errant colliders in your tilset that have zero width and height. ST2U will complain to you about that in the TSX inspector, btw.

![image](https://user-images.githubusercontent.com/6980630/68901960-ac45c400-06fc-11ea-8b8b-0dfdbe8cfdda.png)

Note that Tiled draws uninitialized collision rectangles with a width and height of 20 pixels so it can be easy to miss that.

**Comment by peachspit** [comment]
Hi Sean!

First of all, thanks so much for your help! I got the map onto Unity and
it's looking good, but the colliders aren't working with my sprite.  I've
read a lot of forums and troubleshooted, including re-doing all the
collision tiles with snap to pixel to make sure they are accurate.  My
sprite has 2d rigid body physics, and it seems the collision squares got
translated over as I see the collision objects in the hierarchy, but they
don't seem to be reading each other. I'll send the unity package and see if
you can spot any problems, I feel like it's user error or some small thing
I missed along the way.

Thanks again!
Taylor/Peachspit

**Comment by Seanba** [comment]
It looks this was resolved so I'm closing out the bug. Thanks and good luck with your game. :)
