### ISSUE TITLE
Bounding box on layers shifted up by one row

### ISSUE THREAD

**Issue by yadurajiv** [Seanba/SuperTiled2Unity#110]
The bounding box has shifted one row up in the y direction. I did not face the problem in 1.6.2. The problems appeared after updating to 1.8.1 (and remains in 1.8.2 as well).

You can recreate this if you have 1.6.2 - import it into unity, open the example level and drag it into a scene. Select any layer and keep an eye on the bounding box. As seen below.

![1.6.2](https://i.imgur.com/AbEmSYV.png)

Update to 1.8.1 (or 1.8.2) and re-import  the tilemaps (if it doesn't automatically do so). Select the same layer and see the bounding box. You can see that it has shifted up by one row.

![1.8.1](https://i.imgur.com/QMJHL44.png)

Also, `TileMap.HasTile(pos) ` returns true on top of the bounding box, where, `var pos = CurrentTilemap.WorldToCell(Camera.allCameras[0].ScreenToWorldPoint(Input.mousePosition));` Which just means that when the mouse is on top of the invisible area above the map, the system assumes you are actually on top of a tile.

**Comment by Seanba** [comment]
Hi there, @yadurajiv. Having the bounding box of the tilemap be out of sync with the tiles is an unfortunate side-effect of what I was hoping to fix with tile sorting. I do plan to fix this but I'll have to give it some thought. Hopefully this coming weekend I can find some time. Thanks of the bug report.

**Comment by Seanba** [comment]
Hi again, @yadurajiv. [Version 1.8.3 of SuperTiled2Unity](https://seanba.itch.io/supertiled2unity/devlog/111536/supertiled2unity-version-183) should fix this for you now.

As you can see in the picture below, the boundary on the tilemap now lines up with what you'd expect.

![image](https://user-images.githubusercontent.com/6980630/69503868-c42efc00-0ee3-11ea-9187-06a8136dfeb1.png)

Thanks for the bug report.
