### ISSUE TITLE
Error importing tsx file (was imported at smaller size)

### ISSUE THREAD

**Issue by SlowCircuit** [Seanba/SuperTiled2Unity#111]
The following is the error message

SuperTiled2Unity version: 1.8.2, Unity version: 2019.2.3f1
Texture was imported at a smaller size. Make sure 'Max Size' on 'Park Objects/tree-17.png' is at least '253'

However, the max size for that sprite is 2048.

**Comment by Seanba** [comment]
Hi there, @SlowCircuit. That does sound like a bug but I'm not able to replicate it. Could you send your project for further debbugging? (sean@seanba.com)

**Comment by SlowCircuit** [comment]
I'm not able to send the project, unfortunately. I'll try to fix the bug and let you know what I find.

**Comment by Seanba** [comment]
Okay. If you can replicate the bug in something you are able to share with me I'll be happy to look it further.

**Comment by SlowCircuit** [comment]
Found the issue. The texture width in the XML was being detected as 202, but the asset's width is 200. I went into the XML and found that it is indeed 202. If I go into Tiled and select that object it says it's 200. No idea why the tileset/object collection is having this issue. I fixed it simply by manually changing the value to 200 in the XML. Then it imported just fine. So either Tiled has a bug that caused it to use an incorrect value, or the object image we imported into the collection changed size after importing? I'm not sure. Either way, I don't think this is SuperTiled2Unity's fault at all. Thanks though!

**Comment by Seanba** [comment]
Thanks for the update. When this sort of thing happens I want the importer to make the user aware. Chances are the tileset just needs to be resaved in Tiled in which case I want to print out a more helpful error.

So, let's keep the bug open for now. :)

**Comment by Seanba** [comment]
Version 1.8.3 should be this a bit more obvious now. Thanks.

**Comment by elecfrog** [comment]
Sorry I pick up this issue again with https://opengameart.org/content/painted-iso-roguelike-tiles this resource when I need to make up with an isometric game, I solve it with changing the .png file default max size from 2048 to 4096. I don't know what potential question would exits, but it really works
