### ISSUE TITLE
1.9.0 Vector2 List to Array Conversion errors.

### ISSUE THREAD

**Issue by PeaceBrigade** [Seanba/SuperTiled2Unity#114]
All the lines that are akin to:
`List<Vector2> points = new List<Vector2>(1024 * 8);`
and then
 `composite.GetPath(p, points);`

generate the error:
`cannot convert from 'System.Collections.Generic.List<UnityEngine.Vector2>' to 'UnityEngine.Vector2[]'`

I don't know if they need to be something like
`composite.GetPath(p, points.ToArray());`
Or something, but 1.9.0 I can't get to work at all.

**Comment by Seanba** [comment]
Hi there, @PeaceBrigade. What version of Unity are you on?

**Comment by PeaceBrigade** [comment]
2018.3.14f1, though I get the same error in 2018.4.X, and I think also 2019, but when I tried 2019 last night I was pretty tired.

**Comment by Seanba** [comment]
I've confirmed that the `CompositeCollider2D` methods I was using do not exist for Unity 2018.3 and 2018.4. Upgrading to 2019.1.x should have fixed these errors for you but I've modified ST2U with version 1.9.1 so you shouldn't have to do that. Thanks for the bug report.

https://seanba.itch.io/supertiled2unity/devlog/112853/supertiled2unity-version-191
