### ISSUE TITLE
CompositeCollider2D with tons of PolygonCollider2D loaded too slow.

### ISSUE THREAD

**Issue by park-do** [Seanba/SuperTiled2Unity#115]
It leads to a massive lag when we open the map on the scene viewer in Unity, or when the map is loaded in the play. Have you got any idea what could be the cause?

Lagging map has a TileLayer with a Composite Collider2D that has almost 1,000 PolygonCollider2D children.
I tried the Composite Collider 2D's generation type sync to manual but occured same.

**Comment by park-do** [comment]
answered myself:

My Tile Collision setting is wrong.
My tile is 32px, but there is some gap in collision setting. ( I set collision width,height with 31.xx px)
so composite collider don't work anything and it's meaningless caculation makes lag.
I edited collision fit to tile, it works fine.

**Comment by Seanba** [comment]
Glad you got it sorted out. FWIW, I use `Snap to Pixels` in Tiled to help me out with stuff like this.

![image](https://user-images.githubusercontent.com/6980630/71377028-1b7ac780-2589-11ea-888b-fd7b9e759c83.png)
