### ISSUE TITLE
Collision bug with imported map

### ISSUE THREAD

**Issue by Natlink** [Seanba/SuperTiled2Unity#116]
Hi!
I'm geting stuck on a problem with collisions of a map imported with ST2U.
This bug occurs on the new version of unity 2019.2.17, i haven't this bug before the upgrade from 2017.X unity version. I have tried to upgrade to last ST2U, but nothing changed.

So, when map is instantiated, she has the good shape collider, corresponding to collision set on TiledMap, but entity didn't interract well with this collider. For exemple, character pass half throug this collider on some point of the edge.

![image](https://user-images.githubusercontent.com/35851177/71986416-c0a1cb00-322c-11ea-8c52-1b83512b5fc0.png)
On the image, the big shape is the map collider, and the litle rect collider is the player collider.
So, it's seem to work, but for an unknow reason the collision is detected only at a certain point of the collider.

If i manually edit the collider, it works well, for exemple:
![image](https://user-images.githubusercontent.com/35851177/71986794-58071e00-322d-11ea-9224-732fa784c921.png)

Another exemple:
![image](https://user-images.githubusercontent.com/35851177/71986880-8258db80-322d-11ea-8858-e19e6ac89b4f.png)
At this precise point, the character will slide over the ground and fell throug without reason

Sorry for my bad english, i'm french.
Thank's for your futur help!

**Comment by Natlink** [comment]
After further research, it's seem not to be totaly caused by ST2U, cause if i spawn another entity, it doesn't have the collision bug 
![image](https://user-images.githubusercontent.com/35851177/71995074-424c2580-323a-11ea-936d-330a98943650.png)
I think this bug occurs by merging ST2U collision and the specific script/collision of my character...

**Comment by Seanba** [comment]
Hi there, @Natlink. I've run into issues before with polygon data not being updated or serialized properly due to some combination of Unity's scripted importers and prefab overrides.

**One quick thing to try**: What if you replace the prefab instance of your map in your scene with a fresh one? (In other words, remove the map from your scene and drag and drop a new prefab of it into your scene).

Also, did you upgrade to the latest version of SuperTiled2Unity when you switched from Unity version 2017.x to 2019.x?

**Comment by Natlink** [comment]
Hi! Thanks for this quick answer!
For ST2U version, i have tried with the version i had before upgrading unity, see the bug, try update ST2U to last version and the bug is again her. So it's seems to be the unity upgrade who have break something.

I have try your solution, but it's still the same. One really strange thing is that if i change any very litle piece of the polygon from editor when game is running, the collision works properly, it's really strange.

So i think i will use the edge collision, it work properly, and seems to be more accurate.

( But i you find an answer to this bug, i'll be curious to see how did you fix it :D )

**Comment by Seanba** [comment]
FWIW, this seems familiar to issue #108 and upgrading to Unity 2019.3 seems to have fixed it for that user.

**Comment by Natlink** [comment]
Effectively, it's seems to be the same probleme, when i used polygon, my character strangely follow the green line over polygon. Can't see why this bug occurs, but use edge fix this, so let's wait for the next LTS unity version to see if it's fix my bug.
Thanks for your answer, i close this issues :)
