### ISSUE TITLE
Getting Build errors

### ISSUE THREAD

**Issue by sidshekar** [Seanba/SuperTiled2Unity#122]
Getting following build errors while creating Build&Run in Unity 2019.2.17f1

![image](https://user-images.githubusercontent.com/2862097/72947799-1c9d4f80-3de8-11ea-865a-71b73f8f6678.png)

**Comment by Seanba** [comment]
Hi there, @sidshekar. Those look like compile errors from an custom exporter copied from the [SuperMovingPlatform](https://github.com/Seanba/SuperMovingPlatform) example. Do you have SuperTiled2Unity installed on that project as well? The missing namespaces should be defined there.

**Comment by sidshekar** [comment]
Hi!! Ya I have supertiled2unity installed as initially I didn’t have it
installed so the object wasn’t getting replaced by prefab. But once I
installed it it was working fine.

When I run the project it runs fine. It gives an error while building!!

**Comment by Seanba** [comment]
> When I run the project it runs fine. It gives an error while building!!

Oh, okay, I missed that part there. I think the problem may be that you are compiling an editor script into the build. Try putting that script into an `Editor` folder and see if that helps.

**Comment by sidshekar** [comment]
Should it be in the editor folder? this is a custom tmx
importer file/class? This is the same file that is there to import the
track in the track sample.

**Comment by AberrantWolf** [comment]
I believe that importer classes need to be inside a folder called "Editor".
You can have many of these, and Unity will exclude everything underneath an
"Editor" folder from the build process.

**Comment by AberrantWolf** [comment]
I believe that importer classes need to be inside a folder called "Editor".
You can have many of these, and Unity will exclude everything underneath an
"Editor" folder from the build process.

**Comment by sidshekar** [comment]
oh ok!! will do and give it a try. thanks.

**Comment by sidshekar** [comment]
Ok it works now. Thanks!!
