### ISSUE TITLE
Problems with importing tilemaps

### ISSUE THREAD

**Issue by filipio** [Seanba/SuperTiled2Unity#127]
I'm using Tiled for the first time. I've tried so hard to import my map, but I have no idea what's wrong with importing it to unity through SuperTiled2Unity. I even tried to import an example map, the desert, but even for this it didn't work (followed the instructions from the video on youtube, but still something is wrong). I can't find the answer in the net, so I hope somebody can help me over here... It drives me crazy. The error message is: 
SuperTiled2Unity version: 1.9.1, Unity version: 2019.3.0f6
Errors detected in tileset 'desert.tsx'. Check the tileset inspector for more details. Your map may be broken until these are fixed.
Could not find tile 30. Make sure the tilesets were successfully imported.
Could not find tile 14. Make sure the tilesets were successfully imported.
Could not find tile 15. Make sure the tilesets were successfully imported.
Could not find tile 16. Make sure the tilesets were successfully imported.
Could not find tile 46. Make sure the tilesets were successfully imported.
Could not find tile 31. Make sure the tilesets were successfully imported.
Could not find tile 22. Make sure the tilesets were successfully imported.
Could not find tile 23. Make sure the tilesets were successfully imported.
Could not find tile 24. Make sure the tilesets were successfully imported.

**Comment by Seanba** [comment]
Hi there, @Zone313213. That error is telling you there is a problem with a tileset that your map is using ...
```
Errors detected in tileset 'desert.tsx'. Check the tileset inspector for more details. Your map may be broken until these are fixed.
```

So find `desert.tsx` in your Unity project, select it, and see what errors it is reporting. My guess is that your tileset is dependent on a texture that has not yet been added to your Unity project or perhaps was added but at the wrong location. Each map (TMX file) may have dependencies on tilesets (TSX files) that in turn have dependencies on texture files (probably PNGs) and all of those files have to be in your Unity project and in the "right" folders. It will help to have an understanding of "relative paths" if that is a new concept for you.

**Comment by Zone313213** [comment]
Thanks for the answer ;) I've fixed this. Another problem has shown up...
Maybe you have some idea what's wrong about with it? If you have some time
, please check
https://answers.unity.com/questions/1698637/cant-detect-colliders-from-tiled.html

I have no idea how to solve this...

sob., 8 lut 2020 o 20:00 Sean Barton <notifications@github.com> napisał(a):

**Comment by Seanba** [comment]
I'm sorry I let this bug linger so long (almost 5 years) that now the link given above is dead. I'm closing for now but will revisit if newer information is given. Apologies.
