### ISSUE TITLE
It says that I have to import something that i already did.

### ISSUE THREAD

**Issue by potatoesrgood** [Seanba/SuperTiled2Unity#129]
So, I went to import my TIled map and it said "Missing tileset asset .../.../.../TileLayerOne.tsx. So I imported TileLayer1.tsx, but it still says that I need to import TileLayer1.

**Comment by Seanba** [comment]
Hi there, @potatoesrgood. Your `TileLayerOne.tsx` file was probably imported into the wrong directory. Your TMX file is expecting `TileLayerOne.tsx` to be three directories "up" from your TMX file (check the `..` in the path).

**Rule of thumb:** The relative paths between your TMX, TSX, and texture files must be kept in tact when you import your files into Unity.

Hope that helps.

**Comment by potatoesrgood** [comment]
I really appreciate you helping me. I do have a question though. The only TileLayer1.tsx that I can find is on my desktop. Is there another folder that I can go into to find the right one?

**Comment by potatoesrgood** [comment]
or do I have to put it somewhere specific?

**Comment by Seanba** [comment]
Yeah, the location of your files will need to be specific. Your TMX file has relative paths to your tilesets and your tilesets will have relative paths to your textures. All these relative paths need to stay intact when you import into Unity.

Probably the best thing for you to do first, before importing into Unity, is to rearrange your files into a folder structure like so ...
```
+MyTiledFiles
    +Maps
    +Tilesets
    +Textures
```
... or something like that. The point being you want to have one directory at the top and all other files used for your maps will exist in folders underneath.

Then, all you should need to do is drag that `MyTiledFiles` directory into your Unity project and everything will get imported.

Does that make sense? The important thing is that these files need to one where their dependencies exist **and ** all dependencies must also exist in your Unity project. So, you can't have a TMX reference a tileset that is on your desktop.

Hope that helps.

**Comment by potatoesrgood** [comment]
Thank you so much. That was really helpful. Also, thank you for getting back to me so quickly.

**Comment by Seanba** [comment]
You're welcome. I'll close the issue for now but you can re-open if you're still having issues.
