### ISSUE TITLE
Colliders arent working on Unity 2019.3.9f1

### ISSUE THREAD

**Issue by Vachan0** [Seanba/SuperTiled2Unity#130]
I've done multiple imports and by checking on/off TIlemap Collider 2 in Unity I see no change at all. The collision never gets applied to my tilemap no matter what I've tried.

**Comment by ijacquez** [comment]
Do you see colliders in the example TMX file?

**Comment by Vachan0** [comment]
> Do you see colliders in the example TMX file?
Yes I do, the example works. The issue seems to appear only when I import myself.

**Comment by Seanba** [comment]
Hi there, @Vachan0. If you can email me your project I'll try to find some time to take a quick look soon. (sean@seanba.com)

**Comment by Vachan0** [comment]
Hey, the "quick reinstall" I did previously didn't have any effect. Today I completely removed Unity, I mean COMPLETELY. Reinstalled and "bam" it seems to work now again. Thanks a lot for the quick answers.
