### ISSUE TITLE
Help Super tiled2unity

### ISSUE THREAD

**Issue by juanmega** [Seanba/SuperTiled2Unity#140]
Im using ST2U
SuperTiled2Unity version: 1.9.1, Unity version: 2018.3.0f2
Missing texture asset: ../sprites/maps/valley-sprites.png
Could not find tile 145. Make sure the tilesets were successfully imported.
Could not find tile 25. Make sure the tilesets were successfully imported.
Could not find tile 25. Make sure the tilesets were successfully imported.
Could not find tile 63. Make sure the tilesets were successfully imported.
Could not find tile 75. Make sure the tilesets were successfully imported.
Could not find tile 92. Make sure the tilesets were successfully imported.
Could not find tile 71. Make sure the tilesets were successfully imported.
Could not find tile 35. Make sure the tilesets were successfully imported.
Could not find tile 112. Make sure the tilesets were successfully imported.

SuperTiled2Unity version: 1.9.1, Unity version: 2018.3.0f2
Missing texture asset for tile 2: ../sprites/maps/tree-1.png

Help with these errors please

**Comment by AberrantWolf** [comment]
First I would check that your missing sprites exist in the correct relative path from the tiled file. It's a pretty common error to accidentally put your images in a different path if you're copying tiles into the Unity project rather than editing your tilemap in-place from within the Unity Assets directory.

**Comment by Seanba** [comment]
Hi there @juanmega. It looks like your `tree-1.png` file is in the wrong location. SuperTiled2Unity is expecting it to be up one directory, then in the `sprites/maps` folder.

As @AberrantWolf mentioned this is a common error. The relative paths between your TMX, TSX, and texture files must remain intact as you move your assets into your Unity project.
