### ISSUE TITLE
Imported map is small

### ISSUE THREAD

**Issue by uweenukr** [Seanba/SuperTiled2Unity#141]
I tried searching the issues history to find an answer. Maybe what I am trying to do is not best practice. if so please tell me. I have a player that is 32x64 and in Unity the Pixels Per Unit is set to 32. I created a map in Tiled using 32x32 tiles. When I load that into Unity it defaults to what looks like is 1 unit to 100 pixels. So tiles are ~3x smaller than the player.

The PPU on the Tiled map in Unity is set to 100 and any changes I make there seem to skew the spacing on tiles. As well as give me a warning in the inspector.

The only change I made that seems to do what I want is changing the scaling of the whole grid to 3 up from 1. This feels like the wrong solution and im worried it will have other negative impacts later in the workflow.

Any advice? Thank you

**Comment by Seanba** [comment]
Hi there, @uweenukr. You want to use the same `Pixles Per Unit` value on your sprites, maps, and tilesets. My guess is that you changed the PPU on your map but the tilesets it uses are still using a value of 100, which is why the spacing gets messed up. If you look at your map in the inspector you should see a warning telling you that your tilesets and map have mismatched pixels per unity settings, btw.

**Comment by uweenukr** [comment]
![image](https://user-images.githubusercontent.com/1385108/83442262-e3b85b80-a415-11ea-89bc-49d0050d8edc.png)

![image](https://user-images.githubusercontent.com/1385108/83442459-36921300-a416-11ea-9314-da6f9073be90.png)

![image](https://user-images.githubusercontent.com/1385108/83442506-47428900-a416-11ea-9124-d65e4efd7204.png)

![image](https://user-images.githubusercontent.com/1385108/83442567-5fb2a380-a416-11ea-801b-d5ee8aca9104.png)

![image](https://user-images.githubusercontent.com/1385108/83442630-7bb64500-a416-11ea-8020-ef876bdaf6ce.png)

**Comment by uweenukr** [comment]
You were right and I didnt even notice that this object existed:
![image](https://user-images.githubusercontent.com/1385108/83443951-9b4e6d00-a418-11ea-9b85-007e6ea1de36.png)

This is the issue:
![image](https://user-images.githubusercontent.com/1385108/83443913-8bcf2400-a418-11ea-8ad5-bb9a99c8d716.png)

And this is the fix:
![image](https://user-images.githubusercontent.com/1385108/83444003-b1f4c400-a418-11ea-95e1-4217a0c820ce.png)


Explaining all this out incase someone else makes this mistake :)

Thank you for your time. Sorry to bother!
