### ISSUE TITLE
Tiled now defaults to Z Standard compression?

### ISSUE THREAD

**Issue by mikest34** [Seanba/SuperTiled2Unity#143]
Hi Sean,

I'm trying this out for my next project and ran into a small issue. I'm using Tiled 1.4.1 for this test (latest version) and the Unity 2019 LTS release (2019.4.0f1)

It looks like Tiled is now storing the tile data using Z standard compression ("zstd") which Super Tiled2Unity does not support. It's a fairly easy fix in the Tiled editor (just change the compression) but thought I would log it here for a future fix.

thanks for the great tool!

**Comment by StudTheSystem** [comment]
What was the fix?

**Comment by mikest34** [comment]
In TIled, go to "Map" and then "Map Properties" and you can change the "Tile Layer Format" to "Base64 (gzip compressed)" or at least something other than Z Standard. Then just save and reimport the tilemap in unity and it should work.

**Comment by StudTheSystem** [comment]
Wow that actually fixed the errors.  Thanks for that!

**Comment by Seanba** [comment]
Hi there @mikest34. Thanks for bringing this to my attention. I've looked into `Zstandard` compression and it simply isn't available through use in Unity scripts. If someone makes a pure C# decoder (that doesn't rely on external DLLs) then I will update SuperTiled2Unity accordingly.

For the time being the newest version of SuperTiled2Unity will alert users of the error and the fix.

![image](https://user-images.githubusercontent.com/6980630/88471923-fe69f680-ced3-11ea-8b1f-a8d1e5780b24.png)
