### ISSUE TITLE
tmx file giving me errors but files aren't missing from folders

### ISSUE THREAD

**Issue by StudTheSystem** [Seanba/SuperTiled2Unity#146]
So I already checked the dependencies of each file to make sure they're in the right location so the "missing files" errors is gone but now I'm getting this error with the same tmx file when I highlight it.  I have tiled open and Tiled isn't complaining about anything, the files are in their right locations

SuperTiled2Unity version: 1.9.1, Unity version: 2019.4.4f1
Could not find tile 221230376. Make sure the tilesets were successfully imported.
Could not find tile 218678368. Make sure the tilesets were successfully imported.
Could not find tile 45350915. Make sure the tilesets were successfully imported.
Could not find tile 78709502. Make sure the tilesets were successfully imported.
Could not find tile 61997056. Make sure the tilesets were successfully imported.
Could not find tile 47699968. Make sure the tilesets were successfully imported.
Could not find tile 83952938. Make sure the tilesets were successfully imported.
Could not find tile 182124544. Make sure the tilesets were successfully imported.
Could not find tile 33892612. Make sure the tilesets were successfully imported.
Could not find tile 16963290. Make sure the tilesets were successfully imported.

EDIT: If I export the tmx file directly from Tiled to Unity I get this error message instead
SuperTiled2Unity version: 1.9.1, Unity version: 2019.4.4f1
Missing tileset asset: ../../../../Tiled Maps/overworld.tsx

In this method Unity doesn't give me the "could not find tile" errors like posted above but it now expects the tsx file to be in a different location.

**Comment by StudTheSystem** [comment]
Never mind I got it, I just had to change the compression type in Tiled.  Cool program, man!

**Comment by ContrerasA** [comment]
> Never mind I got it, I just had to change the compression type in Tiled. Cool program, man!

How were you able to achieve this? I'm having the same issue, and there doesn't seem to be supporting documentation on how to fix.

**Comment by StudTheSystem** [comment]
Ok so once you get rid of all the missing file errors, meaning all 3 files are in their respective locations,  make sure in the program "Tiled" you have your compression set to anything but what the default is, I think it's defaulted to gzip, so change it to anything but that and it should get rid of the error in unity.  you're gonna have to delete the tmx file in unity first in order to import the corrected format from Tiled

**Comment by Seanba** [comment]
It looks like Tiled has recently added a new compression format (`Zstandard`) for the tile layers and has made it the default. This compression format simply isn't available in Unity. However, the latest version of SuperTiled2Unity has a more helpful error telling users what to do.

![image](https://user-images.githubusercontent.com/6980630/88471851-3f154000-ced3-11ea-8371-fdd03d00c572.png)
