### ISSUE TITLE
Does SuperTiled2Unity work for Unity Vesion 2019.4.5f1?

### ISSUE THREAD

**Issue by RealOesi** [Seanba/SuperTiled2Unity#147]
Could not convert 'zstd' to enum type 'DataCompression'.
UnityEngine.Debug:LogErrorFormat(String, Object[])
SuperTiled2Unity.StringExtensions:ToEnum(String) (at Assets/SuperTiled2Unity/Scripts/Extensions/StringExtensions.cs:55)
SuperTiled2Unity.Editor.XmlExtensions:GetAttributeAs(XElement, String, DataCompression) (at Assets/SuperTiled2Unity/Scripts/Editor/Extensions/XmlExtensions.cs:63)
SuperTiled2Unity.Editor.XmlExtensions:GetAttributeAs(XElement, String) (at Assets/SuperTiled2Unity/Scripts/Editor/Extensions/XmlExtensions.cs:84)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessLayerData(GameObject, XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.TileLayer.cs:77)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessTileLayer(GameObject, XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.TileLayer.cs:47)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessMapLayers(GameObject, XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.cs:341)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessMap(XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.cs:83)
SuperTiled2Unity.Editor.TmxAssetImporter:InternalOnImportAsset() (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.cs:51)
SuperTiled2Unity.Editor.SuperImporter:OnImportAsset(AssetImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/SuperImporter.cs:72)
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)

Does sombody knows what that error means? Are there any bugs in SuperTiled2Unity for the newest version?

**Comment by Seanba** [comment]
Hi there, @RealOesi. The issue is that the latest version of Unity has introduced a new `Tile Layer Format` compression that is not supported (yet) in SuperTiled2Unity and has made that the default. Just go into your properties for the map (in Tiled) and select one of the other formats.

![image](https://user-images.githubusercontent.com/6980630/88466510-a959c080-ce92-11ea-9e06-947bf274448f.png)

Hope that helps.

**Comment by Seanba** [comment]
I've looked into supporting `Zstandard` compression and it simply isn't available through Unity. With the latest version of SuperTiled2Unity you will see a helpful error message in the inspector for your Tiled map.

![image](https://user-images.githubusercontent.com/6980630/88471809-f2316980-ced2-11ea-8687-2e9aadeb7c63.png)
