### ISSUE TITLE
How to add Collision from Tiled?

### ISSUE THREAD

**Issue by Thundros** [Seanba/SuperTiled2Unity#148]
Hi @Seanba ! First off, give yourself a PAT on the BACK! This project is AMAZING! Keep up the GREAT work! <3 Second, I would like to ask how to add tile-based collision information using a custom properties boolean called 'collides' in my Tiled import in Unity using SuperTiled2Unity. Any help is GREATLY appreciated!

Thank you so much!

Regards, 

Thundros

**Comment by Thundros** [comment]
@Seanba Hello?

**Comment by Seanba** [comment]
With SuperTiled2Unity custom properties are generally used in concert with a custom importer, that you write, that knows what to do with the properties you provide it. I'm not sure where you are in your programming abilities but most users stay away from that as it can be an advanced subject.

However, collisions can be easily imported into your maps without any custom programming. What you do is use the [Collision Editor in Tiled](https://doc.mapeditor.org/en/stable/manual/editing-tilesets/#tile-collision-editor) to add collision geometry to your tiles. The collision tiles are grouped together in your prefab when you save your map.

**Comment by Thundros** [comment]
@Seanba : What? I have to make my own collision system just to use TexturePacker collision? Is there not a short 30 second or so clip showing how to do this & that it works? Thank you once again for all the help! MUCH appreciated, brother! <3

**Comment by Thundros** [comment]
@Seanba : How do you check for collision in that supertiled2unity demo you made? i am using a Rigidbody as my character is loaded in with with the texturepacker plugin.

**Comment by Thundros** [comment]
@Seanba : Hello?

**Comment by Seanba** [comment]
> @Seanba : Hello?

Please don't do that. At best I find time on weekends to look at issues and since the pandemic started my free time has become even more scarce.

**Comment by Thundros** [comment]
Apologies.

**Comment by Seanba** [comment]
> @Seanba : How do you check for collision in that supertiled2unity demo you made? i am using a Rigidbody as my character is loaded in with with the texturepacker plugin.

I'm not familiar with the texturepacker plugin but if it is creating a character with a `RibidBody2D` component on it then you can probably get it to work. I think collision detection (and physics) is one of the toughest things to get right with Unity so expect for this to take some time and to be a source of frustration.

In my sample project I have two classes of colliders:
1. Default colliders (Walls, rocks, whatever the player will collide with. These are pink in the picture below. They use the `Default` layer.)
2. Water (A collision trigger volume as the player doesn't collide with water but falls into it. This is blue below. It uses the `Water` layer.)

![image](https://user-images.githubusercontent.com/6980630/91003516-1d24e100-e597-11ea-885a-6fd22997899a.png)

I use raycasts in the player script (`OverheadMegaDadController.cs`) and when a "hit" is detected I use that to limit movement of the player ...
```
var hit = Physics2D.Raycast(pos, m_Facing, MovementBlockSize, 1 << LayerMask.NameToLayer("Default"));
```

And I use the `OnTriggerEnter2D` function to detect when the player has entered the water trigger ...
```
        private void OnTriggerEnter2D(Collider2D collision)
        {
            if (collision.gameObject.layer == LayerMask.NameToLayer("Water"))
            {
                StartCoroutine(Drowned());
            }
        }
```

Your game is going to have special needs, however. My recommendation for you is put together a very simple project (without SuperTiled2Unity and other plugins) that has a simple box representing your character (with an appropriate `RigidBody2D` component and colliders) and a few other simple boxes (with colliders) that represent platforms or walls or whatever the player will collide with. Get this working to your satisfaction and then you can bring in texturepacker, SuperTiled2Unity, etc. one at a time with a focus on getting those plugins to create the game objects with the settings and components you need.

You will likely need to use just the right combination of layers, tags, etc. to get this just right and you want to succeed there without the complexity of other plugins getting in your way. This is approach is no doubt slower than you would like but I think it's essential to get this kind of thing right in your game early.

**Comment by Thundros** [comment]
@Seanba : Is there a way to refine the collisions? I noticed if I'm at the top of a sprite, some sprites such as trees I want to go behind but there is still collision there.

Thank you for all the help!

Regards, 

Thundros

**Comment by Seanba** [comment]
> @Seanba : Is there a way to refine the collisions? I noticed if I'm at the top of a sprite, some sprites such as trees I want to go behind but there is still collision there.

It's a common issue in game development to have your characters get stuck on geometry when doing collision detection. Are you using Snapping in Tiled? It helps a great deal in making sure your colliders are pixel-accurate.

![image](https://user-images.githubusercontent.com/6980630/91381552-4c349000-e7ed-11ea-9156-a723235a3660.png)

Using pixel snapping I can make sure the collision box around my tree tile is perfectly 16x16 pixels:

![image](https://user-images.githubusercontent.com/6980630/91381601-69695e80-e7ed-11ea-947e-734f9bbb9266.png)

Note that when importing into Unity all my colliders are grouped into one big blob like so ...

![image](https://user-images.githubusercontent.com/6980630/91381647-84d46980-e7ed-11ea-81d2-a9184449888e.png)

If I wanted to give my trees some space behind them for sprites to move about I might make the collider box on them only half the height ...

![image](https://user-images.githubusercontent.com/6980630/91381701-a5042880-e7ed-11ea-8d24-4cb64fd131c2.png)

... when I save those changes you can see I now have rows of trees colliders ...

![image](https://user-images.githubusercontent.com/6980630/91381765-c36a2400-e7ed-11ea-91e7-a0d0467c58ff.png)

Hope that helps.

**Comment by Seanba** [comment]
Hi there. I'm going through old bugs that I think are resolved and closing them out. If this still requires support let me know. Thanks.
