### ISSUE TITLE
Problem loading TMX file into Unity 2019.4.6f1?

### ISSUE THREAD

**Issue by Thundros** [Seanba/SuperTiled2Unity#149]
Hi @Seanba! For some reason when trying to load my TMX into Unity, I get this error : 

![SuperTiled2Unity-tiles-issue](https://user-images.githubusercontent.com/32390102/89748609-9dbceb00-da89-11ea-87d6-ad5fb9f292c8.png)

How can I fix this?

Thank You so kindly!

Regards, 

Mythros

**Comment by Seanba** [comment]
Hi there, @Thundros. This is fairly common issue for people starting off with ST2U. It means your `platformPack_tilesheet.png` file is either not in your project or it is in the wrong location. According to this error the file should be up two directories and then down in a folder named `tilesets`.

Are you familiar with relative paths between files and folders? That kind of knowledge will help you track down this issue.

**Comment by Thundros** [comment]
Hi @Seanba ! Yea, I finally got it figured out! Thank you VERY much! I also had a quick question about Collisions as well if you don't mind answering that as well! PLEASE keep up the GREAT work to SuperTiled2Unity! I see it going VERY far in the VERY near future! <3

Regards, 

Thundros

**Comment by Seanba** [comment]
Hi again, @Thundros. I have limited availability for side-projects especially during these pandemic times.

I'm glad you figured this issue out. I'll close this and answer your other question there.
