### ISSUE TITLE
Level is messed up

### ISSUE THREAD

**Issue by 64BitUniverse** [Seanba/SuperTiled2Unity#151]
I don't know how to describe it, it's just a jumbled mess. here's a photo:

![Screenshot (7)](https://user-images.githubusercontent.com/17104044/90337530-13a4e300-dfb1-11ea-8c72-00b18a77b038.png)

I originally thought this was caused by Unity 2020, since it was working fine in 2019 LTS. I re-downloaded the files on my GitHub Repo and it still did this. I have no idea what is causing it. I've tried deleting the object in my hierarchy and I updated ST2U to 1.9.2.

Any help would be appreciated

**Comment by 64BitUniverse** [comment]
Oh, and it looks fine in Tiled

**Comment by Seanba** [comment]
Hi there, @64BitUniverse. A picture of how it's supposed to work may help to further debug but at first blush it looks to me that your map and your tilesets are using a different `Pixels Per Unit` settings. If you look at your map in the inspector you should see a warning alerting you to such.

Hope that helps.

**Comment by 64BitUniverse** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/17104044/90338545-5ddd9280-dfb8-11ea-9528-f7ab63db4521.png)
Here's the level
Do you mean the Default Pixel Per Unit in the Project Settings?

**Comment by 64BitUniverse** [comment]
Changed it, and forced ST2U to use Default Import Settings and it's fixed! I feel sorta daft for not checking the Pixels Per Unit

**Comment by Seanba** [comment]
I'm glad you got it working, @64BitUniverse. Good luck with your game.

**Comment by 64BitUniverse** [comment]
Thanks Seanba, and thanks for this amazing program.
