### ISSUE TITLE
Remove tiles collision individually

### ISSUE THREAD

**Issue by Hirosam1** [Seanba/SuperTiled2Unity#157]
Hi there, I wish to remove collision from individuals tiles (as well the tile itself), like destroying the tile. I managed to set individuals tiles from the tilemap to null, so they stop rendering, however, the collision from the removed tile stays. Is there any way to remove the collision from individual tiles?  Thanks!

I see you use your own collider program, instead of the native tilemap collider, if I could use the tilemap collider, maybe I could disable collision of individuals tiles.

**Comment by seanb-22ct** [comment]
Hi there, @Hirosam1. If you are going to be removing tiles during gameplay then it would be best to make an `Object Layer` (in Tiled) for those dynamic tiles and place `Tile Objects` in that layer. The polygon colliders on a `Tile Layer` do not update their geometry in realtime.

**Comment by Seanba** [comment]
I'm going to close this bug out but if further support is needed let me know.
