### ISSUE TITLE
Is there a roadmap for the future of this tool?

### ISSUE THREAD

**Issue by lrtanner** [Seanba/SuperTiled2Unity#16]
I am really interested in this tool! It looks slick and the demo project you have shows off some really powerful integration. I have two questions for you:

1. Do you have plans for the immediate future of this tool?
2. Is this tool intended to fully replace the old one eventually? I don't mind the extra step to import the tiles if it means I get more overall features. I just want a tool that can give me the most power and control over how much of my level design gets to (efficiently) live inside Tiled.

**Comment by lrtanner** [comment]
I am just now starting to look into using this tool in my current project, so I have not figured out exactly what it can do yet.

What I can do is tell you what I want to do and you can tell me if this is beyond what either of the tools can do currently.

I would like to have the ability to add custom properties to a given tile that can be interpreted in my game and result in custom Monobehaviors being assigned to the resulting tiles/objects.

A made-up example would be for me to have a door tile in Tiled that has two custom properties on it:
my-custom-monobehavior-field=MyDoorController
my-custom-destination-id-field=123

Can ST2U or T2U be leveraged to result in a tile/object in Unity with a "MyDoorController" monobehavior on it?

**Comment by Dalqin** [comment]
Very doable in both ST2U and T2u, though I recommend using ST2U as it leverages Unity's recent Tilemap and grid system.

The project has an example of how to use itself, provided [here](https://github.com/Seanba/SuperTiled2Unity/tree/master/SuperTiled2Unity/Assets/SuperTiled2Unity/Examples).

Visit light documentation on ST2U features with properties set in Tiled:
https://supertiled2unity.readthedocs.io/en/latest/index.html

Visit the super simple example in the source code:
https://github.com/Seanba/SuperTiled2Unity/blob/036e1b59c9633783a0692bbd875cb0967be5927e/SuperTiled2Unity/Assets/SuperTiled2Unity/Scripts/Editor/CustomImporters/CustomTmxImporter.cs

Let me know if you need more guidance? I've used this importer function to replace objects created in Tiled with prefabs, which is not far from your described idea.

**Comment by TannerMoore** [comment]
Awesome to hear! I will be giving this a pretty detailed look Friday and I will report back here on what I accomplish.

**Comment by Seanba** [comment]
Hi @lrtanner. Your game looks cool. I'm glad SuperTiled2Unity was a help.

FWIW, I've added a [Roadmap to the wiki page](https://github.com/Seanba/SuperTiled2Unity/wiki/Roadmap). If there's something you want added to the list let me know.

**Comment by lrtanner** [comment]
@Seanba - Thanks! Glad to hear the tool will keep developing!
