### ISSUE TITLE
Support for .world files?

### ISSUE THREAD

**Issue by darkgriffin1986** [Seanba/SuperTiled2Unity#162]
I'd like to suggest some light support for .world file parsing.

For my current project, I've been using Tiled's ".world" format to lay out rooms for a metroidvania.  Now I need to bring those maps into unity.  There will be hundreds of these maps in the final game, and we might shuffle their positions around a bit as we continue to create and edit the maps.  

For reference, the .world format is simply a tree of maps with extra coordinates to offset each one.  See: [https://doc.mapeditor.org/en/stable/manual/worlds/#working-with-worlds](https://doc.mapeditor.org/en/stable/manual/worlds/#working-with-worlds) for details.

My thoughts are that SuperTiled is already bringing in the maps as prefabs.  I want to be able to also import the .world files, and have SuperTiled create a "world" prefab, with all the map prefabs as children inside that with the offsets from the world file.

I also need to be able to add some custom code to the world prefab creation to create the room transitions and camera boundaries (We are using Corgi Engine's room system).  I understand this would involve me extending your importing classes.

If this is out of scope, I'd appreciate any pointers on how to get started myself!  I'm pretty new to both SuperTiled's code and the concept of custom importers.

**Comment by Seanba** [comment]
I think world support sounds like a good idea. The ongoing pandemic has been disruptive to all my hobby efforts but I'll try to find some time for this over the holidays. Thanks for the suggestion.

**Comment by Seanba** [comment]
Hi there, @darkgriffin1986. Just in time for the holiday end I've updated SuperTiled2Unity to support `*.world` file importing.

You can get this version of SuperTiled2Unity here: https://seanba.itch.io/supertiled2unity/devlog/209521/supertiled2unity-version-1100

Check it out and let me know if it works for you. With it working we can tackle custom importing next for whatever hookups you want to do between your maps.

**Comment by darkgriffin1986** [comment]
Sorry for the late reply, been away on New Years Holiday.

The update works wonderfully, thanks!

I will need to research the camera and scene bounds code for the Corgi
Engine first before I can tell you what else needs to be done.  The engine
has a specific setup for making metroidvania room/camera bounds and
transitions.  I'll continue looking over the examples and see what
requirements I have for map hookups.

Gawain

**Comment by Seanba** [comment]
Hi there, @darkgriffin1986. I'm going to close this issue for now as world support has now been added.

If you having issues with custom importing please open another issue specific to that and I'll try to help you out. Thanks.
