### ISSUE TITLE
Fatal error - size overflow in allocator

### ISSUE THREAD

**Issue by imgalone** [Seanba/SuperTiled2Unity#171]
Hello,

I am running into a problem, out of the blue, when trying to start my project (I haven't worked with supertiled2unity recently, I was last working on my ui prior to this). No matter how far back I go onto my commits history I keep getting this error and I have no idea what it is or what may have caused it. I can't access my project because of it.

[Error Screenshot](https://i.imgur.com/rWq4wXJ.png)

**Unity version: 2019.4.19f1**
**What I've tried so far**
* went back a number of commits --> NOK, same error
* moved my entire project folder to a shorter path (ie: D:\Folder1\ProjectFolder) --> NOK, same error
* update unity to version  2019.4.20f1 --> NOK, same error
* deleted the library folder --> **OK**, I can now start the project without encountering the error

I would appreciate any suggestion,
Thank you.

**Comment by imgalone** [comment]
Although I have solved the issue, I will leave it opened in case there is some actual useful information here for anyone else to see.

**Comment by Seanba** [comment]
Hi there, @imgalone. This looks like something that happens with Unity from time-to-time. However, since the bug was reported within ST2U I'd like to know if you have particularly large TMX or TSX files.

**Comment by imgalone** [comment]
Hi there @Seanba,

Thank you for your reply. I don't think it's big but to be honest, I don't really have enough experience with these things to know what a *large* file is. I only made one level in tiled, which is not particularly complicated or complex. If you want I can send it to you if you think it would help.

My one .tmx file is 41 KB and most if not all of my .tsx files are 1 KB (with the exception of one which is 12 KB)

Please let me know if I can do anything else to help.

Best regards,
Iancu

**Comment by Seanba** [comment]
Those files sizes should be fine. I've done some additional investigation and it does appear that this is something Unity just does under some conditions. I'll close this bug for now and will keep in mind that deleting the library folder is a work around. Thanks.
