### ISSUE TITLE
Reserialize meta files

### ISSUE THREAD

**Issue by elexis1** [Seanba/SuperTiled2Unity#172]
There is an annoying bug with ST2U:

The *.tsx.meta or *.tmx.meta file contains some information that changes depending on the content of the asset file, but the meta file is not updated in case the content changes.

This is two pieces of information:
- numberOfObjectsImported
- errors

A third example is if ST2U has been updated and changed the layout, but the file still wasn't reserialized to reflect the new layout.
This can be seen even with the ST2U provided examples:
```
diff --git a/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/TestOverhead.tmx.meta b/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/TestOverhead.tmx.meta
index 0a1d8f67..d2d4431b 100644
--- a/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/TestOverhead.tmx.meta
+++ b/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/TestOverhead.tmx.meta
@@ -609,3 +609 @@ ScriptedImporter:
-  errors:
-  - Unity does not support Zstandard compression.
-  - Select a different 'Tile Layer Format' in your map settings in Tiled and resave.
+  errors: []
@@ -619 +617 @@ ScriptedImporter:
-  numberOfObjectsImported: 1
+  numberOfObjectsImported: 2
```

```
diff --git a/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/Zoria Tileset/overhead-objects.tsx.meta b/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/Zoria Tileset/overhead-objects.tsx.meta
index 59e6aed4..17cb1e5d 100644
--- a/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/Zoria Tileset/overhead-objects.tsx.meta      
+++ b/Assets/Others/Extras/SuperTiled2Unity/Examples/Overhead/Maps/Zoria Tileset/overhead-objects.tsx.meta      
@@ -4,8 +4,22 @@ ScriptedImporter:
-  fileIDToRecycleName:
-    2800000: Atlas_Overhead Objects_1
-    11400000: _TilesetScriptObject
-    11400002: _superAsset
-    11400004: Tile_Overhead Objects_1
-    11400006: Tile_Overhead Objects_2
-    21300000: Sprite_Overhead Objects_1
-    21300002: Sprite_Overhead Objects_2
+  internalIDToNameTable:
+  - first:
+      28: 2800000
+    second: Atlas_Overhead Objects_1
+  - first:
+      114: 11400000
+    second: _TilesetScriptObject
+  - first:
+      114: 11400002
+    second: _superAsset
+  - first:
+      114: 11400004
+    second: Tile_Overhead Objects_1
+  - first:
+      114: 11400006
+    second: Tile_Overhead Objects_2
+  - first:
+      213: 21300000
+    second: Sprite_Overhead Objects_1
+  - first:
+      213: 21300002
...
```

The only time when the meta files are reserialized is when one changes the options and presses the Apply button.

The negative consequence of only reserializing when one changes a setting is that the resulting diff is bloated with unrelated changes, so people looking at the patch wonder where those changes came from, making it harder to maintain.

On the flipside, if people always reserialize their data when their content changes (either by ST2U doing that automatically then, or by people pressing a button regularly), one not only gains the improved reviewability of commits but also the information how many `numberOfObjectsImported` changed when one changed the content or import settings or import code.

It is especially annoying if there are false positive error messages saved in the meta file that actually have been obsolete since months.

(Also for the record this "frequent reserialization" feature was also relevant to the ugly python script uploaded at https://github.com/Seanba/SuperTiled2Unity/issues/37#issuecomment-792117189 )

Here our patch to provide such a button:
```
commit b974f2452a2626f2a4f334da92a134f96dc75075
Author: Alexander Heinsius <email@email.email>
Date:   Mon Mar 8 19:20:43 2021 +0100

    SuperTiled2Unity: New button to force-reimport selected assets.
    
    This allows us to keep the information in the *tsx.meta file up to date when we change the *.tsx file.

diff --git a/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Config/SuperTiled2Unity_Config.cs b/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Config/SuperTiled2Unity_Config.cs
index b6f9a311..84981601 100644
--- a/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Config/SuperTiled2Unity_Config.cs
+++ b/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Config/SuperTiled2Unity_Config.cs
@@ -52,6 +52,17 @@ namespace SuperTiled2Unity.Editor
 
         [MenuItem("Assets/SuperTiled2Unity/Apply Default Settings to ST2U Assets")]
         public static void ReimportWithDefaults()
+        {
+            Reimport_TiledAssetImporters(true);
+        }
+
+        [MenuItem("Assets/SuperTiled2Unity/Reimport ST2U Assets")]
+        public static void Reimport()
+        {
+            Reimport_TiledAssetImporters(false);
+        }
+
+        private static void Reimport_TiledAssetImporters(bool save_defaults)
         {
             UnityEngine.Object[] selectedAsset = Selection.GetFiltered(typeof(UnityEngine.Object), SelectionMode.DeepAssets);
             HashSet<TiledAssetImporter> tiledImporters = new HashSet<TiledAssetImporter>();
@@ -68,7 +79,10 @@ namespace SuperTiled2Unity.Editor
 
             foreach (var importer in tiledImporters)
             {
-                importer.ApplyDefaultSettings();
+                if (save_defaults)
+                    importer.ApplyDefaultSettings();
+                else
+                    importer.ApplyCurrentSettings();
             }
 
             foreach (var importer in tiledImporters)
diff --git a/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs b/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs
index 491098a2..2b0e97e9 100644
--- a/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs
+++ b/Assets/Others/Extras/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs
@@ -118,6 +118,11 @@ namespace SuperTiled2Unity.Editor
             EditorUtility.SetDirty(this);
         }
 
+        public void ApplyCurrentSettings()
+        {
+            EditorUtility.SetDirty(this);
+        }
+
         protected override void InternalOnImportAsset()
         {
             m_RendererSorter = new RendererSorter();
```

As mentioned it might be reasonable it SuperTiled2Unity would automatically reserialize the meta file if the content changed.

**Comment by Seanba** [comment]
Hi there, @elexis1. If I understand you correctly this all comes down to ST2U invoking `EditorUtility.SetDirty(this);` at the appropriate time. Is that right?

**Comment by Seanba** [comment]
I've tested your SetDirty suggestion and have it being automatically called during asset import. Thanks for the tip. The fix is available in version 1.10.1

https://seanba.itch.io/supertiled2unity/devlog/231859/supertiled2unity-version-1101

**Comment by elexis1** [comment]
Fixed in 5442826224af004dc2f6d1b8d315179c864f888c.

Yes, that's the ideal place to insert the SetDirty call, it was missing for a long time!

It also fully removes the need for such a button to flush out the garbage in existing files, because one can select old files, rightclick, reimport to achieve that.

You might want to do that for the assets in the ST2U repository, since there is still some left, e.g. the *.tsx file mentioned in the first post.

Thanks for the fix!

**Comment by elexis1** [comment]
I would highly recommend to reimport the following files:

```
Examples/Overhead/Maps/Zoria Tileset/overhead-objects.tsx.meta
Examples/Overhead/Maps/Zoria Tileset/scraps.tsx.meta
Examples/Overhead/Maps/Zoria Tileset/tiles.tsx.meta
Examples/Overhead/Maps/Zoria Tileset/water.tsx.meta
```
When we open Unity and it imports these files, it will modify these files, so they show up on a git commit as changed, and, as of this SetDirty change. (And we cannot revert this change locally to make the change disappear anymore, since it will automatically reappear again).

**Comment by Seanba** [comment]
Thanks, @elexis1. I have reimported these files with the latest version of SuperTiled2Unity.
