### ISSUE TITLE
Layer Tint Color not working

### ISSUE THREAD

**Issue by RotcivOcnarb** [Seanba/SuperTiled2Unity#173]
I wanted to create a shadow effect on my tilemap, by duplicating one of the layers and setting the layer Tint Color to transparent black

In the Tiled editor everthing works fine:
![image](https://user-images.githubusercontent.com/17129106/111040568-3d709c00-8412-11eb-83dc-858cda212cf6.png)

But when importing into unity, it seems the Tint Color is not being read into the tiled layer

![image](https://user-images.githubusercontent.com/17129106/111040587-5bd69780-8412-11eb-9131-2cf1191fc5b1.png)

I can manually set the Tile Map Color property manually, and the desired effect shows up, but I think it would be nice for the importer to automatically detect the Tint Color of the layer and just change the tint color of the Tilemap layer in unity

![image](https://user-images.githubusercontent.com/17129106/111040623-8f192680-8412-11eb-8d3a-41c17d141201.png)

**Comment by RotcivOcnarb** [comment]
I have created a custom importer that can do this for me, but it is still not the ideal way I think it should be done

First of all, when I see the ```SuperTileLayer``` component in the layer, I see all the properties of the layer, except the colorTint:

![image](https://user-images.githubusercontent.com/17129106/111042030-fbe3ef00-8419-11eb-9a56-7db945d9c9fe.png)

So my approach was to simply duplicate the color tint property as a Custom Property in the layer

![image](https://user-images.githubusercontent.com/17129106/111041980-bfb08e80-8419-11eb-9c69-065b2ec8556d.png)

and used it in the CustomTMXImporter to apply the tilemap tint

![image](https://user-images.githubusercontent.com/17129106/111041992-d35bf500-8419-11eb-8acd-0879aca95709.png)

It works nicely, but it would work better if I didn't need to duplicate the color property

**Comment by Seanba** [comment]
Hi there, @RotcivOcnarb. I wonder if Tint Color is a fairly recent features to Tiled? It seems like something I would have supported if I knew about it.

In any case I'll get this into the next version of ST2U. Thanks for letting me know about it.

**Comment by RotcivOcnarb** [comment]
Nice!

Thank you!

Looking forward for the next update!

**Comment by Seanba** [comment]
You're welcome. I'll keep this issue open until I'll delivered the feature though. :)

**Comment by Seanba** [comment]
Support for tint color has been added to ST2U 1.10.1. Thanks for letting me know of this missing feature.

https://seanba.itch.io/supertiled2unity/devlog/231859/supertiled2unity-version-1101
