### ISSUE TITLE
Reimport tiled assets error

### ISSUE THREAD

**Issue by cephen** [Seanba/SuperTiled2Unity#18]
Hey, encountered this bug today after downloading 1.1.4

```
EndLayoutGroup: BeginLayoutGroup must be called first.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

Steps to reproduce: 
1. Import SuperTiled2Unity unitypackage
2. Import any .tmx asset
3. Click Reimport Tiled Assets in ST2U settings asset

Didn't get any other error messages or any other error details

**Comment by Seanba** [comment]
I haven't been to reproduce this bug using several different versions of Unity, both pro and free. Closing for now but feel free to re-open if you have more information I can use. Thanks.
