### ISSUE TITLE
AssetDatabase.rRefresh takes very long

### ISSUE THREAD

**Issue by rolandjmoritz** [Seanba/SuperTiled2Unity#180]
Hi! I am having extremely long import times with Unity 2020.1.14f1 and SuperTiled2Unity1.10.1. I have about 8 TMX tilemaps and 2 Tilesets in my project, not very large - the tilemaps are max. 50x50, the tileset contain about a few hundred tiles. They do have 6-8 layers each. Everytime I change something in a tilemap, "AssetDataBase.Refresh()" takes at 3-4 minutes, sometimes longer. The project itself is not too big, it's a 2D game with no large models or such. What could cause this? Should I update to a newer Unity version?

**Comment by Seanba** [comment]
That doesn't seem right to me. Do you have any other plugins in your project? One thing to try is to delete your `Library` folder. If you still have an issue I can try taking a look if your share your project with me.

**Comment by Seanba** [comment]
Hi there. Without further information I'm going to close the bug out but if you (or others) are still experiencing slow `AssetDatabase.Refresh()` times let me know. Thanks.
