### ISSUE TITLE
Tilemap is darker in unity than in Tiled editor and source image

### ISSUE THREAD

**Issue by Amelebak** [Seanba/SuperTiled2Unity#181]
I have a blue/grey brick tileset that appears darker once imported to Unity. 

One of the colors, for example, is (90, 100, 36), in the source image. In the Tiled editor, the colors match the source image. After importing to Unity using SuperTiled2Unity, the map is darker, with that specific color appearing as (26,36,64). If I disable "Use Sprite Atlas for Tiles," the colors are correct (but I get highly visible seams). 

I do not have any tints on the map layers. 

Any guidance would be appreciated.

**Comment by Seanba** [comment]
Hi there, @Amelebak. Which version of Unity are you using? And is the image darker in the Unity Scene View, Game View, or in your build executable (and if so on what platform?).

**Comment by Amelebak** [comment]
2020.1.2f1

The image is darker in Scene View, Game View, and a Windows build. So it's consistent between those 3, but not with the Tiled Map Editor or when viewing the tileset source png.
________________________________

**Comment by Seanba** [comment]
How about if you try the `overhead` scene that comes with SuperTiled2Unity? Does that look dark too?

Scene: `Assets/SuperTiled2Unity/Examples/Overhead/overhead.unity`
Tiled file: `Assets/SuperTiled2Unity/Examples/Overhead/Maps/TestOverhead.tmx`

**Comment by Amelebak** [comment]
TestOverhead.tmx looks fine when I drag into into my scene, or when I open the overhead.unity scene. There's no color changes.

I'm not sure if it's relevant, but testOverhead is significantly larger than my test map. My test map uses a 64x64 tileset.

**Comment by Seanba** [comment]
Your tileset size should be fine. Is it possible for me to get a copy of your project?

**Comment by Amelebak** [comment]
Unfortunately I'm not in a position where I can share these assets.

However, I've gotten around the issue, in part due to your suggestion of trying known-good assets. Here's what I did:


  *   Saved a copy of my source tileset PNG
  *   moved the PNG to the same directory as my TMX files
  *   Made a TMX map, with a new tileset, using the 'new' PNG
  *   Imported the TMX map to unity using SuperTiled2Unity


It is working as expected!

I'm sorry that I'm not able to provide any more information. Thank you for providing SuperTiled2Unity, and thank you for your prompt attention!

________________________________

**Comment by JoshMayberry** [comment]
@Seanba, I am having this issue too and can share my tileset with you.
[tiles.zip](https://github.com/Seanba/SuperTiled2Unity/files/15492062/tiles.zip)

Here is a screenshot of what it looks like in unity:
![image](https://github.com/Seanba/SuperTiled2Unity/assets/11482252/065ed055-bf50-4693-b542-e35883f5b15e)
The things with red arrows pointing to them should be the same color; The darker one is from the tileset. The lighter one is a sprite object.

**Comment by JoshMayberry** [comment]
Your Overhead map does NOT look dark when I open it in the same project.

The main difference between our projects was you had your .png in the same folder as your tileset- and I did not.
**Moving it into the same folder fixed the darkness issue.**

I don't want to have them in the same folder though; Would you be able to fix this?

**Comment by seanb-22ct** [comment]
Thanks for providing your assets. I'll try to take a look at this soon. Moving the files around to different folders shouldn't change anything except to fix dependency issues between map, tileset, and texture files from the point of view of Tiled.
