### ISSUE TITLE
Importing/Reimporting assets freezes Unity

### ISSUE THREAD

**Issue by aricleighton** [Seanba/SuperTiled2Unity#184]
I've used ST2U and Tiled before with no issue. It's been a few weeks since I've worked on the project, and my Tiled map has been updated considerably. It's 300 x 150 tiles at 10px per tile.

It wasn't letting me import for a long time, so I updated ST2U and Tiled just to make sure everything was good. I'm using Unity Version 2020.3.9f1. It finally let me import after that, but it shows my main tilemap as a small T as pictured.
![image](https://user-images.githubusercontent.com/86164903/122650907-6b493900-d103-11eb-88f3-30551bd5dc5e.png)
![image](https://user-images.githubusercontent.com/86164903/122650921-861bad80-d103-11eb-96ca-8352e615eafd.png)

So, obviously this doesn't work or didn't import right. If I try to reimport the tilemap or any of it's dependecies I get this:
![image](https://user-images.githubusercontent.com/86164903/122650957-bc592d00-d103-11eb-92d2-c8cdda97afa1.png)

And then it freezes Unity and never reimports or does anything. I tried opening a blank project and just importing the tilemaps, and it does the same thing. The tilemaps open in Tiled and have no issues. When I open the new project with only ST2U it shows this:
![image](https://user-images.githubusercontent.com/86164903/122651060-646ef600-d104-11eb-8eb5-282273184119.png)

This makes me believe it's something with ST2U.

**Comment by aricleighton** [comment]
Hey @Seanba, I appreciate you getting back to me at all. I believe I have the project kicking around.

I left it for ~30 minutes and it finally used the tilemap. It seems to be treating it like a huge file, but Tiled files are fairly small. What's the best way to get you a file?

**Comment by Seanba** [comment]
Hi there, @aricleighton. Without further information I'm going to close this issue for now. Feel free to re-open if you're still having issues and you can share your files with me. Thanks.
