### ISSUE TITLE
Hello I have a problem with the Super Tiled2Unity which does not allow me to put my created maps

### ISSUE THREAD

**Issue by ElBromena** [Seanba/SuperTiled2Unity#186]
Hello I have a problem with the Super Tiled2Unity which does not allow me to put my created maps, please I need help :c

I get these 2 errors
1#:
SuperTiled2Unity version: 1.10.2, Unity version: 2020.3.12f1
This asset is dependent on other files that either cannot be found or they failed to be imported.
Note that all Tiled assets must be imported to Unity in folder locations that keep their relative paths intact.
Reimport this asset once fixes are made.

Tip: Try opening Mundo.tmx in Tiled to resolve location of missing assets.

Assets/SuperTiled2Unity/Mundo.tsx
2#:
SuperTiled2Unity version: 1.10.2, Unity version: 2020.3.12f1
Missing tileset asset: ../Mundo.tsx

**Comment by phybros** [comment]
Your tilemap is referencing a tsx (tileset) called Mundo.tsx which it expects to find in the folder one level above the tmx file (../ means "up one level").

So you could just make a new folder and put the tilemap in it. And then put the tileset in the same folder as the new folder you just created and that should resolve your issue.

**Comment by Seanba** [comment]
Hi there, @ElBromena. This is a common user error when TMX, TSX, and texture files are imported into the "wrong" directories in your Unity application. Keep in mind that relative paths between these files must be kept in tact when you put them into Unity.
