### ISSUE TITLE
Custom Importer for handling Sprite Depth within a single Sorting Layer

### ISSUE THREAD

**Issue by MabLuxx** [Seanba/SuperTiled2Unity#19]
I've been working with Tiled for about a year now and have yet to land on a reliable method for handling this issue.  What I'd like to achieve is the ability for character sprites to weave in front of or behind environment sprites based on y-position of each (higher y-values behind lower y-values).  

Attaching the script **Overhead Sprite Sorter** (included in ST2U unity package) to character sprites allows for control over each particular sprite's depth by adjusting the **Order in Layer** value of the attached Sprite Renderer.  So this works!

![depthtrackingorderinsortinglayer_a](https://user-images.githubusercontent.com/43322300/49316276-ffa40f80-f4b5-11e8-9763-59a01820ef31.PNG)

![depthtrackingorderinsortinglayer_b](https://user-images.githubusercontent.com/43322300/49316288-06cb1d80-f4b6-11e8-8730-1b3a2e323be2.PNG)

However, by default Tiled imports maps with each layer having assigned a specific **Sorting Layer** and **Order in Layer**.  What this means is that characters can either be in front of or behind an entire layer at once.

<img width="150" alt="image_a_trees" src="https://user-images.githubusercontent.com/43322300/49316454-9ffa3400-f4b6-11e8-9130-bcf5f7a04a06.PNG">

<img width="288" alt="image_a" src="https://user-images.githubusercontent.com/43322300/49316476-ae485000-f4b6-11e8-81db-ab3f9b54acba.PNG">

I've since recently upgraded to ST2U and noticed that it allows for .tmx files to import tiles as individual objects.  With Tiles as objects, the **Overhead Sprite Sorter** script can now be attached to each tile as necessary.

![image_b_settings](https://user-images.githubusercontent.com/43322300/49316867-fc118800-f4b7-11e8-966d-0baef1a2da01.PNG)

<img width="160" alt="image_c" src="https://user-images.githubusercontent.com/43322300/49316876-05025980-f4b8-11e8-8771-9820dd1133cd.PNG">

<img width="278" alt="image_b" src="https://user-images.githubusercontent.com/43322300/49316880-06338680-f4b8-11e8-9256-b8bc0976d981.PNG">

This solves the problem aesthetically, as each environment sprite is now assigned a specific **Order in Layer** based on y-position, but quickly leads to an overflow of objects in Unity.

What I'd ultimately like to achieve (if it's even possible) is a **Custom Import Script** that renders sprites within a single **Sorting Layer** to have their **Order in Layer** assigned based on y-position in Unity.

Can this be done without forcing each tile to be an object?

**Comment by Seanba** [comment]
There's a new render mode for the Unity `TilemapRenderer` coming that supports `Chunk` and `Individual`. I'm hoping that gives us better control over how a tilemap is rendered but I haven't looked at it yet. It looks like it's available with Unity 2018.3 so if you happen to play with it let me know your findings.

**Comment by Seanba** [comment]
Here's a good link: https://docs.unity3d.com/2018.3/Documentation/Manual/Tilemap-Isometric-RenderModes.html

I hate to fix bugs that are dependent on beta versions of Unity but let me get familiar with this and see what can be done.

**Comment by MabLuxx** [comment]
Very cool.  It sure does seem like this feature in Unity could be utilized.  I’ll look into it as well.  Thanks!

**Comment by david-bingham** [comment]
Seanba, looks like I emailed you before prematurely. Glad this is on your radar. Any update on ST2U sorting in the last 4 months?

**Comment by Seanba** [comment]
Hi there, @david-bingham and @MabLuxx. I'm working on this for my next demo. I did recently add a new sorting mode to the TMX importer (`Custom Sort Axis`) to better support isometric maps. That combined with a custom `Transparency Sort Axis` will almost gets us there (and in fact will work if you have everything on one tile layer) but I need to do some additional work to better group Tilemaps for sorting.

![image](https://user-images.githubusercontent.com/6980630/54733700-050e8e00-4b69-11e9-972b-c4bef91817c3.png)

![image](https://user-images.githubusercontent.com/6980630/54733703-0a6bd880-4b69-11e9-9857-707afe3b77cb.png)

I'm sorry the whole thing seems like it should "just work" but that's I think we'll get it there. Unity is great but the general purpose nature of it has a dark side.

**Comment by Seanba** [comment]
SuperTiled2Unity verion 1.3.0 makes it easier to accomplish the kind of sorting that you'd like.

I've updated to docs to talk about this a bit more but as expected you will need to use a Custom Axis.

https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html
