### ISSUE TITLE
Wrong Height of Hexagonal Tilemaps

### ISSUE THREAD

**Issue by mirrorlink** [Seanba/SuperTiled2Unity#197]
First of all, great plugin.

I've encountered a problem with it. To be fair I think this problem is probrably on the unity side, but I wonder if it can be workarounded on the plugin.

The hexagonal tilemaps have wrong height.

I've attached an example map:

[Maps.zip](https://github.com/Seanba/SuperTiled2Unity/files/7776370/Maps.zip)

In TiledMap:
 
![image](https://user-images.githubusercontent.com/58230638/147251469-000c4448-cd17-4181-af9f-e71fa298fc21.png)

In unity:

![image](https://user-images.githubusercontent.com/58230638/147251520-dcb1096f-87e6-453a-a86d-8298db5bbfe4.png)

If I adjust the Cell Size, it works, but the collisions become wrong

![image](https://user-images.githubusercontent.com/58230638/147251569-27e9a8d6-4d2b-4eb6-be4c-605691927366.png)

Also, it seems the value of Hex Side Length is being ignored

Any way we could get around it? Trying on 2021.2.7f1

Tks!

**Comment by mirrorlink** [comment]
Also, it seems the value of Hex Side Length is being ignored

**Comment by mirrorlink** [comment]
I found a workaround using a custom importer

public class CustomHeightAdjustImporter : CustomTmxImporter
{
    public override void TmxAssetImported(TmxAssetImportedArgs args)
    {
        Grid[] grids = args.ImportedSuperMap.GetComponentsInChildren<Grid>();

        for (int i = 0; i < grids.Length; i++)
        {
            grids[i].cellSize = new Vector3(1, 0.963f, 1);
        }
        SuperColliderComponent[] colliders = args.ImportedSuperMap.GetComponentsInChildren<SuperColliderComponent>();

        for (int i = 0; i < colliders.Length; i++)
        {
            colliders[i].transform.localScale = new Vector3(1, 0.963f, 1);
        }
    }
}

**Comment by Seanba** [comment]
Hi there, @mirrorlink. I'm happy to take a look but there a missing `hexCollision.tx` template file that is preventing the map from being fully imported into Unity successfully.

**Comment by Seanba** [comment]
So what I think is happening here is that Unity is hard-coded to only support "canonical" hexagon maps. These are maps that have an side length that is equal to half of your tile height (in your case, 9 pixels).

But, Tiled looks at the side-length that you entered and from that uses the largest even number that is less-than-or-equal-to that value. In your case, that would be 8 pixels.

In other words: You want a hex grid (in Unity) that uses a side-length of 8 pixels but given your map of tile width/heights of 18 the (internal) side-length will always be 9. This is why your tiles are off by one pixel along the y-axis.

Your custom importer is an interesting fix but I wonder if that won't bite you later on. It would be better, IMHO, to find a solution that is more robust.

Since hexagons are a specialization of staggered isometric maps you can accomplish what you want by faking your hex map. You have to get your dimensions just right though. For you that will be to take the even-numbered-side-length of 8 and add it to your "regular" tile height of 18. (In other words, you'll have an 18x26 staggered isometric map.)

![image](https://user-images.githubusercontent.com/6980630/147375791-527513d5-adf8-4805-bd4c-5076e7f1c7e2.png)

![image](https://user-images.githubusercontent.com/6980630/147375901-198715c2-7afd-4dbe-be2f-7420c26b78f3.png)

![image](https://user-images.githubusercontent.com/6980630/147375904-96bb02af-4b3a-4311-b279-4310116f97be.png)

**Comment by mirrorlink** [comment]
Hey @Seanba ! I'm very sorry, I dont know what was on my mind, here it is with the missing file
[Maps.zip](https://github.com/Seanba/SuperTiled2Unity/files/7776370/Maps.zip)

**Comment by mirrorlink** [comment]
> So what I think is happening here is that Unity is hard-coded to only support "canonical" hexagon maps. These are maps that have an side length that is equal to half of your tile height (in your case, 9 pixels).
> 
> But, Tiled looks at the side-length that you entered and from that uses the largest even number that is less-than-or-equal-to that value. In your case, that would be 8 pixels.
> 
> In other words: You want a hex grid (in Unity) that uses a side-length of 8 pixels but given your map of tile width/heights of 18 the (internal) side-length will always be 9. This is why your tiles are off by one pixel along the y-axis.
> 
> Your custom importer is an interesting fix but I wonder if that won't bite you later on. It would be better, IMHO, to find a solution that is more robust.
> 
> Since hexagons are a specialization of staggered isometric maps you can accomplish what you want by faking your hex map. You have to get your dimensions just right though. For you that will be to take the even-numbered-side-length of 8 and add it to your "regular" tile height of 18. (In other words, you'll have an 18x26 staggered isometric map.)
> 
> ![image](https://user-images.githubusercontent.com/6980630/147375791-527513d5-adf8-4805-bd4c-5076e7f1c7e2.png)
> 
> ![image](https://user-images.githubusercontent.com/6980630/147375901-198715c2-7afd-4dbe-be2f-7420c26b78f3.png)
> 
> ![image](https://user-images.githubusercontent.com/6980630/147375904-96bb02af-4b3a-4311-b279-4310116f97be.png)

So, my Hexagons are actually 19x19 pixels, with 1 pixel overlap, so it ends up 18x18. It seems that tiled, by default, overlaps one pixels at least on the horizontal axis.

Your solution is something new to me. Looks great! I didnt know that was possible. I'll check right away.

If I take one pixel of height, maybe that oughta fix that too? I'll try that too.

Thank you!

**Comment by mirrorlink** [comment]
AWWW YISSS @Seanba 

![image](https://user-images.githubusercontent.com/58230638/147395774-2ccb64e1-d92e-4eb8-bec3-e34688b5d6ee.png)

Crispy af. I'm tottaly going with your suggestion. I'm still making a custom importer So I can create the objects dynamically and check them on the editor. This importer is amazing.

I knew right from the start that that unity was doing something wrong from the get go (I could not do it even if I tried to use the system directly). I havent used unity for about 10 years, I was surprised they didn't implement such a basic feature properly. On unity, hexagons wont work properly if you make hexagonal tiles with the intent of having them overlapping by any amount of pixels, or if they dont have an even width/height. I think 16x16 pixels that don't overlap, for example, would work.

I like to have an odd number, so the hexagon has a 'center pixel'.

**Comment by mirrorlink** [comment]
AWWW YISSS @Seanba 

![image](https://user-images.githubusercontent.com/58230638/147395774-2ccb64e1-d92e-4eb8-bec3-e34688b5d6ee.png)

Crispy af. I'm tottaly going with your suggestion. I'm still making a custom importer So I can create the objects dynamically and check them on the editor. This importer is amazing.

I knew right from the start that that unity was doing something wrong from the get go (I could not do it even if I tried to use the system directly). I havent used unity for about 10 years, I was surprised they didn't implement such a basic feature properly. On unity, hexagons wont work properly if you make hexagonal tiles with the intent of having them overlapping by any amount of pixels, or if they dont have an even width/height. I think 16x16 pixels that don't overlap, for example, would work.

I like to have an odd number, so the hexagon has a 'center pixel'.

**Comment by Seanba** [comment]
> I'm still making a custom importer So I can create the objects dynamically and check them on the editor.

That's a great idea and exactly why I made it so you can extend the importer. You don't want to have to make changes to the generated prefabs "by hand" once the import process is done. Instead, make the importer do all the work for you.

Glad you got it working. Good luck with your game.
