### ISSUE TITLE
Tag not on collider layer

### ISSUE THREAD

**Issue by GarryPlays** [Seanba/SuperTiled2Unity#199]
I added colliders on the tile itself. In the .tsx file.
![image](https://user-images.githubusercontent.com/31503736/150951248-19055b06-2224-4d92-95d4-2c049f94aacc.png)

In my .tmx file I added Tag and layer to my Ground Layer.
![image](https://user-images.githubusercontent.com/31503736/150951433-7a5daa47-321d-425f-8e64-235cecbf6d59.png)

In unity it will create a Collision_Ground automatically.
![image](https://user-images.githubusercontent.com/31503736/150951523-3e6d3470-74fa-48f0-8f58-a1b3cfb88c6b.png)

While the Ground Layer has correctly Tag and Layer set.
![image](https://user-images.githubusercontent.com/31503736/150951600-2037535d-439a-4d0f-be5f-20dd77fb22ce.png)

The Collision_Ground only has the Layer set, not the Tag.
![image](https://user-images.githubusercontent.com/31503736/150951661-4f2905c4-720d-470c-b78a-3ce152161185.png)

I also tried adding unity:Tag to the tile and the collider on the tile. Nothing makes the Collision_Ground pick up the tag.

When creating an object layer and adding the Tag to the Layer, the Layer itself will have the tag, the colliders within not.
However, adding a Tag on such a collider will work correctly in unity.
The layer will be passed correctly to colliders within the layer that have no override, while correctly receiving another layer if the collider has another layer set.

It confuses me that Layers are passed along, while Tags are not.
Might be a bug, might be intentional.

**Comment by Seanba** [comment]
Hi there, @GarryPlays. My apologies for the late reply.

`Tags` and `Layers` are a bit different and therefore the rules of applying to children are not the same. You can see this for yourself in the Unity Editor (without ST2U) when you try to change the `Layer` of a parent object in the Inspector.

![image](https://user-images.githubusercontent.com/6980630/155896496-af65c987-5ce2-40f1-8e98-578654e382a2.png)

Unity doesn't ask you this question if you change the `Tag` on the parent game object.

The reasoning for this is that you get tagged objects in script by calling `GameObject.FindGameObjectsWithTag` and you almost always only want to get a collection of root/parent game objects in that case, not the parent and all it's children.
