### ISSUE TITLE
Importing from an Infinite Tiled map crunches everything together

### ISSUE THREAD

**Issue by VladDerptastic** [Seanba/SuperTiled2Unity#2]
Map settings: Orthogonal, 32x32, Infinite

Importing from an infinite Tiled map crunches everything together into a square, whereas a map with limits on the tiles looks as expected.

Here's a side by side comparison on how it appears in Unity:
![comparison](https://user-images.githubusercontent.com/17119930/46298086-80ba5580-c59e-11e8-84a8-fd1f500be34c.png)

**Comment by Seanba** [comment]
Hi Vlad, I was not handling cases where users were using Pixels Per Unit of 100 (or any value that isn't 1) with infinite maps. Version 1.0.1 fixes this. Thanks for the bug report.
