### ISSUE TITLE
unity:layer option not applying to children

### ISSUE THREAD

**Issue by xThuby** [Seanba/SuperTiled2Unity#202]
I've got a Tiled map with a layer for collisions. These should be assigned to the Ground layer in Unity but although the tilemap becomes assigned to that layer, it's children does not, which causes collisions to not work.

![image](https://user-images.githubusercontent.com/7295432/153732990-4b13849d-6801-43d8-b20e-487863de11b0.png)

![image](https://user-images.githubusercontent.com/7295432/153732997-a1645c53-cd20-45f2-aae6-e0ade089724f.png)

**Comment by Seanba** [comment]
Hi there, @OliverAThunes. Sorry for the late reply.

I just did a quick test and the layers are applying to children. I wonder if you have a `unity:layer` custom property not only on the `Tile Layer` but on `Tileset` properties or maybe within the separate tiles (in the Tiled Collision Editor)? Those later properties will take precedence in that case.

If that doesn't help maybe you can send me your Tiled files and I'll see if there's a bug somewhere. Thanks.

**Comment by rocifier** [comment]
Hi, I also have this exact problem. Here are my files: https://drive.google.com/file/d/1fxSPX299MuC9GXJpFXsszhWzgNXNubh6/view?usp=sharing

**Comment by Seanba** [comment]
My apologies for sitting on this bug for nearly two years. A sickness in the family keeps me away from this project.

In any case this is fixed [with version 2.2.4 of ST2U](https://seanba.itch.io/supertiled2unity/devlog/847632/super-tiled2unity-224).
