### ISSUE TITLE
Possible Object layer position issue.

### ISSUE THREAD

**Issue by jonny64bit** [Seanba/SuperTiled2Unity#205]
I'm using a object layer but when i import into Unity its 1 cell off on the vertical.

Tiled:

![image](https://user-images.githubusercontent.com/3177463/155182824-71da374a-17a6-4447-bd31-1a855d0a965c.png)

Unity:

![image](https://user-images.githubusercontent.com/3177463/155182905-26e623cd-7969-4848-8e5f-94be3ec52f5a.png)

Blue arrow points at object in question.

I worked out i can fix this using the below code.

```
using UnityEngine.Tilemaps;
using SuperTiled2Unity;
using SuperTiled2Unity.Editor;

[AutoCustomTmxImporter()]
 public class FixupTmxImporter : CustomTmxImporter
 {
     public override void TmxAssetImported(TmxAssetImportedArgs args)
     {
        var map = args.ImportedSuperMap;
        foreach (var tilemap in map.GetComponentsInChildren<SuperObjectLayer>())
        {
            var tilemapTransform = tilemap.gameObject.transform;
            tilemapTransform.Translate(0, 1f, 0);
        }
     }
 }
```

Which gives me the correct output.

![image](https://user-images.githubusercontent.com/3177463/155183146-60c70ae6-42c7-4b24-b271-32981f4aa511.png)

I was trying to work out if i just have a setting wrong in tiled but im only just starting with Tiled as a application.

(as an aside thanks for making this script, so easy to use! 👍 )

**Comment by Seanba** [comment]
Hi there, @jonny64bit. You shouldn't have to write a custom importer to translate objects back into place like that. I just did a quick test and confirmed that object layer geometry is appearing where I'd expect it to.

I suspect your map is doing something that ST2U does not properly support yet - perhaps with grouping or offsets? If you send me your Tiled files I should be able to debug and fix. My email is sean@seanba.com. Thanks!

**Comment by jonny64bit** [comment]
@Seanba emailed over, thanks for taking a look.

**Comment by jonny64bit** [comment]
For anyone in the future. I had acidently introducted some overrides to the prefab in unity. @Seanba pointed out to check for these which i had missed. Reverting these made everything go back to as suspected.
