### ISSUE TITLE
Physics Materials on Tilemap

### ISSUE THREAD

**Issue by DevoxDeveloping** [Seanba/SuperTiled2Unity#211]
Hi,

is there a way to add Physics Materials to the Tilemap?

**Comment by jonny64bit** [comment]
You could do this by adding a custom importer

Docs for this are here.

[https://supertiled2unity.readthedocs.io/en/latest/manual/extending-the-importer.html](https://supertiled2unity.readthedocs.io/en/latest/manual/extending-the-importer.html)

**Comment by DevoxDeveloping** [comment]
thx man, i've been stuck with this problem xD

**Comment by Seanba** [comment]
Hi there, @DevoxDeveloping. Jonny is right that that is the kind of thing you want to use custom importers for.

That might be a bit tricky for people who are not yet used to programming in Unity. Let me know if you're having issues and I should be able to walk you through it. I imagine a dozen or so lines of code is all you need.

**Comment by DevoxDeveloping** [comment]
Yeah that would be nice... I tried it for 2h but I don't get it working.

**Comment by Seanba** [comment]
@DevoxDeveloping probably the fastest way is to provide a working example.

See this github repository: https://github.com/Seanba/ST2U_CustomImporterPhysicsMaterial

See the `ST2UCustomImporter_PhysicsMaterial` class. This is set up to assign a physics material 2D asset to *every* imported collider that is not a trigger.

```
using UnityEngine;
using SuperTiled2Unity;
using SuperTiled2Unity.Editor;

// Use this attribute to have this custom importer automatically apply to every TMX asset in your project
[AutoCustomTmxImporter]
public class ST2UCustomImporter_PhysicsMaterial : CustomTmxImporter
{
    public override void TmxAssetImported(TmxAssetImportedArgs args)
    {
        // Steps:
        // 1) For all SuperColliderComponents in the imported Tiled map (a SuperMap)
        // 2) Get the sibling Collider2D component
        // 3) Assign the physics material

        foreach (var superCollider in args.ImportedSuperMap.gameObject.GetComponentsInChildren<SuperColliderComponent>())
        {
            // We generally don't want to use physics materials on triggers
            var collider2d = superCollider.GetComponent<Collider2D>();
            if (collider2d != null && collider2d.isTrigger == false)
            {
                collider2d.sharedMaterial = AssetDatabaseEx.LoadFirstAssetByFilter<PhysicsMaterial2D>("MyPhysicsMaterial2D");
            }
        }
    }
}
```

You will probably want to add a bit more logic to your importer. For example, you only want a physics material on specific layers. You may also want to choose from different physics materials based on name of the Tiled layer (or something like that).

(Note that only the "brick" tiles in this example are set up to have colliders on them.)

![image](https://user-images.githubusercontent.com/6980630/165215436-5fe1f076-b062-4763-852f-cfa6b14e19b8.png)

Let me know if you have any questions.

**Comment by DevoxDeveloping** [comment]
Thanks for your help, man! I really appreciate that. But there's one question I still have: How can you add Components to certain Objects? Maybe with "FindObjectOfType" ?

**Comment by DevoxDeveloping** [comment]
Already done, I just found out how to do it instant after I commented
