### ISSUE TITLE
Can't match normal texture because of non-unity atlas

### ISSUE THREAD

**Issue by rocifier** [Seanba/SuperTiled2Unity#212]
Hi, when SuperTiled2Unity imports a sprite atlas from Tiled, it regenerates the texture to 2048x2048 (in my case) with padding around the edges to power of 2. However I have a custom normals texture that I am using exactly as described in the docs project for adding normal mapping. But the normal map doesn't align to the generates diffuse atlas. How can I predict what size the importer will generate the internal texture atlas for diffuse at so that I can manually match it in my normal map? Or is there a way that I can import a normal map atlas which runs through the same algorithm and matches perfectly to the diffuse, as I'm worried the tiled might be laid out differently in the one generated from unity? I am using single texture files to create my tileset in Tiled. Thanks!

EDIT: Attached is a screenshot showing the generated diffuse atlas which I can't access in any properties, and the normal map atlas which I have manually created:

![image](https://user-images.githubusercontent.com/1772304/163694645-a92908ea-7cb5-4a65-884b-45debee6be46.png)

In the screenshot you can also see terrain_sand and terrain_sand normals. The normals file was manually matched up to terrain_sand including adding spacing of the sprites on the atlas. This worked, but I don't know why an internal atlas was not generated upon importing - the texture is not a power of 2. I have checked the import settings for both textures and they are the same.

**Comment by rocifier** [comment]
I've found a workaround for now, which is to untick "Use Sprite Atlas for Tiles" on the tmx asset in Unity.

**Comment by Seanba** [comment]
Hi there, @rocifier. Disabling the sprite atlas is exactly what you want to do in a scenario like this.

However! Depending on your tilesheets you may end up with seams in your maps. That was a common issue with my first Tiled plugin (Tiled2Unity, before it was *Super*Tiled2Unity) and is the reason why ST2U defaults to a padded sprite atlas now.

I talk about these seams [in the old documentation here](https://tiled2unity.readthedocs.io/en/latest/fixing-seams/). If you get these kinds of seams you should go with the "Pad Your Tiles" solution outlined there.

Thanks and good luck with your game.

**Comment by rocifier** [comment]
Thanks @Seanba I'll use the option and I'm now padding tiles using imagemagik in my workflow as you described. Instead of inflating the pixels into the border area, keeping the border 100% transparent works.
