### ISSUE TITLE
Prefab replacement and custom importers - prefabs missing

### ISSUE THREAD

**Issue by jonny64bit** [Seanba/SuperTiled2Unity#215]
If you're loading your unity project from source control for the first time, the Library folder should be missing. From what I understand, the Library folder is always regenerated. 

If you are using prefab replacement feature, it won't be able to find the prefabs in the asset database even though it will load the ST2U settings correctly.

Similarly, in a custom importer it also can't access prefabs in the asset database.

You can test this issue by setting up prefab replacement or customer importer. Closing unity, delete the Library folder and load up the project.

I think i have a fix for this which is to push ST2U down the order in which Unity runs customer imports. See #214 for suggested fix.

**Comment by jonny64bit** [comment]
This is bug seems to pop-up when someone does a cloud/ci build. See #223 for example of this.

**Comment by seanb-22ct** [comment]
This is so odd but if fixes cloud builds then so be it. I'll find some time this weekend to update ST2U with this fix. Thanks.

**Comment by hoonsubin** [comment]
Just wanted to say thanks! This solved a big issue.
