### ISSUE TITLE
Unity Cloud Build doesn't replace tilemap objects with prefabs

### ISSUE THREAD

**Issue by ramchale** [Seanba/SuperTiled2Unity#223]
Locally the tilemap objects are replaced with the prefabs configured, having initially clicked the Reimport Assets button, but with remote builds I don't know how (or if it's possible) to trigger this

**Comment by jonny64bit** [comment]
@ramchale I don't have access to the cloud builds, but I suspect this is related to the issue I reported in #215 

I've already found a fix for that issue, which I ran into doing GameCI builds. I would suggest try implementing these changes in your local ST2U and see if it fixes it. https://github.com/Seanba/SuperTiled2Unity/pull/216/files

**Comment by ramchale** [comment]
After updating SuperTiled2Unity, applying the change, and running a clean build, that seems to have done the trick. Thanks!

**Comment by jonny64bit** [comment]
Glad it working!
