### ISSUE TITLE
Imported sprites / textures have no "Read/Write" rights

### ISSUE THREAD

**Issue by Ryxmedia** [Seanba/SuperTiled2Unity#237]
I'm trying to add a dynamic shadow caster in Unity to the sprites, but that is not possible, because they need to be able to access the initial sprite source by having the read/write rights.

As the imported sprites / textures have no option to select the "Read/Write" option like manually added sprites, you run into errors if you try to access them via a script:

Options for manually imported sprites:
![image](https://user-images.githubusercontent.com/9654470/229166932-40b853cb-17a0-4c3a-b380-638d3105cadc.png)

Options for sprites / atlas imported via ST2U:
![image](https://user-images.githubusercontent.com/9654470/229166970-e4807dd0-e52f-413a-9914-6babcefcb7a4.png)

If you try to access the sprites via a script to for example cast a shadow, the following error is thrown:

`UnityException: Texture 'Atlas_housing_objects_1' is not readable, the texture memory can not be accessed from scripts. You can make the texture readable in the Texture Import Settings.`

------------------------

I asked in Discord and searched for an option to give the correct rights for the sprites / textures, but couldn't find anything.

Anyone got an idea how to make to make it work?

**Comment by Ryxmedia** [comment]
No one got an idea? :(

**Comment by seanb-22ct** [comment]
Hi there, @Ryxmedia. My apologies for not getting back sooner. I've been crazy busy lately.

The atlas texture is a sub-asset of a custom importer and Unity doesn't give me the ability to enable write access on it.

However, if you disable `Use Sprite Atlas for Tiles` for your `housing objects` tileset then ST2U will use the "source" textures for the tiles and as long as your source textures have read/write enabled then you should be able to achieve what you want.

Keep in mind that you may see some seams when not using a sprite atlas. If that's the case then this link (from the older non-super Tiled2Unity) may help: https://tiled2unity.readthedocs.io/en/latest/fixing-seams/
