### ISSUE TITLE
Stack track is in the console output

### ISSUE THREAD

**Issue by squaremezzmer** [Seanba/SuperTiled2Unity#238]
```
There were errors importing xxxxxxxx.tmx
``` 
```
SuperTiled2Unity version: 1.10.7, Unity version: 2020.3.30f1
Unknown error encountered. Please report as bug. Stack track is in the console output.
Object reference not set to an instance of an object
```
This bug has occurred recently. Not sure how to reproduce.

My Visual Studio errorlist shows 121 errors concerning SuperTiled2Unity

**Comment by seanb-22ct** [comment]
Thanks for the report. The console output should have the essential data to see what's broken. Can you copy and paste that here?

**Comment by squaremezzmer** [comment]
You should also be aware of the Unity console readout. Apologies for not mentioning this earlier!

[Unity problems importing SuperTiled2Unity Errors in Unity.txt](https://github.com/Seanba/SuperTiled2Unity/files/11140723/Unity.problems.importing.SuperTiled2Unity.Errors.in.Unity.txt)

**Comment by seanb-22ct** [comment]
It looks like at least one of the errors is due to a missing component one on your game objects you are using as a `Prefab Replacement`. I can project against that with a bug fix.

But it also looks like your project or ST2U import is busted pretty badly. Do you happen to have your Unity project up on git somewhere or can you share it with me in some other way?

**Comment by squaremezzmer** [comment]
Yes ST2U is busted pretty badly. It began to give warnings that I'd named a ST2U Class (object) the same name as my own class, for example Torchlight and Torchlight class, I didn't think that would have been a problem. I have noticed of late prefabs are spawned from the Tilemap via ST2U import as around 3 recursive basically empty GameObject childs until the actual prefab. I hope this helps you find an answer.

I'm afraid I'm not able to send you my project because I don't want it anywhere but in my devices. Sorry

I can answer any more questions you may have about this issue.

**Comment by squaremezzmer** [comment]
The bug fix sounds good enough.
As I haven't received any questions and the stability part of the issue remains unknown, I'll happily close this issue as can't reproduce, etc.
