### ISSUE TITLE
Unity2018.3 Added Isometric Tilemap support for 2D Tilemap

### ISSUE THREAD

**Issue by jixiang111** [Seanba/SuperTiled2Unity#25]
Unity2018.3 Added Isometric Tilemap support for 2D Tilemap, Consider change the way to create the Tiled Isometric Map in new unity?

**Comment by Seanba** [comment]
This was addressed with version 1.2.3 of SuperTiled2Unity. Thanks again. @jixiang111.

**Comment by jixiang111** [comment]
Nice,Thank you for this update
