### ISSUE TITLE
ST2U needs an update for coming unity releases. (some things are obsolete in 2022 and of course 2023)

### ISSUE THREAD

**Issue by c0d3r9** [Seanba/SuperTiled2Unity#250]
A few month ago i just find a few warnings...but now i think its time to update it.
Does no one use unity >= 2022?
For a working and here and there updated version for 2023 i would pay a few bucks.
I wouldn´t start with another unity version because i wouldn´t make a step backwards.
Here are the warnings from today with unity 2023.2.0b4

Assets\SuperTiled2Unity\Examples\Overhead\Sprites\MegaDad\OverheadMegaDadController.cs(48,27): warning CS0618: 'Object.FindObjectsOfType<T>()' is obsolete: 'Object.FindObjectsOfType has been deprecated. Use Object.FindObjectsByType instead which lets you decide whether you need the results sorted or not.  FindObjectsOfType sorts the results by InstanceID but if you do not need this using FindObjectSortMode.None is considerably faster.'

Assets\SuperTiled2Unity\Scripts\Editor\Importers\TiledAssetImporterEditor.cs(38,33): warning CS0672: Member 'TiledAssetImporterEditor<T>.ResetValues()' overrides obsolete member 'AssetImporterEditor.ResetValues()'. Add the Obsolete attribute to 'TiledAssetImporterEditor<T>.ResetValues()'.

Assets\SuperTiled2Unity\Scripts\Editor\Importers\TmxAssetImporterEditor.cs(65,33): warning CS0672: Member 'TmxAssetImporterEditor.ResetValues()' overrides obsolete member 'AssetImporterEditor.ResetValues()'. Add the Obsolete attribute to 'TmxAssetImporterEditor.ResetValues()'.

Assets\SuperTiled2Unity\Scripts\Editor\Importers\TsxAssetImporterEditor.cs(67,33): warning CS0672: Member 'TsxAssetImporterEditor.ResetValues()' overrides obsolete member 'AssetImporterEditor.ResetValues()'. Add the Obsolete attribute to 'TsxAssetImporterEditor.ResetValues()'.

Assets\SuperTiled2Unity\Scripts\Editor\Collision\CollisionBuilder.cs(109,25): warning CS0618: 'Collider2D.usedByComposite' is obsolete: 'usedByComposite has been deprecated. Use Collider2D.compositeOperation instead'

Assets\SuperTiled2Unity\Scripts\Editor\Extensions\CompositeCollider2DExtensions.cs(30,21): warning CS0618: 'Collider2D.usedByComposite' is obsolete: 'usedByComposite has been deprecated. Use Collider2D.compositeOperation instead'

Assets\SuperTiled2Unity\Scripts\Editor\Extensions\CompositeCollider2DExtensions.cs(89,21): warning CS0618: 'Collider2D.usedByComposite' is obsolete: 'usedByComposite has been deprecated. Use Collider2D.compositeOperation instead'

Assets\SuperTiled2Unity\Scripts\Editor\Importers\TiledAssetImporterEditor.cs(40,13): warning CS0618: 'AssetImporterEditor.ResetValues()' is obsolete: 'UnityUpgradeable () -> DiscardChanges'

Assets\SuperTiled2Unity\Scripts\Editor\Importers\TmxAssetImporterEditor.cs(67,13): warning CS0618: 'AssetImporterEditor.ResetValues()' is obsolete: 'UnityUpgradeable () -> DiscardChanges'

Assets\SuperTiled2Unity\Scripts\Editor\Importers\TsxAssetImporterEditor.cs(69,13): warning CS0618: 'AssetImporterEditor.ResetValues()' is obsolete: 'UnityUpgradeable () -> DiscardChanges'

Assets\SuperTiled2Unity\Scripts\Editor\Importers\SuperImporterEditor.cs(132,29): warning CS0618: 'AssetImporterEditor.ApplyAndImport()' is obsolete: 'UnityUpgradeable () -> SaveChanges'

Assets\SuperTiled2Unity\Scripts\Editor\Math\PolygonUtils.cs(39,21): warning CS0618: 'Collider2D.usedByComposite' is obsolete: 'usedByComposite has been deprecated. Use Collider2D.compositeOperation instead'

Assets\SuperTiled2Unity\Scripts\Editor\Importers\SuperImporterEditor.cs(267,21): warning CS0618: 'AssetImporterEditor.ApplyAndImport()' is obsolete: 'UnityUpgradeable () -> SaveChanges'

Calls to "AssetDatabase.CreateAsset" are restricted during asset importing. AssetDatabase.CreateAsset() was called as part of running an import. Please make sure this function is not called from ScriptedImporters or PostProcessors, as it is a source of non-determinism and will be disallowed in a forthcoming release.
UnityEditor.AssetDatabase:CreateAsset (UnityEngine.Object,string)
SuperTiled2Unity.Editor.SuperTiled2Unity_Config:CreateDefaultSettings () (at Assets/SuperTiled2Unity/Scripts/Editor/Config/SuperTiled2Unity_Config.cs:22)
SuperTiled2Unity.Editor.ST2USettings:GetOrCreateST2USettings () (at Assets/SuperTiled2Unity/Scripts/Editor/Settings/ST2USettings.cs:109)
SuperTiled2Unity.Editor.TiledAssetImporter:WrapImportContext (UnityEditor.AssetImporters.AssetImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs:179)
SuperTiled2Unity.Editor.TiledAssetImporter:InternalOnImportAsset () (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs:124)
SuperTiled2Unity.Editor.TsxAssetImporter:InternalOnImportAsset () (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TsxAssetImporter.cs:33)
SuperTiled2Unity.Editor.SuperImporter:OnImportAsset (UnityEditor.AssetImporters.AssetImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/SuperImporter.cs:78)
UnityEditor.AssetImporters.ScriptedImporter:GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext)

Calls to "AssetDatabase.SaveAssets" are restricted during asset importing. 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
SuperTiled2Unity.Editor.SuperTiled2Unity_Config:CreateDefaultSettings () (at Assets/SuperTiled2Unity/Scripts/Editor/Config/SuperTiled2Unity_Config.cs:23)
SuperTiled2Unity.Editor.ST2USettings:GetOrCreateST2USettings () (at Assets/SuperTiled2Unity/Scripts/Editor/Settings/ST2USettings.cs:109)
SuperTiled2Unity.Editor.TiledAssetImporter:WrapImportContext (UnityEditor.AssetImporters.AssetImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs:179)
SuperTiled2Unity.Editor.TiledAssetImporter:InternalOnImportAsset () (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TiledAssetImporter.cs:124)
SuperTiled2Unity.Editor.TsxAssetImporter:InternalOnImportAsset () (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TsxAssetImporter.cs:33)
SuperTiled2Unity.Editor.SuperImporter:OnImportAsset (UnityEditor.AssetImporters.AssetImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/SuperImporter.cs:78)
UnityEditor.AssetImporters.ScriptedImporter:GenerateAssetData (UnityEditor.AssetImporters.AssetImportContext)

**Comment by Seanba** [comment]
Hi there, @c0d3r9. I'm using `2022.2` for my upcoming re-release of ST2U as a UPM package and will be retiring deployment as a `*.unitypackage` file. All 2022 warnings are fixed in that version. I have not yet looked at 2023 but I know a good number (perhaps all) of the warnings you reported above are already addressed.

To install this version of ST2U
- delete the `Assets/SuperTiled2Unity` folder in your project
- download [the zipped package](https://github.com/Seanba/SuperTiled2Unity/blob/package_refactor/deploy/super-tiled2unity.v2.0.0.zip)
- put zip file in your `[ProjectRoot]/Packages` folder

**Comment by c0d3r9** [comment]
Great Scott....thanks alot.Put in the Packages folder without any warnings in 2023.2.(last night i solved all warnings myself and so i can compare if all was right what i changed)And in future you offer ST2U as UPM package?Great...for that all you got a paypal beer ;)

**Comment by hoonsubin** [comment]
> Hi there, @c0d3r9. I'm using `2022.2` for my upcoming re-release of ST2U as a UPM package and will be retiring deployment as a `*.unitypackage` file. All 2022 warnings are fixed in that version. I have not yet looked at 2023 but I know a good number (perhaps all) of the warnings you reported above are already addressed.
> 
> To install this version of ST2U
> 
>     * delete the `Assets/SuperTiled2Unity` folder in your project
> 
>     * download [the zipped package](https://github.com/Seanba/SuperTiled2Unity/blob/package_refactor/deploy/super-tiled2unity.v2.0.0.zip)
> 
>     * put zip file in your `[ProjectRoot]/Packages` folder

@Seanba is there a public guide for installing the package? I tried your method, but I got an assembly reference error from my custom importer script.

**Comment by seanb-22ct** [comment]
Hi there, @hoonsubin. Which version of Unity are you using?

**Comment by hoonsubin** [comment]
> Hi there, @hoonsubin. Which version of Unity are you using?

`2021.3.12f1`

**Comment by seanb-22ct** [comment]
That _should_ be fine but now I'm seeing the same error with that version. I'll work on that later today. Thanks for letting me know.

**Comment by c0d3r9** [comment]
DiscardChanges comes first in 2022.2
I look at the docs.
It should be possible to implement code depending on the unity version.
In one script.
No errors here ein 2023.2

**Comment by seanb-22ct** [comment]
Thanks, @c0d3r9. I was off on what versions introduced `DiscardChanges`. I'll have a fix for this later today.

**Comment by c0d3r9** [comment]
@seanb-22ct i´m sure you know it.

**Comment by Seanba** [comment]
Thanks, @c0d3r9, it never hurts to check.

I've submitted the fixes with version 2.0.1. [You can find it here](https://github.com/Seanba/SuperTiled2Unity/blob/master/deploy/super-tiled2unity.v2.0.1.zip).

**Comment by c0d3r9** [comment]
You should fix 
super-tiled2unity.v2.0.1\Editor\Collision\CollisionBuilder.cs   -> polyCollider.usedByComposite = true;

**Comment by Seanba** [comment]
@c0d3r9 Version 2.1.0 has those compile warnings fixed for 2022.2 and later. Thanks for making me aware of this.

https://seanba.itch.io/supertiled2unity
