### ISSUE TITLE
Improvement idea: Add default Tilemap rendere material to ST2U Settings

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#26]
Exemplary use case:

I'm using a directional light that changes it's color over time as "sun". However, the _Sprites-Default_ material, that gets added to all the _Tilemap Render_ components is not influenced by light sources. That's why I need to assign my own material.

I do this by writing a custom importer which looks something like this:

```csharp
public class ExampleImporter : CustomTmxImporter
{

  public override void TmxAssetImported(TmxAssetImportedArgs args)
  {
    ReplaceSpriteDefaultMaterialWithDiffuseDepthInstanced(map);
  }

  private static void ReplaceSpriteDefaultMaterialWithDiffuseDepthInstanced(SuperMap map)
  {
    var spriteRenderers = map.GetComponentsInChildren<TilemapRenderer>();

    //path fetching a little simplified so the example stays easy to understand
    var materialPath = Path.Combine("Assets\\Main\Resources\\SuperTiled2Unity\\Materials\\StandardTilemapRendererMaterial.mat", "StandardTilemapRendererMaterial.mat");
    var material = AssetDatabase.LoadAssetAtPath<Material>(materialPath);

    foreach (var spriteRenderer in spriteRenderers)
    {
      spriteRenderer.material = material;
    }
  }
}
```

Granted, this works but it would be way more convenient if one would be able to set a default material in _ST2U Settings_ that then would be applied to all Tilemap Renderer components upon import.
Especially, I could then move the material freely around in the hierarchy, rename it, etc.. As things stand now, the path is hard coded and whenever I move the material around or rename it, I will have to remember to update my code.

In my actual code I, at least have one file where I get all the paths from and it would probably be doable to just use the name and search all the assets or whatever. But it would be so much easier if we could just drag and drop the default material in the settings.

Thanks a lot for your consideration!

**Comment by Seanba** [comment]
This was added with [version 1.1.6 of SuperTiled2Unity](https://seanba.itch.io/supertiled2unity/devlog/61153/supertiled2unity-version-116). Thanks for the good suggestion.

![image](https://user-images.githubusercontent.com/6980630/50380242-08a47e80-0627-11e9-91aa-c7f3101f0625.png)

**Comment by SharlatanY** [comment]
Thank you for the quick implementation! :)
