### ISSUE TITLE
FindXXXBySignature problem with Enums

### ISSUE THREAD

**Issue by willyx78** [Seanba/SuperTiled2Unity#260]
Hi, i'm trying to use int Enums in Tiled for custom properties for Prefab Replacement and they don't work. 
The problem is that Enum are int32 in Tiled, but in Unity they are...well. enums (type like MyCustomEnumName+Value) and 
FindPropertyBySignature FindMethodBySignature FindFieldBySignature cannot match the types.

U can fix FindFieldBySignature adding an 
 || (info.FieldType.IsEnum && valueType== Type.GetType("System.Int32")))
To the check of valueType:

private static FieldInfo FindFieldBySignature(Component component, string name, Type valueType)
        {
            return component.GetType().GetFields(BindingFlags.Instance | BindingFlags.Public).Where(
                info =>
                !info.IsInitOnly &&
                info.Name == name &&
                (info.FieldType == valueType ||
                (info.FieldType.IsEnum && valueType== Type.GetType("System.Int32")))
                ).FirstOrDefault();
        }

Same thing with other 2 Find

**Comment by Seanba** [comment]
Thank-you for the tip, @willyx78. I've added [this ST2U version 2.2.4](https://seanba.itch.io/supertiled2unity/devlog/847632/super-tiled2unity-224).
