### ISSUE TITLE
Old file format detected. You must save this file with a newer verion of Tiled.

### ISSUE THREAD

**Issue by forrejam** [Seanba/SuperTiled2Unity#264]
SuperTiled2Unity version: 2.1.1, Unity version: 2022.3.5f1
Old file format detected. You must save this file with a newer verion of Tiled.

Got the above error on a TSX file with the latest version of Unity and Tiled, any ideas?

**Comment by seanb-22ct** [comment]
Hi there, @forrejam. That should be an easy fix. You need to open your TSX file in Tiled and resave it.
(You need to be using a recent version of Tiled though. From the last year or two.)

**Comment by forrejam** [comment]
Thanks for getting back so quickly! Issue is I am using the latest version 1.10.2 of tiled as is indicted in the error message.

**Comment by forrejam** [comment]
Sorry about that, what had happened was I download an old version of a TSX file and needed to recreate it in the latest version of Tiled

**Comment by seanb-22ct** [comment]
No worries. Good luck with your game.
