### ISSUE TITLE
high quality tiles causing PPU mismatch error

### ISSUE THREAD

**Issue by nlfmt** [Seanba/SuperTiled2Unity#272]
When trying to import a map using a tile size of 400px, the importer says there were errors found in the tilemap, and in the tilemap it says "Our Pixels Per Unit setting is '400' (or '100') Texture.png Pixels Per Unit setting is '247.5'", although that texture is set to the correct PPU of 400 (or 100, tried both).
When changing the PPU for that png to another value, the PPU thats being read by SuperTiled2Unity changes too

When i downscale the texture im using for the tileset to a 32px tile size it suddenly works, 256px doesnt work either tho.
Am i missing something that has to be setup, or is my tileset image size too big (5600x6000), or is this just not supported?

Any help would be greatly appreciated, as well as pointers to where i can read more about my case because there doesnt seem to be any documentation about tile size and PPU

**Comment by Seanba** [comment]
Hi there, @nlfmt. Is it possible to get a copy of your project? That's the easiest way for me to debug issues like this.

One thing to look out for is maybe your texture importer settings on the 5600x6000 texture might not have a max size that is big enough.

![image](https://github.com/Seanba/SuperTiled2Unity/assets/6980630/53deabf3-4fcb-4396-9dcd-069510cfd6ab)

**Comment by nlfmt** [comment]
Increasing the Max Size actually fixed it, thanks a ton! Dont know how i didnt see that setting...
Had to reimport a bunch of times due to a "missing tiles" error after the max size change but then it was fine.

Going forward with this, would it be smarter for me to provide the tiles as split up single tile files of 400x400 or multiple tilesets of size 2000x2000 instead? Im guessing my huge texture isnt really performant nor future-proof.

**Comment by Seanba** [comment]
Going forward with this, would it be smarter for me to provide the tiles as split up single tile files of 400x400 or multiple tilesets of size 2000x2000 instead? Im guessing my huge texture isnt really performant nor future-proof.

It's going to matter of platform but I doubt performance will matter much, especially if you decide to put your textures into a sprite atlas (which is probably a good idea). However, I find development *a lot* easier using separate textures for each tile. Putting all your sprites or tiles into one texture is more of a holdover from the olden days.
