### ISSUE TITLE
Failed to import tmx: unknown error under macOS (Apple Silicon)

### ISSUE THREAD

**Issue by PythonLimited** [Seanba/SuperTiled2Unity#273]
Hi,
I recently wanted to try out supertiled2unity on my Macbook Pro (M3Pro - latest os update).
However every time I drag the supertiled2unity folder into my unity project, it loads some scripts and compiles something in the background, but then spits out a bunch of errors in the log.
I am also unable to load any of the sample tmx files included in the project.

I tried this on a windows machine and I don't have any problems there.

What I noticed from the logs is that it formats them, and looking at the source, it is maybe an issue with how macOS handles file paths? Also it just plain fails to recognize that the path that's about to be sanitized, already includes my home directory, thus prefixing it anyway.
I did try some stuff out so that the file paths would be correct (upper-case and correctly sanitized), but then I would still get errors about missing files in the editor.

Below is the console output of just loading the supertiled2unity project, as well as two screenshots of the error messages in the inspector.

`Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/testoverhead.tmx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/testoverhead.tmx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:240)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:AddSpritesFromTiledFiles () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:68)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:OnPreprocessTexture () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:42)
UnityEditor.AssetPostprocessingInternal:PreprocessTexture (string,UnityEditor.AssetImporters.AssetImportContext) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:839)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/overhead-objects.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/overhead-objects.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:247)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:AddSpritesFromTiledFiles () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:68)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:OnPreprocessTexture () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:42)
UnityEditor.AssetPostprocessingInternal:PreprocessTexture (string,UnityEditor.AssetImporters.AssetImportContext) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:839)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/scraps.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/scraps.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:247)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:AddSpritesFromTiledFiles () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:68)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:OnPreprocessTexture () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:42)
UnityEditor.AssetPostprocessingInternal:PreprocessTexture (string,UnityEditor.AssetImporters.AssetImportContext) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:839)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/tiles.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/tiles.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:247)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:AddSpritesFromTiledFiles () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:68)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:OnPreprocessTexture () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:42)
UnityEditor.AssetPostprocessingInternal:PreprocessTexture (string,UnityEditor.AssetImporters.AssetImportContext) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:839)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/water.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/water.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:247)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:AddSpritesFromTiledFiles () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:68)
SuperTiled2Unity.Editor.SuperTexturePostprocessor:OnPreprocessTexture () (at Assets/super-tiled2unity.v2.2.0/Editor/Postprocessors/SuperTexturePostprocessor.cs:42)
UnityEditor.AssetPostprocessingInternal:PreprocessTexture (string,UnityEditor.AssetImporters.AssetImportContext) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:839)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/overhead-objects.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/overhead-objects.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:198)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:313)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/scraps.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/scraps.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:198)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:313)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/tiles.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/tiles.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:198)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:313)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/water.tsx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/zoria tileset/water.tsx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:198)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:313)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/testoverhead.tmx': Could not find a part of the path "/Users/mcsbuild/Test/users/mcsbuild/test/assets/super-tiled2unity.v2.2.0/samples/overhead/maps/testoverhead.tmx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:198)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:313)
UnityEditor.AssetPostprocessingInternal:PostprocessAl
lAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

`

<img width="1511" alt="Screenshot 2024-06-17 at 3 22 55 PM" src="https://github.com/Seanba/SuperTiled2Unity/assets/16454674/b0f38914-3cf6-4353-ba66-a0e908c7380e">
<img width="1512" alt="Screenshot 2024-06-17 at 3 23 07 PM" src="https://github.com/Seanba/SuperTiled2Unity/assets/16454674/cdd69606-81ae-4a3f-893a-fceb1104a7b7">

**Comment by PythonLimited** [comment]
I now also tried it with the intel unity flavor - however with the same result.

**Comment by PythonLimited** [comment]
Ok I just got it semi-working.
Simple tile sets (like the one you include) do work, but anything more complex doesn't.
The main issue from what I found is that by sanitizing the path and removing the '/' at the beginning of the path, the check if path.StartsWith(Application.dataPath does not return true anymore -> therefore signaling to supertiled2unity that an import error has occurred.
Once I removed that it imported the actual assets fine, but when I wanted to import a sample assetpack it now still complained about missing assets. By using the button "Add sprites..." it does work, but I'd now have to do that for every file which is annoying.

But perhaps you can give some insight why this is happening in the first place, as on Linux this should happen too (if dotnet returns the string starting at home for directory listings idk)

**Comment by PythonLimited** [comment]
<img width="1512" alt="Screenshot 2024-06-17 at 5 29 31 PM" src="https://github.com/Seanba/SuperTiled2Unity/assets/16454674/63b1e150-d127-4246-836c-0bb6bd853099">

**Comment by seanb-22ct** [comment]
Hi there, @PythonLimited. It looks like you put the ST2U package into your `Assets` folder but it is meant to be imported into your project through the Unity Package Manager. Can you unzip the ST2U file and put that folder into your `Packages` directory and let me know if that fixes things up for you?

Put another way, you have ST2U here: `YourGame/Assets/super-tiled2unity.v2.2.0`
But it should go here: `YourGame/Packages/super-tiled2unity.v2.2.0`

**Comment by PythonLimited** [comment]
> Hi there, @PythonLimited. It looks like you put the ST2U package into your `Assets` folder but it is meant to be imported into your project through the Unity Package Manager. Can you unzip the ST2U file and put that folder into your `Packages` directory and let me know if that fixes things up for you?
> 
> Put another way, you have ST2U here: `YourGame/Assets/super-tiled2unity.v2.2.0`
> But it should go here: `YourGame/Packages/super-tiled2unity.v2.2.0`
> 

Oh, my bad.
It worked just fine that way in my windows based machine, but I'll try that out ASAP.
Thanks!

**Comment by PythonLimited** [comment]
> Hi there, @PythonLimited. It looks like you put the ST2U package into your `Assets` folder but it is meant to be imported into your project through the Unity Package Manager. Can you unzip the ST2U file and put that folder into your `Packages` directory and let me know if that fixes things up for you?
> 
> Put another way, you have ST2U here: `YourGame/Assets/super-tiled2unity.v2.2.0` But it should go here: `YourGame/Packages/super-tiled2unity.v2.2.0`

alright, I put a fresh version in the packages folder now, however I'm getting the same error messages as in the beginning with the only exception being the path now (./packages instead of assets/supertiled3unity)
I then tried the one with my edits and it loads the simple example, but not more complex assetpacks.

Anyhow here are the logs (I put in some warnings in too that I skipped before since there are like 1k+ of them in the log):


```Importer(TextureImporter) generated inconsistent result for asset(guid:b36397d925a854b2b8a95941141533ee) "Assets/art/erw-ar/Tilesets/Transparency version/waterfall-transparency.png"
UnityEditor.AssetDatabase:ImportAsset (string)
SuperTiled2Unity.Editor.SpriteRectsManager:CheckForTextureReimports (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:189)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:205)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:311)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool)

Importer(TextureImporter) generated inconsistent result for asset(guid:34abc9825896e4c2e8c1c14d2afd6761) "Assets/art/erw-ar/Tilesets/Transparency version/wall-2 - 3 tiles tall.png"
UnityEditor.AssetDatabase:ImportAsset (string)
SuperTiled2Unity.Editor.SpriteRectsManager:CheckForTextureReimports (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:189)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:205)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:311)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool)

Importer(TextureImporter) generated inconsistent result for asset(guid:e547a8d773e57419f9462ea248d89122) "Assets/art/erw-ar/Props/Atlas-Props.png"
UnityEditor.AssetDatabase:ImportAsset (string)
SuperTiled2Unity.Editor.SpriteRectsManager:CheckForTextureReimports (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:189)
SuperTiled2Unity.Editor.SpriteRectsManager:ImportTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:205)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:311)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/ancient ruins example map.tmx': Could not find a part of the path "/Users/mcsbuild/My project/users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/ancient ruins example map.tmx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:240)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:330)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/sample scene.tmx': Could not find a part of the path "/Users/mcsbuild/My project/users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/sample scene.tmx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:240)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:330)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/rules/wall-1-rule0-erases all generated tiles and resets them to their initial state.tmx': Could not find a part of the path "/Users/mcsbuild/My project/users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/rules/wall-1-rule0-erases all generated tiles and resets them to their initial state.tmx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:240)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:330)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)

Looking for tilesets. Unknown error processing Tiled file 'users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/rules/wall-1-rule1-places all tiles.tmx': Could not find a part of the path "/Users/mcsbuild/My project/users/mcsbuild/my project/users/mcsbuild/my project/assets/art/erw-ar/tiledmap editor/rules/wall-1-rule1-places all tiles.tmx".
UnityEngine.Debug:Log (object)
SuperTiled2Unity.Editor.SpriteRectsManager:ProcessTiledFile (string) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:65)
SuperTiled2Unity.Editor.SpriteRectsManager:CreateInstance () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:240)
SuperTiled2Unity.Editor.SpriteRectsManager:.cctor () (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:21)
SuperTiled2Unity.Editor.SpriteRectsManager/InternalAssetPostprocessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at ./Packages/super-tiled2unity.v2.2.0/Editor/Sprite/SpriteRectsManager.cs:330)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool) (at /Users/bokken/build/output/unity/unity/Editor/Mono/AssetPostprocessor.cs:403)
```

**Comment by mminer** [comment]
I also ran into this problem on macOS. `StringExtensions.SanitizePath` looks to be the culprit — it strips the leading `/` from path names, so in places like this: https://github.com/Seanba/SuperTiled2Unity/blob/3eb57d1c1588c1f667a76eee68f737921d29cf08/SuperTiled2Unity/Packages/com.seanba.super-tiled2unity/Editor/Sprite/SpriteRectsManager.cs#L38-L46

It passes what looks like a relative path, e.g. _users/mminer/project/assets/tileset.tsx_.

A quick fix is to remove this line: https://github.com/Seanba/SuperTiled2Unity/blob/3eb57d1c1588c1f667a76eee68f737921d29cf08/SuperTiled2Unity/Packages/com.seanba.super-tiled2unity/Editor/Extensions/StringExtensions.cs#L50-L51

Though I assume the logic to remove repeated slashes and the slash at the end has a good reason to be there.

**Comment by Seanba** [comment]
Hi there, @mminer. Thanks for pointing that out. That has led me to what I think the fix needs to be.
Unfortunately my plans to obtain to a MacBook for proper testing hasn't worked out but I'll find time to address this soon.

**Comment by Seanba** [comment]
Hi there, @PythonLimited and @mminer. Can you try version 2.2.1 and see if that fixes you up? Unfortunately I had to fix this without testing on proper Mac (or Linux) hardware but I think I addressed the problem.

Zip is here: [super-tiled2unity.v2.2.1.zip](https://github.com/Seanba/SuperTiled2Unity/blob/master/deploy/super-tiled2unity.v2.2.1.zip )

**Comment by mminer** [comment]
v2.2.1 works great for me. Thanks for the fix!

**Comment by PythonLimited** [comment]
> Hi there, @PythonLimited and @mminer. Can you try version 2.2.1 and see if that fixes you up? Unfortunately I had to fix this without testing on proper Mac (or Linux) hardware but I think I addressed the problem.
> 
> Zip is here: [super-tiled2unity.v2.2.1.zip](https://github.com/Seanba/SuperTiled2Unity/blob/master/deploy/super-tiled2unity.v2.2.1.zip)


tried it out on my windows machine by accident - and im getting the same error weirdly enough - lots of weird purple madness on the maps...
![image](https://github.com/Seanba/SuperTiled2Unity/assets/16454674/d9d5df8b-263d-4918-912d-d22d3c35be9a)


this leads me to believe its an error with the tileset or so?
i can invite you to a repo with the tileset so you can have a look if you want - maybe its just something stupid from the tileset creator?

**Comment by PythonLimited** [comment]
btw when click on these "Add Sprites to <tileset>" buttons the map then displays correctly:
![image](https://github.com/Seanba/SuperTiled2Unity/assets/16454674/380e8f73-97c0-424d-9d0f-482087671dad)

**Comment by seanb-22ct** [comment]
Hi there, @PythonLimited. An invitation to your repo is fine. What I think is happening is indicated by the warning in your Console window. Your texture needs to be cut up into 2340 sprites which bogs Unity down. I currently have it limited so that only 2048 sprites are created per import, otherwise your import time could take hours.

(Sorry, that's a Unity thing. They have an O(n^2) algorithm in their code that splits up textures into sprites.)

However, if you hit the "Add Sprites" button then up to another 2048 sprites are added to your texture (if that makes sense). So, there is a way to move past this, which you seem to have figured out.

If possible it would be best to use textures with a smaller number of tiles/sprites in it. And like I said before I'm happy to look at your repo.

**Comment by PythonLimited** [comment]
> Hi there, @PythonLimited. An invitation to your repo is fine. What I think is happening is indicated by the warning in your Console window. Your texture needs to be cut up into 2340 sprites which bogs Unity down. I currently have it limited so that only 2048 sprites are created per import, otherwise your import time could take hours.
> 
> (Sorry, that's a Unity thing. They have an O(n^2) algorithm in their code that splits up textures into sprites.)
> 
> However, if you hit the "Add Sprites" button then up to another 2048 sprites are added to your texture (if that makes sense). So, there is a way to move past this, which you seem to have figured out.
> 
> If possible it would be best to use textures with a smaller number of tiles/sprites in it. And like I said before I'm happy to look at your repo.

sorry for the late reply, but yes upping the number indeed worked.
thanks!
