### ISSUE TITLE
Doesn't change Tag and Layer of children Game Object in Unity.

### ISSUE THREAD

**Issue by storyteller24** [Seanba/SuperTiled2Unity#277]
I have worked in Unity with SuperTiled 2.2.1
My project is a platformer Game.

I used properties unity:Tag and unity:Layer but looks like it doesn't change the children of the game object, which include collisions.
That affects my progress when my script use compare.Tag with Trigger of the colliders a lot.

I suggest you make all the component in Tiled's layer to the same value we set in the properties. It's better for all platformer game.

Hope you read this!
![Screenshot 2024-07-24 074821](https://github.com/user-attachments/assets/e9436b66-7e9c-4b5f-bb3f-882c20264992)
![Screenshot 2024-07-24 074847](https://github.com/user-attachments/assets/a45ce270-557a-4313-ab29-ef2f9ea2cfbc)
![Screenshot 2024-07-24 074902](https://github.com/user-attachments/assets/fdcbb42f-2212-42b5-b613-821378f083aa)

**Comment by Seanba** [comment]
Hi there, @storyteller24. My apologies for commenting on this so late. The `Layer` setting was meant to be passed on to the children but it doesn't like that is working for `Infinte` maps (the `Chunk` children are all set to `Default` layer). I'll try to look into a fix for that soon.

**Comment by Seanba** [comment]
Thanks for the report. This is fixed with [version 2.2.4 of ST2U](https://seanba.itch.io/supertiled2unity/devlog/847632/super-tiled2unity-224).

**Comment by smoketlt** [comment]
How about tags? Children not get layer tag.
