### ISSUE TITLE
Z scale is set to 0 on rotated/flipped tiles

### ISSUE THREAD

**Issue by firebellys** [Seanba/SuperTiled2Unity#28]
If I place a tile in Tiled and but flip it on the X axis, Tiled2Unity sets the Z scale to 0 for some reason. It changes the X scale to -1 as it should to show it flipped on the X axis, but for some reason the Z is also changed. It doesn't do this on normal tiles.

Two things I changed recently
- Changed the Default Material in the settings
- Updated to 1.1.6.
<img width="352" alt="screen shot 2018-12-28 at 10 23 11 pm" src="https://user-images.githubusercontent.com/577101/50527174-50c41500-0aef-11e9-99b1-6f5c2a252d22.png">

Tiles with Z of 0 are black.
<img width="224" alt="screen shot 2018-12-28 at 10 26 03 pm" src="https://user-images.githubusercontent.com/577101/50527210-97b20a80-0aef-11e9-9bd8-488f7b3a77b6.png">

**Comment by Seanba** [comment]
Hi there, @firebellys. That was a nice find. I've just [uploaded version 1.1.7 of SuperTiled2Unity](https://seanba.itch.io/supertiled2unity/devlog/61925/supertiled2unity-version-117) which contains the fix for this. Thanks for the bug report.
