### ISSUE TITLE
Texture assets not importing

### ISSUE THREAD

**Issue by Graver067966739** [Seanba/SuperTiled2Unity#30]
I may be out of my league here jumping into this but I'm unable to get the textures of my tiled map into unity. I keep getting errors on the tileset importers stating "Missing texture asset". The map loads fine in tiled and I've been able to import example maps into unity with textures intact. But specifically the maps I've tiled don't seem to work. Is there some sort of configuration issue I'm missing?

Also if there is an in depth tutorial or documentation I would be interested

**Comment by Seanba** [comment]
Hi there, @Graver067966739. That error means the textures being referenced by your tileset are not part of your Unity project. SuperTiled2Unity requires that all your files (maps, tilesets, textures) reside in Unity so that it can be found through the asset database.

**Comment by emperor-doel** [comment]
@Graver067966739 I am having the same issue.  I right click inside the supertiled2unity folder, import new asset and click on the .tmx and the corresponding .tsx files along with the textures referenced in the .tsx and I keep getting missing texture asset. Been spending a couple days trying to fix the issue now :(

Please help @Seanba :)

**Comment by emperor-doel** [comment]
@Seanba Done and done, hopefully you can find something :)

**Comment by Seanba** [comment]
@emperor-doel, I didn't receive an email from you with your Unity Package. If you responded to a Github-generated email that may be why. Can you send again? Thanks.

**Comment by Seanba** [comment]
Hi there. I've give this a couple more days to and then close, barring further feedback.

**In the meantime, here's something to double check**: When a texture (or other asset) is missing the error will give you the (relative) path to where Tiled expects that file to be found. So, make sure that a) your missing texture is indeed in your Unity project and b) That it is in the right location.

Another rule of thumb: Try opening your TMX file in Tiled. If the tilesets and texture paths are wrong then Tiled will also complain. If you resolve the problem there then it should also work in SuperTiled2Unity.

**Comment by emperor-doel** [comment]
Hey @Seanba, 

I don't know why my project never sent thru email :*( 

I did manage to fix the issue by moving all the assets into the SuperTiled2Unity Folder in my project while reimporting in Unity and opening up the tmx files in tiled until it was happy. Thank you for responding and being helpful :)

**Comment by Seanba** [comment]
Glad you got it fixed. Good luck with your game.
