### ISSUE TITLE
Improvement idea: Add option for default material for different layers

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#31]
Hey Sean!

I already love the default material addition for tilemaps you made. It's really useful!

I've got to work a bit more on my project and came across an advanced version of this feature that would be really handy in my project and I can imagine others might like it as well:

**It would be great if (in addition to a default material) we could define a list of layer names and a material that's assigned if a layer has a certain name in the editor.**
I imagine something like a dictionary where the layer name is the key and the material the value and for every layer, the importer looks up if a key with the current layer name exists and if so, assigns the value as the material. Since (as far as I can remember) Unity doesn't by default support serialized dictionaries, a workaround that wouldn't pose too much effort could be a list of a wrapper class, that wraps the layer name and material?

**Use case example**:
I have reflections in my game. For the reflections to work, certain elements have to have a certain material. E.g. water needs a specific material so it reflects and distorts everything that is on a certain layer. But of course, things like grass should not reflect or distort anything at all.

With this additional feature, I could draw all the water on a "Water" layer in Tiled and then configure the import settings in such a way that the default material is assigned to all layers, except when a layer is named "Water", in which case the special water material would be assigned.

Of course this would also be possible through custom importers but this way would be much more convenient, less error prone and probably a feature there's a need for by most projects that are a bit more ambiguous.

Thanks for all your hard work and for considering my suggestion!

All the best,

Sharlatan

**Comment by firebellys** [comment]
👍 upvote

**Comment by Seanba** [comment]
Hi there, @SharlatanY and @firebellys. SuperTiled2Unity 1.8.0 gives you the ability to match layer names (in Tiled) to materials you've defined (in Unity).
https://seanba.itch.io/supertiled2unity/devlog/106641/supertiled2unity-version-180

This is a forced example of how you can match layer names ...

![image](https://user-images.githubusercontent.com/6980630/67626772-f8949700-f815-11e9-9a5b-0a1b65327f27.png)

![image](https://user-images.githubusercontent.com/6980630/67626773-fd594b00-f815-11e9-9eaa-2a86a0f61247.png)

![image](https://user-images.githubusercontent.com/6980630/67626774-00ecd200-f816-11e9-89d8-84a68e01775f.png)

Thanks for the suggestion. Let me know if that works for you. :)

**Comment by SharlatanY** [comment]
@Seanba Thank you very much! This looks extremely helpful and I'll be happy to try it out next weekend!

**Comment by Seanba** [comment]
Hi there. I'm going through old issues I think are resolved and closing them out. If this is still an issue let me know. Thanks.
