### ISSUE TITLE
How to automatically create prefabs from Tiled objects?

### ISSUE THREAD

**Issue by asusralis** [Seanba/SuperTiled2Unity#33]
I can't find anything that touches on creating prefabs from the Tiled maps. If I had a Spikes unity prefab, how would I place spikes in Tiled, import it to Unity, and get my Spikes prefab to be automatically created from that tile?

**Comment by AberrantWolf** [comment]
I think you're meant to go at it from the other direction. That is, you have your spike tiles either tagged or on a "spikes" layer in Tiled, then your player would either check for the "spikes" layer or you could write a custom importer that attaches a "spike" MonoBehaviour to the tiles on import.

I guess you could also have an import script which uses tagged tiles from Tiled to instantiate a spikes prefab into  your map as well, but unless you need to replace the 2D tile visual with something else (e.g., you're using Tiled for the layout, but actually intend to replace all the 2D tiles with 3D objects).

**Comment by Seanba** [comment]
I apologize for not getting around to providing documentation yet but I have a github repository that provides an example of a custom importer replacing objects in a Tiled file with prefabs.

https://github.com/Seanba/SuperMovingPlatform

See `TrackCustomImporter.cs` and `MovingPlatformOnTrack.cs` in that example. If you load the `Assets/ExampleFiles/Scene.unity` scene you should be able to press play and see the instantiated platforms moving along the tracks.

**Comment by asusralis** [comment]
Thanks for an example. Does this mean you'd have to make an importer for every prefab type? That seems very cumbersome for even slightly more advanced projects. I was thinking, because SuperTiled2Unity knows about the object types from Tiled, you could just drag a prefab into the inspector and have it created for you - kind of like how [Super Tilemap Editor](https://assetstore.unity.com/packages/tools/level-design/super-tilemap-editor-56339) deals with prefabs.

**Comment by Seanba** [comment]
Hi @asusralis. I write one importer that takes care of all my needs but I'm a programmer by trade so perhaps I underestimate the work required there for others.

Your idea seems interesting though: Are you saying that an object type in Tiled is replaced wholesale by an instantiated prefab automatically? So, for each known object type the inspector has a field we can drag a prefab into? I can see that working.

**Comment by asusralis** [comment]
I also prefer to use programming, but I try to use the editor when applicable. 

I admittedly don't know too much about Tiled, but yes - that's what I was thinking. In Super Tilemap Editor, which is what I see as the alternative of this plugin, you can give a tile a prefab reference that would be instantiated whenever it's placed. I think the equivalent of that in Tiled would be a tile's Type in the tileset. In that tileset resources in Unity, you could have a GameObject field for that type. And whenever that tile would be placed, a prefab would be created. https://i.imgur.com/mcDGMug.png

I'm not sure about custom properties. You could use reflection, but I'm not sure you can override a tile's property once they're placed in a map? If not, you'd probably just set the data in the prefab once they've been created. 

Super Tilemap Editor also gives the option to not render the tile from the tilemap so, if you had have some special animation, you could just have a sprite renderer on the prefab. That's shown in the Super::Render property above. 

All of this is rather involved. I will definitely try the workflow of the example you show me, and what I've stated about are first impressions that might not be the best way to do this, but I thank you for hearing me nonetheless!

**Comment by Seanba** [comment]
@asusralis, I hope to have something for automatic prefab replacement of Tiled objects ready soon. As requested, you will be able to drag a prefab into an object type field. It will use reflection to set properties on the instantiated prefab from custom properties. Stay tuned.

**Comment by asusralis** [comment]
Very cool! Thanks a lot. I'm looking forward to using it.

**Comment by Seanba** [comment]
Hi there, @asusralis. I apologize for letting this issue linger, especially because I added Prefab Replacements as a feature months ago. :/

In case you're still interested, [this repo has a working example](https://github.com/Seanba/SuperPrefabReplacement) of and demonstrates how to use such prefab replacements. Thanks for your suggestion, btw. This is proving to be a useful feature of SuperTiled2Unity.
