### ISSUE TITLE
Bug/Problem: When importing an isometric tiled map, the tiles are overlapping each other in the wrong way.

### ISSUE THREAD

**Issue by iagomaia** [Seanba/SuperTiled2Unity#34]
When I import an isometric Tiled map into Unity, the tiles are overlapping each other:
![image](https://user-images.githubusercontent.com/7398900/52217182-15033480-287f-11e9-9ce7-64fe7041c53d.png)
While it should actually look like this:
![image](https://user-images.githubusercontent.com/7398900/52217236-2f3d1280-287f-11e9-9482-8f1b1fa503a1.png)
I tried messing around with some configs and changing the Layer/Object Sorting from "Stacking" to "Overhead Dynamic" changed it on the scene, but it messed with my tiles layers when I hit play and test the game.
Inside the Scene:
![image](https://user-images.githubusercontent.com/7398900/52217503-b25e6880-287f-11e9-9ba3-ceedcb11c946.png)
When I hit play and go to game mode:
![image](https://user-images.githubusercontent.com/7398900/52217636-010c0280-2880-11e9-999c-27d4795ebca8.png)
As its possible to see, the plants and the road, wich are in other layers, have been overlapped.

**Comment by Seanba** [comment]
Hi there, @iagomaia. I may need to rethink my approach to isometric maps now that Unity has better support for them. Do you mind sending me your Unity project, exported as a Unity Package? I'd like to use it as a guide. Thanks!

sean@seanba.com

**Comment by Seanba** [comment]
Thanks, @iagomaia. I'm neck deep into the isometric code and hope to have a new version of SuperTiled2Unity ready in the next couple of days.

**Comment by Seanba** [comment]
Super2Unity 1.2.1 was just published. This is a rewrite of how isometric maps are created in Unity and it renders your map with no weird seems or overlaps. In other words, the render order of the tiles appears correct:
![image](https://user-images.githubusercontent.com/6980630/52928718-d8b3e780-3306-11e9-88c1-d453b2e7e174.png)

Here's a couple of things you'll need to know:

1) You'll need to use the new 'Custom Sort Axis' sorting option in the inspector or your map asset.
![image](https://user-images.githubusercontent.com/6980630/52928811-3b0ce800-3307-11e9-9f35-b59e14dd740d.png)

2) This requires you to change some graphics settings for your project. Namely, you'll need to set a custom Transparency Sort Axis that is used in your render pipeline.

![image](https://user-images.githubusercontent.com/6980630/52928841-61cb1e80-3307-11e9-8ab1-b9a623dde867.png)

The idea here is that tile positions are projected onto a vector (0, 1, -1). This makes tiles lower on the screen and on later tile layers be further away from the camera so they are rendered in the correct order (sorry, it's a Unity thing that makes this more complicated than perhaps it could be, but that's the price of having a generic, all-purpose engine like Unity).

Let me know if that works for you. Thanks.

**Comment by iagomaia** [comment]
I will test it as soon as possible, thank you very much @Seanba!

**Comment by Seanba** [comment]
I'm going to close this for now but feel free to re-open if you're still having trouble with overlapping.
