### ISSUE TITLE
Program not importing tiled maps + compiler errors

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Seanba/SuperTiled2Unity#35]
Hi! I already posted my problem on the Tiled forums (here: https://discourse.mapeditor.org/t/tiled2unity-problem/3736/3), but i think it belongs there now.
Basically, i imported the unitypackage into my project, but the weird part is that when i click "Import New Assets", the explorer shows up, but doesn't show my tiled files, my maps. So... Have you got any ideas of why it's doing this?

**Comment by DonTomasDeLaVega** [comment]
Edit: Now, it's telling me this when i import the package:
"Assets/SuperTiled2Unity/Scripts/Editor/AssetTypes/SuperAsset.cs(22,25): error CS1061: Type `UnityEditor.Experimental.AssetImporters.AssetImportContext' does not contain a definition for `DependsOnSourceAsset' and no extension method `DependsOnSourceAsset' of type `UnityEditor.Experimental.AssetImporters.AssetImportContext' could be found. Are you missing an assembly reference?
"

**Comment by Seanba** [comment]
Hi there, @DonTomasDeLaVega. What version of Unity are you using?

**Comment by DonTomasDeLaVega** [comment]
I updated it thinking it was the thing that was making it bugged, but still nothing:
i am now on version 2018.3.4f1 (64-bits by the way)

**Comment by Seanba** [comment]
Check your Package Manager (Menu Bar: `Windows -> Package Manager`) and make sure the built-in package `Tilemap` is enabled.

![image](https://user-images.githubusercontent.com/6980630/52360406-89fe7780-2a01-11e9-8b7d-b3181f19981b.png)

If that isn't working for you then send me your project (sean@seanba.com) and I'll take a look. Thanks.

**Comment by DonTomasDeLaVega** [comment]
Okay, it's working properly now, thanks! I just ran Unity, to check what you asked me, and it magically worked... Thanks a lot, back to work!
