### ISSUE TITLE
Feature request: More options for sprite atlas generation

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#38]
As discussed in #36 :

It would be nice to have some more options for generating the sprite atlases. Since currently a custom atlas system is used, I'm not sure what all the options that could be exposed are. But I was thinking about things like e.g. a compression quality setting.

**Comment by Seanba** [comment]
Thinking about this some more I think the best way forward is to use Unity's sprite atlases. Unity doesn't give us as much scripting support on those that I would like but hopefully that will change soon.

**Comment by SharlatanY** [comment]
Sure, that's fine by me! In the long run it will probably pay in most cases to use Unity's inbuilt systems.

**Comment by Seanba** [comment]
What concerns me the most is I would like some feedback when a sprite/tile doesn't fit inside a given Sprite Atlas and as far as I can tell that information is not available through scripting. I'll look into it deeper though when I get around to this. Thanks.

**Comment by Seanba** [comment]
Sorry to have taken so long to reply to this but internal sprite atlases were troublesome and were finally removed with `v2.2.0`. We now use the source texture and a custom importer adds the sprites it needs there. You can then choose to put that source texture into an atlas if you wish. Thanks.
