### ISSUE TITLE
Texture was imported at a smaller size. Make sure "Max Size" is at least 2516

### ISSUE THREAD

**Issue by l8hf21** [Seanba/SuperTiled2Unity#40]
Where 2516 seems to be the width of the image asset that it's trying to import. I'm getting this on multiple tilemaps and images. After that error message it reads "Could not find Tile X. Make sure the tilesets were successfully imported" for every tile ID that is used in the map.

I was able to fix it on one map by moving around tiles to a different width but I'm not sure how that fixed anything, and the tileset widths range from 48px to 2516px on different TMX maps, could you shed some light on how to avoid this error message?

**Comment by Seanba** [comment]
Hi there, @l8hf21. Your source texture importer settings probably has "Max Size" set to 2048. This shrinks your 2516 pixel-wide texture and, therefore, gets in the way of creating tiles from your texture. 

The error should have given you the name of the texture that needs to be fixed. Was this not the case for you?

**Comment by Seanba** [comment]
BTW, here's a pic of the Max Size setting in the texture importer:

![image](https://user-images.githubusercontent.com/6980630/52610808-4ca64980-2e48-11e9-9f84-e1882ae2ebf8.png)

**Comment by l8hf21** [comment]
Ah, I didn't realize that was what the error meant but that makes total sense, just tweaked that on a few maps and the error goes away -- thank you @Seanba!
