### ISSUE TITLE
Bug: Animations broken if there are unused Tile ID's below the TileID of an animation

### ISSUE THREAD

**Issue by DespawnFinch** [Seanba/SuperTiled2Unity#41]
I had a tileset which had some tiles removed at one point. So instead of the tiles being 0, 1, 2, 3, etc. they started at 3, 4, 5, 6, etc. On this tileset tile 7 had an animation on it involving tiles 7, 8, 9, 10, 11 and 12. 

When imported into Unity 2018.3 on the latest version of ST2U, this tileset specifically would throw an unknown error. The stacktrace led me to Line 258 of TilesetLoader.cs. 

After some debugging, I realized that 
xAnimation.Elements("frame").Select(f => f.GetAttributeAs<int>("tileid"))
was returning ints of 3, 4, 5, 6 and so on.

m_TilesetScript.m_Tiles[index]
uses those ints as the index, so it gets the fourth element in the m_tiles list instead of the first one. This causes the animations used to use the wrong frames and then end up out of range at a certain point.

I fixed the issue by creating a new tileset and re-adding the images and animations to it, then re-adding the objects to the tilemap. Then it worked perfectly, because the IDs started at 0 instead of 3.

**Comment by Seanba** [comment]
Hi @thetomfinch, this sounds like a good find on your part. By any chance do you still have the old tileset that was causing the issue? I'd like to test any potential fix against it.

**Comment by thetomfinch** [comment]
Unfortunately not. You should be able to reproduce it by taking one of your example tile sheets with an animation, removing some tiles and re-adding them, then attempting to import it into unity.

**Comment by Seanba** [comment]
Okay. I guess you had a tileset that was based on a collection of images though, right? And not a single texture that was cut into tiles?

**Comment by thetomfinch** [comment]
Yeah, exactly.

**Comment by Seanba** [comment]
Hi again, @DespawnFinch. Version 1.2.3 of SuperTiled2Unity fixes this. Thank you for digging deep and providing such a well-written bug report.  :)

https://seanba.itch.io/supertiled2unity/devlog/68925/supertiled2unity-version-123
