### ISSUE TITLE
Errors after importing.

### ISSUE THREAD

**Issue by DonTomasDeLaVega** [Seanba/SuperTiled2Unity#44]
Hi! So here are my problems: i've done my maps on tiled, nothing too complicated, and i decide to import it into unity using ST2U, that i already used someday. So i click on Assets>Import New Assets; select the map, the tileset and the tileset's image, import them, but then, error messages on the screenshots. What should i do?
![erreur1](https://user-images.githubusercontent.com/47381187/53429882-c19f8480-39ed-11e9-940e-a4f793d5e063.PNG) (error on the map's inspector)
![erreur2](https://user-images.githubusercontent.com/47381187/53429884-c2381b00-39ed-11e9-96eb-0754afa9aa4c.PNG) (error on the tileset's inspector)
Thank you, Don Thomas.

**Comment by Seanba** [comment]
Hi there, @DonTomasDeLaVega. It looks like your TSX file is expecting your location to be in a different folder, specifically at `../../test-ooh ca l'air bien fait/Assets/Textures/Murs etc.png`

Is `test-ooh ca l'air bien fait` a separate project? Or should `Murs etc.png` be moved into your `Textures` directory?

Once you get the relative paths of your TSX and texture files set up correctly it should work for you.

**Comment by DonTomasDeLaVega** [comment]
Yeah, it is another project actually... How can i change those paths to the real ones?

**Comment by Seanba** [comment]
It's probably easiest at this point to edit your `Murs etcwola.tsx` file by hand.

Look at it in a text editor and where you see something like this ...

`<image source="../../test-ooh ca l'air bien fait/Assets/Textures/Murs etc.png" ..../>`

... replace it with your new relative path ...

`<image source="Murs etc.png" ..../>`

**Comment by DonTomasDeLaVega** [comment]
Woah, magic as i love it! It works just fine now, thank you!

**Comment by Seanba** [comment]
I'm glad you got it working. Good luck with your game. :)

**Comment by TurtleFlyte** [comment]
So I have this same problem. But when I edit the text file this happens in tiled-
<img width="1194" alt="Screen Shot 2019-04-20 at 4 12 45 PM" src="https://user-images.githubusercontent.com/49802391/56463373-b0d51480-6387-11e9-8093-1694399d13e3.png">
Then after I locate the file and save it... the same error happens after I import it to unity.
<img width="285" alt="Screen Shot 2019-04-20 at 4 19 37 PM" src="https://user-images.githubusercontent.com/49802391/56463393-2c36c600-6388-11e9-9415-653687baedd0.png">
<img width="282" alt="Screen Shot 2019-04-20 at 4 19 49 PM" src="https://user-images.githubusercontent.com/49802391/56463394-30fb7a00-6388-11e9-801e-74cf86b3ed25.png">

**Comment by Seanba** [comment]
Hi there, @TurtleFlyte. Where does `rougelikeSheet_transparent.png` exist in your Unity project? It looks to me like that `Unity/roguelike-pack/Spritesheet` is a folder on your harddrive, not a folder in your Unity project.

Just to clear, all files referenced by your Tiled files (TMX, TSX, PNG) must be part of your Unity project and their relative paths to each other must be intact.

**Comment by TurtleFlyte** [comment]
There is one in my Unity project and one on my hard drive.

**Comment by Seanba** [comment]
> There is one in my Unity project and one on my hard drive.

Okay, but it looks like your tileset file is referencing the PNG that is *not* part of your Unity project.

Try this:
1. Find rougelikeSheet_transparent.tsx in your Unity project
2. Open that TSX file in Tiled
3. Go to `Tileset -> Properties`
4. Press `Edit...` on the `Image` field
5. Press `Browse...` in the `Edit Tileset` dialog
6. Select the PNG file that is in your Unity project
7. Resave the TSX file

![image](https://user-images.githubusercontent.com/6980630/56472145-7cf9fd80-6420-11e9-8679-1aac5a4bf290.png)

![image](https://user-images.githubusercontent.com/6980630/56472158-b29ee680-6420-11e9-83e8-3eb4c6d6313a.png)

![image](https://user-images.githubusercontent.com/6980630/56472165-cb0f0100-6420-11e9-8e44-b79543dcda91.png)

**Comment by TurtleFlyte** [comment]
I tried that and it didn't work I get this-
<img width="408" alt="Screen Shot 2019-04-21 at 1 14 24 PM" src="https://user-images.githubusercontent.com/49802391/56475031-a40ff980-6437-11e9-8d83-27ccb1947592.png">
<img width="406" alt="Screen Shot 2019-04-21 at 1 14 39 PM" src="https://user-images.githubusercontent.com/49802391/56475032-a40ff980-6437-11e9-9449-6b79292666cb.png">
As you can see I made the changes and the sprite sheet is right there but its still not working.

**Comment by Seanba** [comment]
It looks to me that your relative path should simply be `roguelikeSheet_transparent.png` since it is in the same directory as your TMX and TSX files. However, for some reason, the relative path your tileset is referencing is `Unity/Projects/ActionRPG/Assets/Art/roguelikeSheet_transparent.png`. I'm guessing that `ActionRPG` is the root of your project, right? So, this doesn't look right.

Perhaps it would be easier for you to export your Unity project as a Unity Project and send it to me? My email is sean@seanba.com.
