### ISSUE TITLE
Can you change tiles at runtime?

### ISSUE THREAD

**Issue by Heishe** [Seanba/SuperTiled2Unity#46]
Can I change tile IDs in imported tile layers at runtime?

**Comment by Heishe** [comment]
Answer seems to be: No, you can't. As far as I can see, the tiles from the imported tileset don't get converted into a form where you could use SetTile of the Unity Tilemap component that every layer has.

**Comment by Seanba** [comment]
Hi @Heishe, you could change tiles at runtime by doing something like this ...

```
var tilemap = gameObject.GetComponent<Tilemap>();
tilemap.SetTile(pos, tile);
```
... but I would recommend using a `Sprite` instead for tiles that are dynamic. Note that SuperTiled2Unity does support tile animations out of the box if that is what you're looking for.

**Comment by Seanba** [comment]
You may also find `Prefab Replacements` to be helpful for this kind of thing.

You can read about prefab replacements here: https://supertiled2unity.readthedocs.io/en/latest/manual/extending-the-importer.html#prefab-replacements

And this repo provides a working example of prefab replacements: https://github.com/Seanba/SuperPrefabReplacement
