### ISSUE TITLE
Sorting layouts

### ISSUE THREAD

**Issue by dakiesse** [Seanba/SuperTiled2Unity#54]
It there any way to sort layers as it was with custom property `unity:sortingOrder`?

**Comment by Seanba** [comment]
Hi there, @dakiesse. I've recently updated SuperTiled2Unity (version 1.3.0) to better handle sorting. I'm actually trying to get by without explictly setting the sorting order, however. Is there a reason why you need it?

BTW, the new docs on sorting may be helpful: 
https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html
