### ISSUE TITLE
[Bug] Changing the PPU of my Tiled level from the default 32 PPU to 16 PPU is not properly stretching the tile

### ISSUE THREAD

**Issue by TannerMoore** [Seanba/SuperTiled2Unity#55]
ST2U by default imports at a PPU of 32. My tileset is 16x16. Here is what my level looks like in Unity with the default settings:

[16x16 tileset at a 32 PPU](https://i.imgur.com/ZVKL4Jc.png)

Here is what happens when I switch the PPU setting to 16

[16x16 tileset at a 16 PPU](https://i.imgur.com/ZEl34gE.png)

The problem is actually easy to reason about. The tilemap is set to take up double the space per tile, but the actual image data is kept 32PPU.

**Comment by Seanba** [comment]
Hi @TannerMoore, what's probably happening is that your map is using the new PPU but the tilesets it is using are still using the old PPU. Can you try looking at the import settings for your tilesets and see if that fixes them up for you?

**Comment by TannerMoore** [comment]
Sure, how do I look at those?

**Comment by seanb-22ct** [comment]
Hi again, @TannerMoore. If you look at the inspector for your map file you can see the list of dependencies. The files with the TSX extension are your tilesets.

![image](https://user-images.githubusercontent.com/18538373/55497122-3e81d780-5606-11e9-8a11-fa93d3237352.png)

If you visit those TSX assets then you can make sure their PPU settings are what you expect ...

![image](https://user-images.githubusercontent.com/18538373/55497213-81dc4600-5606-11e9-9d27-362673cedb7b.png)

BTW, version 1.3.0 of SuperTiled2Unity (which I just released today) makes it easier for you to select these dependency files. Just right-click on one of your dependency (or reference) files and you'll have the option to select it in the inspector.

![image](https://user-images.githubusercontent.com/18538373/55497307-b51ed500-5606-11e9-9d8c-fe3326562bfa.png)

**Comment by TannerMoore** [comment]
Thanks for the detailed reply! I decided to update to your 1.3.0 library, but now I hit a new issue before I can try to fix the first one. It is saying the asset paths are incorrect. I am in Tiled right now and Tiled is happy. The path to the missing tileset is accurately pointing to outdoor-suumer.tsx, so I am not sure what to try next. here is the error:

https://i.imgur.com/D26ihAT.png

**Comment by seanb-22ct** [comment]
What is the location of outdoor-summer.tsx in your project? SuperTiled2Unity is looking for it here:

Assets/_Game/Art/tilesets/outdoor/summer/outdoor-summer.tsx

If that looks right to you then can you send export your project as a Unity package and send it to me? Thanks.

**Comment by TannerMoore** [comment]
I can't send off this project, but the good news is I fixed the path error. Here is what I did:

- Manually delete the SuperTiled2Unity folder in my project
- Re-imported 1.1.9 (what I was using before)
- Let everything process and get happy again
- Delete the SuperTiled2Unity folder again
- Re-imported 1.3.0
- No more path errors.

When I first upgraded from 1.1.9>1.3.0, I did not clear out the SuperTiled2Unity folder by hand. Do you think that could cause issues?

**Comment by TannerMoore** [comment]
on 1.1.9, changing the PPU of the underlying tilesets did the trick! Now onto the current 1.3.0 weirdness. Here is a video of what I see:

https://www.youtube.com/watch?v=3dZtJLSsaYk&feature=youtu.be

**Comment by Seanba** [comment]
I see you've run into a compile error that I'm not getting. By any chance are using the deprecated .NET 3.5 Framework?

See the `Project Settings -> Player -> Configuration` 

![image](https://user-images.githubusercontent.com/6980630/55522863-55e3b380-564c-11e9-9a6c-b2f836a6f4a8.png)

**Comment by TannerMoore** [comment]
Yeah, that was the trick. Good catch. Any idea what is causing the smashed/distorted tiles with the 1.3.0 integration?

**Comment by Seanba** [comment]
I don't know what's going on there. And I've tried re-importing my own maps at different PPU sizes to test. You can try to force a re-import of all your Tiled assets by clicking on `S2TU Settings` and then `Reimport Tiled Assets` in the inspector.

![image](https://user-images.githubusercontent.com/6980630/55523650-b9231500-564f-11e9-88dc-2e9de5684e0f.png)

If that doesn't work out for you then I need someway of replicating the bug you have experiencing. I understand not wanting to send the full project to me but if you exported just your Assets/Levels and whatever portions of Assets/Art that contain your tilesets and tileset textures then maybe that would help me reproduce.

**Comment by TannerMoore** [comment]
If I get some time tonight, I will make a fresh project with just my tilesets and see if it reproduces the issue.

**Comment by seanb-22ct** [comment]
It might help me track down what is going on if you can send a screen shot of your map instance in the inspector and remind me what PPU you are using now. For instance ...

![image](https://user-images.githubusercontent.com/18538373/55571898-0f359e00-56cc-11e9-8c20-4afa92a43d84.png)

The relationship between Tile Width, Tile Height, Cell Size, and PPU may be the answer here.

**Comment by TannerMoore** [comment]
I have a bare-bones package ready for you to look at locally

Context: 
- I pulled out my tilemaps and map into their own folder
- I created a brand new Unity project
- Imported your 1.3.0 integration
- Drug my map onto the scene
- I configured absolutely nothing in the project in any way

https://i.imgur.com/EHyAH8U.png

Do you have a public email?

**Comment by Seanba** [comment]
Yeah, you can email me at: sean@seanba.com
Thanks.

**Comment by Seanba** [comment]
Hi again, @TannerMoore. This looks like it's a problem with SuperTiled2Unity not handling maps correctly when the `Infinite` map property is set. I'm looking into it but in the meantime if you disable the infinite setting it may work for you. Thanks.

**Comment by seanb-22ct** [comment]
I just published [SuperTiled2Unity version 1.3.1](https://seanba.itch.io/supertiled2unity/devlog/76009/supertiled2unity-version-131) which fixes this problem with infinite maps.

Thanks for sticking with this, btw. It was a big help.

**Comment by TannerMoore** [comment]
Glad to have helped out! I have been using ST2U since release. It has been a huge reason why I am still working on my current project.

**Comment by TannerMoore** [comment]
I just updated to 1.3.1 and it is almost all happy. The colliders are still a little off. It looks like the collision data is scaling at a different rate than the tiles when the map is set to infinite.

Collision data in correct place (infinite map scaling is set to off):
https://i.imgur.com/nbUQAL7.png

Collision data is not lining up with tiles properly (infinite map scaling is set to on):
https://i.imgur.com/eol5ZQx.png

**Comment by Seanba** [comment]
Ah nuts. As soon as I read that last bug report I knew exactly what I missed too. My apologies.

[SuperTiled2Unity version 1.3.2](https://seanba.itch.io/supertiled2unity/devlog/76083/supertiled2unity-version-132) fixes the position of colliders on infinite maps.

**Comment by TannerMoore** [comment]
1.3.2 is working great with my infinite maps. Thanks again for keeping this tool running smoothly!
