### ISSUE TITLE
Getting custom properties of colliders

### ISSUE THREAD

**Issue by mzoeller** [Seanba/SuperTiled2Unity#59]
I'm wondering if there a way to get custom properties of colliders? I have seen your very helpful example at
https://github.com/Seanba/ST2U_TileProperties but if I understand correctly this only gives access to the tile's properties.
Thanks!

**Comment by Seanba** [comment]
Hi @mzoeller. It's going to depend on which collider properties you want to get at. 

- **Tile Layers:** the colliders are combined into a larger composite and the custom properties are lost in the process.
- **Tile Objects:** the custom properties are accessible. Look for a `SuperCustomProperties` component and go from there.
- **Tile** This a bit trickier but the custom properties should be accessible through `SuperTile.m_CollisionObjects.m_CustomProperites`

If you explain to me what you'd like to accomplish a bit more I might be able to provide additional advice. Thanks.

**Comment by mzoeller** [comment]
Hi @Seanba. 

Thanks, I think I understand now. If  we'd want to keep individual collider's custom properties we'd have to keep them all as seperate GameObjects inside Unity, degrading performance. Correct?

I was asking because the way we implement slopes at the moment is through colliders defined in the tiles. Each tile gets a Unity layer via `unity:layer` is set as `unity:isTrigger`. So we have 8 Layers (N, NE, E, SE, ...). When our character hits a trigger we move it according to the layer the collider is in. It works but it's not very elegant. 

So I was wondering if maybe I could make all colliders the same Unity layer (i.e. slope) and than have some other way of specifying the slope direction (i.e. as collider properties). Maybe another way would be to specify that inside the tile and only when triggering  a collider accessing that information through `SuperTile.m_CollisionObjects.m_CustomProperties`.

**Comment by seanb-22ct** [comment]
Hi again, @mzoeller. Sorry for the late reply.

I think you've got the right idea with putting your colliders on the same "slope" layer. I think this scheme could get you what you want:

1. Put all your colliders on the same layer
2. Remove the `unity:isTrigger` custom properties.
3. Have a `RigidBody2D` component on your character with `Body Type` set to `Kinematic`.
4. Use the `OnCollisionEnter2D` (as opposed to `OnTriggerEnter2D`) to detect when a collision is made.
5. Check the `normal` of the contact points on the collision object. These normals should be approximately orthogonal to your N, NE, E, SE, S, SW, W, NW directions.

You'll need a little bit of math to deal with approximation issues (i.e. the normals may not be pointing perfectly in one of your 8 directions) but this should get you what you want.

FWIW, here is a character controller that I've used before in a pinch that handles slopes well. You may find it useful too: https://github.com/prime31/CharacterController2D

**Comment by rdsdehal** [comment]
@Seanba Is there any particular tutorial for us to set up the complete layer as colliders? For example, I have a map with 5 layers, one of the layers is for trees and I don't want the player to run over them. But I can't add a box collider to all trees. So, How can we do this?

**Comment by Seanba** [comment]
Hi @rdsdehal. You do that through the Collision Editor (in Tiled) by adding a collider to your tree tile.

![image](https://user-images.githubusercontent.com/6980630/56746966-cb6e0b80-6742-11e9-878b-9f05ae9dcc08.png)

When you save the tileset then colliders will automatically be created for you. SuperTiled2Unity comes with an example (see `Assets/SuperTiled2Unity/Examples/Overhead`) that does this if you need a reference.

**Comment by rdsdehal** [comment]
Hi @Seanba, Thank for the reply mate. 
I have added the collider to the tileset and it seems to be working in Unity too. Although my player is still walking over it. I have a rigidbody on my player just like you did on your Example Project, but no luck yet.
Here is the Screenshot: http://prntscr.com/nh27fg

**Comment by rdsdehal** [comment]
> Hi @Seanba, Thank for the reply mate.
> I have added the collider to the tileset and it seems to be working in Unity too. Although my player is still walking over it. I have a rigidbody on my player just like you did on your Example Project, but no luck yet.
> Here is the Screenshot: http://prntscr.com/nh27fg

I have fixed it myself, Just change the Rigidbody 2D to Dynamic to detect collision. Turned the project gravity to 0 and freeze the rotation at Z axis. 
Thank you making this Prefab, you have been a lifesaver.

**Comment by Seanba** [comment]
Hi again, @rdsdehal. There are two common approaches to handling collision detection and physics with 2D games in Unity.

1) Use the built-in `Physics2D` system (based on Box2D) that moves your character around for you.
2) Use a series of raycasts to detect where a collision would take place and move the character yourself.

As you discovered, option 1 requires a dynamic rigidbody. For the record, I generally require tighter control of my sprites and I often use the raycast approach instead.
