### ISSUE TITLE
Can't put the map into my scene correctly.

### ISSUE THREAD

**Issue by RaBeMi** [Seanba/SuperTiled2Unity#60]
When I put the map on the Unity Scene it is too small, and i can't do it big, i don't know what to do now, please help.

PD: Sorry for my bad english.

**Comment by RaBeMi** [comment]
If it's necessary put images for helping me, tell me.

**Comment by seanb-22ct** [comment]
Hi there, @RaBeMi. This is probably an issue with the default `Pixels Per Unit` being 100. This is the same default value that Unity uses for sprites.

If you want one pixel to be one unit then try setting the `Pixels Per Unit` setting for your maps and tilesets to 1. (Make sure to hit `Apply` after you make these changes).

![image](https://user-images.githubusercontent.com/18538373/55986775-b767db80-5c65-11e9-930a-59bb8777eefb.png)

![image](https://user-images.githubusercontent.com/18538373/55986784-bcc52600-5c65-11e9-9b32-dd37e7997581.png)

BTW, you can change the default `Pixels Per Unity` setting to always be 1 in the `ST2U Settings` asset.

![image](https://user-images.githubusercontent.com/18538373/55986870-ebdb9780-5c65-11e9-9d4e-a87ff1b5fb90.png)

![image](https://user-images.githubusercontent.com/18538373/55986927-0e6db080-5c66-11e9-9f91-e324a90bf19c.png)

Hope that helps!

**Comment by seanb-22ct** [comment]
BTW, you almost always want to use the same `Pixels Per Unit` across all sprites, maps, and tilesets for your game.

**Comment by RaBeMi** [comment]
Thank you so much, i will try that on a second and I tell you.

**Comment by RaBeMi** [comment]
It worked, thanks Sean :D
