### ISSUE TITLE
Tiled Object Sizing Issues

### ISSUE THREAD

**Issue by david-bingham** [Seanba/SuperTiled2Unity#61]
If my Tiled Object is 1*1 pixels, it looks incorrect in Tiled:
![11 in Tiled](https://user-images.githubusercontent.com/22459584/56083291-249f7c00-5de0-11e9-85ed-6bf8e73bf552.PNG)

But it looks correct in Unity:
![Looks Right in Unity](https://user-images.githubusercontent.com/22459584/56083293-2b2df380-5de0-11e9-9b18-79aab4d3cbb9.PNG)

If my Tiled Object is 32*32 pixels, it looks correct in Tiled:
![3232 in Tiled](https://user-images.githubusercontent.com/22459584/56083295-36811f00-5de0-11e9-820a-14357cff35b5.PNG)

But it looks incorrect in Unity:
![Looks wrong in unity](https://user-images.githubusercontent.com/22459584/56083306-557fb100-5de0-11e9-813f-dd0d1596472c.PNG)

My ST2U Settings are:
![ST2U](https://user-images.githubusercontent.com/22459584/56083311-5fa1af80-5de0-11e9-82dc-afbdc191eb46.PNG)

Changing and Applying my Pixels Per Unit in ST2U seems to have no effect whatsoever.

**Comment by Seanba** [comment]
Hi there, @david-bingham. The `Default Pixels Per Unit` field in `S2TU Settings` doesn't change tilesets and maps that have already been imported to your Unity project. Rather, they are they default fields that go into your map and tileset inspectors the first time they are imported.

You'll need to go to the inspector for your map and tilesets separately and change their `Pixels Per Unit` field and then hit `Apply`.

**Comment by Seanba** [comment]
Hi @david-bingham. Are you still running into issues with this? If my suggestion is not helping then send me your project (exported as a Unity Package is okay) and I can take a look. Thanks.

**Comment by Seanba** [comment]
With version 1.5.6 you will now see a warning in the inspector of your map in case your tileset and map do not have matching `Pixels Per Unit` settings. If this is not the problem you were having please let me know and I will re-open this bug. Thanks.
