### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by RaBeMi** [Seanba/SuperTiled2Unity#62]
Hello, i need help, i am viewing a tutorial and he is using Tiled2Unity, the problem is that some variables of Tiled2Unity named "Tiled2Unity.TiledMap.NumTilesWide" and "Tiled2Unity.TiledMap.NumTilesHigh" are different on SuperTiled2Unity and I can't find the equals. Please, help.

Edited: I put wrong the variables.

**Comment by Seanba** [comment]
Are you trying to write a custom importer? Perhaps if you point me to the tutorial you're talking about I can better help you.

It's possible that `SuperMap.m_Width` and `SuperMap.m_Height` is what you're looking for. That is the number of tiles wide and high a map is in SuperTiled2Unity.

You might find [this repository](https://github.com/Seanba/SuperMovingPlatform) useful. It has a custom importer in it that places a sprite on a track (see `TrackCustomImporter.cs`).
