### ISSUE TITLE
Feature request: Add support for public variables for Tiled Object -> Prefab replacement value mapping

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#64]
Hello Sean,

first, let me tell you that I love your feature that lets us replace tiled objects with prefabs, I will be able to get rid of most of my custom importers thanks to that!

Now to my feature request: It's great that values from tiled objects are auto mapped to public properties on the prefabs. It's what's making this a viable replacement for a lot of my custom importers in the first place. However, as things are now, only properties are mapped, not variables. Could you please add mapping of public variables as well? I'm aware that properties normally are the way to go in C# but since the Unity editor doesn't support properties out of the box and I sometimes want to be able to edit those values in the editor as well, I sometimes use public variables; it's just too cumbersome to write a custom drawer for a script every time I want to expose a variable.

I think the fix would be quite easy. What you do now is the following:

```csharp
var csprop = comp.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public).Where(
    info => info.CanWrite &&
    info.Name == property.m_Name &&
    info.PropertyType == objValue.GetType()
    ).FirstOrDefault()

if (csprop != null)
{
    csprop.SetValue(comp, objValue, null);
};
```

and a second series of calls looking something like this would probably give you the field if it exists:

```csharp
var csfield = comp.GetType().GetFields(BindingFlags.Instance | BindingFlags.Public).Where(
    info => !info.IsInitOnly &&
    info.Name == property.m_Name &&
    info.FieldType == objValue.GetType()
    ).FirstOrDefault();

if (csfield != null)
{
    csfield.SetValue(comp, objValue);
}
```

Code works for my case but not sure if I missed any important properties that would need to be checked.

Also, an optional feature to log a warning if a property can't be mapped (optional because it might be intended in some cases and you don't want to get the warning all the time) might be worth thinking about.

Thanks for considering!

**Comment by Seanba** [comment]
Hi there, @SharlatanY. With version 1.4.3 you can use public methods, properties, or fields with custom properties and prefab replacments. Thanks for the suggestion.

BTW, I updated the repo on GitHub that uses Prefab Replacements with some documentation.
https://github.com/Seanba/SuperPrefabReplacement

**Comment by SharlatanY** [comment]
@Seanba As always, thanks a lot for your commendable support and dedication! :)

I also really like that we now can call functions with custom property values! Wouldn't even have thought of it myself but already have some use cases in mind, now that the functionality's there!
Also like the documentation. Before, I had to play around a bit and have a look at the code to see how and why it did (or in case of fields, didn't) work and I'm sure this will make ST2U much more accessible to people just getting started!
