### ISSUE TITLE
Feature request: Add support for prefab position offset for Tiled Object -> Prefab replacement

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#65]
Dear Sean,

When I place Tiled objects in my tiled map, that will then be replaced by prefabs upon ST2U import, I use the "Tile" object type and the "snap to grid" functionality to place the object exactly where the prefab should be later on in Unity. That looks something like this:
![https://i.imgur.com/UpWvYGJ.png](https://i.imgur.com/UpWvYGJ.png)

When the objects get replaced by prefabs, the prefabs are placed directly at the object coordinate (makes sense), which is the lower left of the tile. But that way, my prefabs aren't placed where I want them to be; they're in the lower left of the tile instead of the center (sorry, the collider is a little hard to see):
![https://i.imgur.com/3SlpOox.png](https://i.imgur.com/3SlpOox.png)

Now, I can work around this by attaching a child object to the prefab and add the collider/graphics/whatever else needs to be centered to the child object and set an offset to said child object but it's a little clunky.

It would be way nicer, if the prefab replacement code would respect the base offset of the prefab, at least I think.
Could you maybe add in the prefab base offset?

Currently, the code looks like this:

```csharp
var instance = Instantiate(prefab, so.transform.position, so.transform.rotation);
```
And this small change would fix it already:
```csharp
var instance = Instantiate(prefab, so.transform.position + prefab.transform.localPosition, so.transform.rotation);
```
As always, thanks for considering! :)

**Comment by Seanba** [comment]
Sorry I missed this one before but I've added it now in version 1.4.4. Thanks for the suggestion. :)

https://seanba.itch.io/supertiled2unity/devlog/80861/supertiled2unity-version-144

**Comment by SharlatanY** [comment]
Thanks for this one as well, now I know what I'll do next weekend ;)
