### ISSUE TITLE
Feature Request: Set TilesAsObjects per layer

### ISSUE THREAD

**Issue by dithyrambs** [Seanba/SuperTiled2Unity#68]
Right now you can only toggle TilesAsObjects on the entire imported Tiled map itself, but this introduces a lot of complexity in the map when I only need specific tiles to be unique game objects.

I realize there are tons of examples of how to replace tiles with unique prefabs, but it'd be really rad to easily set this in custom properties or something similarly granular and simple (unity:tilesAsObjects, true)

Especially since you're already checking tile layer properties in your tile map importer!

(BTW I've been using Tiled2Unity for years, you are totally awesome and amazing and thank you so much for continuing to improve this excellent tool)

**Comment by Seanba** [comment]
Hi there, @dithyrambs and thanks for the praise. :)

This sounds like something I could add as a custom property of a layer but, before I take action, why not use `Tile Objects` in an `Object Layer` in Tiled?  These object layers are already imported as a group of objects without the need of custom importers or any other tools/settings.

**Comment by dithyrambs** [comment]
Thanks for the quick reply! That's a great point, and this solution works great.

Do you happen to know if Tiled features such as Automapping, Wang Tiles, and Terrains will work on object layers? I guess I assumed these features only worked on map layers! If so, object layers are a perfect solution. I'll try to do some tests this week if you don't know!

**Comment by Seanba** [comment]
I know automapping works with Tile Objects but I'm not sure about Wang and Terrain tiles. If your testing comes up empty let me know and I'll try to find some time to get what you need added to SuperTiled2Unity.
