### ISSUE TITLE
Dependency Not Recognized on Import

### ISSUE THREAD

**Issue by Arkrusti** [Seanba/SuperTiled2Unity#7]
Hello,

I'm attempting to import my first map with Tiled 1.2 and supertiled2unity.  I tried a bunch of things, but in the end, I've ended up with my png (raw image), my tsx (single tileset), and my tmx in one TileMaps folder in my project.  The importer is catching them fine, and has correctly identified the dependency between the png and tsx.  However, it hasn't identified the dependency between the tmx and the tsx, and will not display.  I get the following error:

Missing tileset asset:  Assets/TileMaps/TestMap1.tmx

I have: 
-reimported the tmx, both manually and through the ST2U settings 
-saved and restarted Unity, also reimporting  
-double checked the source file to make sure everything is hooked up to the correct map, I'm working with very few files as this is just a test

If you could let me know if I'm doing something out of order, or if I need to add the dependency myself via script, I'd be very grateful.  I've been following Tiled and Tiled2Unity for several years, and I'm very thankful for your hard work.

Arkrusti

**Comment by Seanba** [comment]
Hi there, Arkrusti. Can you send your Unity project? Thanks. (sean@seanba.com)

**Comment by Arkrusti** [comment]
No problem.

**Comment by Seanba** [comment]
No worries, I get the email.

SuperTiled2Unity was incorrectly reporting a missing TSX file. I've just now fixed that [with version 1.1.1](https://seanba.itch.io/supertiled2unity/devlog/54546/supertiled2unity-version-111).

BTW, the TSX you were missing from your Unity project is at `Program Files (x86)/Tiled/PrototypeARPG.tsx`. Note that you'll have to fix the reference to this within your Tiled map file (`TestMap1.tmx`) once you move it over to your project.

Thanks for the bug report!

**Comment by Arkrusti** [comment]
Cool, thanks!
