### ISSUE TITLE
Problems after update Unity 

### ISSUE THREAD

**Issue by jfroimovich** [Seanba/SuperTiled2Unity#70]
Hi!

Everything was working fine, but recently I update Unity to Unity 2019.1.0f2 version and after that the problems stars. 
The first issue was that the map I puted on Unity scene dissapear, and all objects names was with (Missing Prefab) legend. I tried creating a new map in Tiled, but when Unity get the map file the console display the next message:

`transform.localPosition assign attempt for 'Layer 1' is not valid. Input localPosition is { NaN, NaN, 0.000000 }.
UnityEngine.Transform:set_localPosition(Vector3)
SuperTiled2Unity.Editor.GameObjectExtensions:AddSuperLayerGameObject(GameObject, SuperLayerLoader, SuperImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Extensions/GameObjectExtensions.cs:114)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessTileLayer(GameObject, XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.TileLayer.cs:35)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessMapLayers(GameObject, XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.cs:241)
SuperTiled2Unity.Editor.TmxAssetImporter:ProcessMap(XElement) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.cs:82)
SuperTiled2Unity.Editor.TmxAssetImporter:InternalOnImportAsset() (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/TmxAssetImporter.cs:53)
SuperTiled2Unity.Editor.SuperImporter:OnImportAsset(AssetImportContext) (at Assets/SuperTiled2Unity/Scripts/Editor/Importers/SuperImporter.cs:72)
UnityEditor.Experimental.AssetImporters.ScriptedImporter:GenerateAssetData(AssetImportContext)
`

I tried reinstalling Super Tiled2Unity but the issue persist.

Unity Version 2019.1.0f2 
SuperTiled2Unity version  SuperTiled2Unity.1.4.0

**Comment by Seanba** [comment]
Hi there, @jfroimovich. I've run into problems to when upgrading Unity versions, particularly with missing prefabs, but this seems particularly bad. Check your `Pixels Per Unit` setting in the inspector for your map. It looks like the map may have been imported with a zero PPU value.

If the problem persists can you export your project as a Unity Package and send it to me at sean@seanba.com? Thanks.

**Comment by jfroimovich** [comment]
> Hi there, @jfroimovich. I've run into problems too when upgrading Unity versions, particularly with missing prefabs, but this seems really bad. Check your `Pixels Per Unit` setting in the inspector for your map. It looks like the map may have been imported with a zero PPU value.
> 
> Also, can you try forcing an import of your map by right clicking on your TMX asset in Unity and selecting `Reimport`?
> 
> If the problem persists can you export your project as a Unity Package and send it to me at [sean@seanba.com](mailto:sean@seanba.com)? Thanks.

Thanks for answer! Configuring "Pixels Per Unit" fixed the issue. As you said, Tilted is importing maps without pixel per unit. 

Regards

**Comment by Seanba** [comment]
Okay, glad you got it working.

I can't get that to happen because the validation that doesn't allow zero values for PPU is working for me. However, it appears that you've gotten into this state somehow. If you wouldn't mind I'd still like to take a look at your project to try to figure out what is going on.

**Comment by Valkrysa** [comment]
Occurred for me today using maps generated in latest Tiled and imported using Super Tiled2Unity 1.4.4.
Solution was indeed to go to each TSX and TMX and set PPU to 16.

**Comment by Seanba** [comment]
Hi there @Valkrysa (and hi again, @jfroimovich). I was able to finally reproduce this bug and have provided a fix with version 1.4.5. My apologies for having introduced such a nasty bug.

https://seanba.itch.io/supertiled2unity/devlog/81064/supertiled2unity-version-145
