### ISSUE TITLE
Editing tiles and properties

### ISSUE THREAD

**Issue by destrugter** [Seanba/SuperTiled2Unity#72]
Is it possible to edit tiles and their properties easily? I'm doing something like below where I have to manually create a new tile and have a reference to the tilemap being used. Just not sure if someone has found a better way:

```
tileMap.SetTile(cellPosition, new UnityEngine.Tilemaps.Tile() { sprite = tileSprite });
SuperTile newTile = new SuperTile()
{
	m_AnimationSprites = tile.m_AnimationSprites,
	m_CollisionObjects = tile.m_CollisionObjects,
	m_CustomProperties = tile.m_CustomProperties,
	m_Height = tile.m_Height,
	m_Sprite = tileSprite,
	m_TileId = tile.m_TileId,
	m_TileOffsetX = tile.m_TileOffsetX,
	m_TileOffsetY = tile.m_TileOffsetY,
	m_Type = tile.m_Type,
	m_Width = tile.m_Width,
	hideFlags = tile.hideFlags,
	name = tile.name
};

newTile.m_CustomProperties.Where(x => x.m_Name.ToLower().Equals("isworked")).FirstOrDefault().m_Value = "true";
```

**Comment by Seanba** [comment]
Hi there, @destrugter. In general, you should probably treat custom properties as read-only data. If you need to store and change state on some game objects related to your Tiled map then you should use your own MonoBehaviours for that.

You can use Prefab Replacements to inject custom behavior into your Tiled maps. You may find this repo useful for describing how to go about this: https://github.com/Seanba/SuperPrefabReplacement

**Comment by destrugter** [comment]
Thanks for the reply. I will definitely be checking your link out. I do have a question as it is related. If this is out of scope, or you do not feel like answering, or whatever. That's fine. I realize this isn't a forum and my issue should be closed now. Feel free.

I was using Tiled's custom properties to not be read only. I do not know their true intention, admittedly. Would you say the properties of the tile in terms of Tiled properties are not meant to be mutated? Essentially I was thinking that I would attach the property data to the tile itself, rather than a separate class/array system. If this isn't an appropriate thing to do I'd love to know. 

Thanks!

**Comment by Seanba** [comment]
Hi again, @destrugter. Yes, I would treat the Tiled properties as if they shouldn't be mutated. In fact, for my personal projects, I commonly use them once during the import process and then discard of them.

What kind of mutable data do you want to apply to your tiles? If you can explain a bit more what you'd like to accomplish then I may be able to direct you better. :)

**Comment by destrugter** [comment]
The player will be able to directly modify the tile by interacting with them, that's all. I think your link may help me achieve that, I haven't had the chance to look yet.

Thanks for the info, I figured I was on the wrong mindset when you replied.

**Comment by destrugter** [comment]
So, for example I want to let a player be able to till a tile, making it suitable to plant something

**Comment by Seanba** [comment]
> So, for example I want to let a player be able to till a tile, making it suitable to plant something

Okay, yeah, that is totally something you want to be doing through a sprite that has `MonoBehaviour` (components) on it that help you manage game state and interact with the player.

Tiled and SuperTiled2Unity are still useful here but in more of a sense where you put down a placeholder (Tiled) object that is replaced by (Unity) object during import.

**Comment by destrugter** [comment]
So you're saying to basically use SuperPrefabReplacement for every tile?

**Comment by Seanba** [comment]
Hi again, @destrugter, sorry for that late reply. I wouldn't use Prefab Replacements for every single tile, just those tiles that change state or behavior in realtime based on gameplay. For instance, if I had grass tiles in a Zelda game that my character cut cut down and perhaps spawn some gems then, yes, that grass "tile" would be some Unity sprite prefab that I would have SuperTiled2Unity instantiate through Prefab Replacements.

Using Typed Tiles and Tile Objects in the Tiled Map Editor should combined with Prefab Replacements should make this pretty simple. 

![image](https://user-images.githubusercontent.com/6980630/58351455-74855000-7e2e-11e9-86c1-cb83d445a479.png)

![image](https://user-images.githubusercontent.com/6980630/58351467-79e29a80-7e2e-11e9-81c3-80dea55f62cb.png)

**Comment by destrugter** [comment]
Yeah, my game is a farming game where the player can till ground, plant stuff, water it, etc. that's why I asked about that. Thanks for writing that up

**Comment by Seanba** [comment]
I'm going to close this issue for now but let me know if clarification was still needed. Thanks.
