### ISSUE TITLE
No Unity Colliders for Template Collision Objects in Tiled

### ISSUE THREAD

**Issue by omnipoof** [Seanba/SuperTiled2Unity#73]
I am finding that when I use a template object for a collision shape in the Tiled tile collision editor, the collision shape is not honored by SuperTiled2Unity.  I have a template object called `collider-all.tx` which covers the entire tile as a square, and I've applied it to all tiles that need to collide with the entire tile.  I also have applied custom polygon shapes to other tiles without the use of a template.  When viewing the map in Unity, the custom shapes show up as expected, but the square collider for each tile using the `collider-all.tx` template does not have any collision associated with it.

In another test, if I build a collision shape in Tiled and check Unity the collider shape shows up, but if I then convert the collision shape in Tiled to a template and check Unity the collider is gone.

Tile Collision Editor with `collider-all.tx` template:
![image](https://user-images.githubusercontent.com/19640032/57502296-f490af00-729f-11e9-8661-8b1b9d55fb94.png)

Unity collider shapes with no collider for the tile selected in the above image:
![image](https://user-images.githubusercontent.com/19640032/57502146-3e2cca00-729f-11e9-8790-266cda17c3b0.png)

**Comment by omnipoof** [comment]
I worked around this by building a polygon collider instead and copy/pasting it in each tile

**Comment by Seanba** [comment]
Hi there, @omnipoof. I just gave this a quick test and it looks to be looking for me but perhaps I'm not understanding you fully. Can you send me your Unity project, exported as a Unity Package, for me to debug some? (email: sean@seanba.com)

**Comment by Seanba** [comment]
Ah, I see now. I didn't even know you could use templates in the collision editor. No need to send me your project, @omnipoof. I'll try to find some time to look into this soon.

**Comment by Seanba** [comment]
Good news, the fix wasn't too bad. Version 1.4.2 of SuperTiled2Unity fixes this. Thanks for the bug report, @omnipoof.

https://seanba.itch.io/supertiled2unity/devlog/80630/supertiled2unity-version-142

**Comment by omnipoof** [comment]
Great, thanks @Seanba!
