### ISSUE TITLE
Error Importing Tilesets. Can't import map.

### ISSUE THREAD

**Issue by jfroimovich** [Seanba/SuperTiled2Unity#74]
Hi ! :)

Recently I downloaded the new super Tiled2Unity versión (1.4.5), but when I tried to import a new map it gives me errors:

SuperTiled2Unity version: 1.4.5, Unity version: 2019.1.0f2
Errors detected in tileset 'tileset1.tsx'. Check the tileset inspector for more details. Your map may be broken until these are fixed.
Could not find tile 159. Make sure the tilesets were successfully imported.
Could not find tile 160. Make sure the tilesets were successfully imported.
Could not find tile 183. Make sure the tilesets were successfully imported.
Could not find tile 184. Make sure the tilesets were successfully imported.

And when I check the tileset inspector:

SuperTiled2Unity version: 1.4.5, Unity version: 2019.1.0f2
Missing texture asset: C:/Users/dc_wa/Desktop/Proyecto sin nombre/Recursos/Pixel Art/Escenarios/warped-files/warped-files/PNG/environment/layers/tilesets.png

The png file is there, at location. I tried different ways to solve the problem but I couldn't fix it.

Regards!

**Comment by Seanba** [comment]
Hi there, @jfroimovich. That PNG file is on your desktop but it has to be an asset in your Unity project.

Probably the easiest fix is to drag that PNG into your Unity project. Then, open your TMX file (make sure it's the one in your Unity project) in Tiled and use Tiled to locate the PNG in its new location. When you resave your TSX and TMX files then you should be good.

![image](https://user-images.githubusercontent.com/6980630/57788024-ffae6980-76fb-11e9-8b34-c4e532f90f2b.png)

**Comment by jfroimovich** [comment]
> Hi there, @jfroimovich. That PNG file is on your desktop but it has to be an asset in your Unity project.
> Probably the easiest fix is to drag that PNG into your Unity project. Then, open your TMX file (make sure it's the one in your Unity project) in Tiled and use Tiled to locate the PNG in its new location. When you resave your TSX and TMX files then you should be good.

Thanks! that solved the issue.

Regards :)

**Comment by Seanba** [comment]
Great. Good luck with your game. :)

**Comment by griever-gf** [comment]
If your tiles image file is bigger that 2048x2048, increasing maxtexturesize of texture file AND sprite atlas width/height of *.tsx file also helps.
