### ISSUE TITLE
[Docs request] Link to your docs site in the Github Readme

### ISSUE THREAD

**Issue by TannerMoore** [Seanba/SuperTiled2Unity#75]
I think this is on the itch.io page, but I didn't see a link to it here: https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html

**Comment by Dalqin** [comment]
I always find my way to the documention via this repo's Wiki tab, which links to itch.io, which links to readthedocs.

**Comment by Seanba** [comment]
Sorry it took a stupid long time for 1 minute of work but the docs link is up there now. Thanks.
