### ISSUE TITLE
Animated tiles not importing correctly

### ISSUE THREAD

**Issue by erikDillaman** [Seanba/SuperTiled2Unity#76]
I am having an issue with animated tiles-- they sadly do not appear on the imported maps. I am curious if there is documentation that exists that explains the best process for importing maps/assets in general (such as those with animations) and I am, perhaps, simply going about it the wrong way.  Thanks and shout outs from Austin!

**Comment by Seanba** [comment]
Hi there, @erikDillaman. Animated tiles is something that should "just work" but just to clarify they don't animate while in the editor view - you have to press play to see them animating.

If that's not your issue then could you export your Unity project (as a Unity Package) and send to me? Thanks.

**Comment by erikDillaman** [comment]
You are absolutely correct.  The import and show as empty, but once the scene is set up and running, the animations appear.  Thanks for taking the time to answer.
