### ISSUE TITLE
Question about how ST2U manages Custom Sort Axis sorting

### ISSUE THREAD

**Issue by Tanz0rz** [Seanba/SuperTiled2Unity#77]
I was looking through your sorting documentation [here](https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html) and have gotten sorting for my game working quite nicely. Great job on this! It let me throw out a custom foreground sorter that I was not too fond of. I am doing the [Custom Sort Axis sorting](https://supertiled2unity.readthedocs.io/en/latest/manual/sorting.html) specifically in my project.

I want pixel-perfect dynamic sorting in my game regardless of sprite size. My game's perspective is the same as your included example scene. An example of what I am trying to achieve with the sorting is to have my character properly sort against a variety of object sizes. I want a 5-tile-tall building and a 1-tile-tall rock to change rendering order _the pixel_ my character goes in front of and behind it. **I was able to achieve this** by doing a few things:

- Place all foreground-sortable objects in my Tiled map in Object layers. 
- Walk through the relevant object layers in Unity at runtime and set all Tiled objects' Sprite Renderers  to sort by their pivot point when the scene loads. (Sprites by default have a `Sprite Sort Point` of `Center` which breaks down when dynamically sorting sprites of various sizes.)
- Manually set the pivot all of my character's sprite images/animations (over 100 .png files!) to the bottom center via the [Sprite Editor window](https://docs.unity3d.com/Manual/SpriteEditor.html). The second step was a little painful to do by hand...

Once I did these steps, I got sorting to work almost perfectly. But I can't actually prove that any of the Tiled objects have their pivot point set to the bottom center of the sprite. It looks like it is in the default center position when I view the backing sprite image in Unity's Sprite Editor. Can you explain this at all?

**Comment by Seanba** [comment]
Hi there, @TannerMoore. My apologies for such a late reply. I put together a more advanced sorting example. Does this help answer your question:

https://github.com/Seanba/ST2U_GroundUpSort

**Comment by Seanba** [comment]
I think this has been resolved some time ago but let me know if that's not the case. Thanks.
