### ISSUE TITLE
How to control animated tile stop and play?

### ISSUE THREAD

**Issue by zhengying** [Seanba/SuperTiled2Unity#78]
Can I control animated tile stop and play at runtime? 
thanks.

**Comment by Seanba** [comment]
Hi there, @zhengying. If these are animations on tiles on a tilemap then, no, Unity has no method of turning off  such animations.

However, if these are `Tile Object`s then you could write a script that looks for all `TileObjectAnimator` components in a scene and disable them.

Another approach is to replace objects from your Tiled map with prefabs that give you tighter control over behavior and state. You can find an example and docs on Prefab Replacements here: https://github.com/Seanba/SuperPrefabReplacement

**Comment by zhengying** [comment]
Thanks for your reply Seanba!  Prefab Replacements is work well for me.
