### ISSUE TITLE
Tiled Type not importing

### ISSUE THREAD

**Issue by firebellys** [Seanba/SuperTiled2Unity#8]
- Open a Tileset in Tiled
- Then select a single tile
- Then enter a value in the properties area
- Open Unity
- m_Type is blank

Using Super Custom Properties works fine.

**Comment by firebellys** [comment]
Tested Version: 1.1.1

**Comment by Seanba** [comment]
Hi there. If you've tried [exporting your Tiled Object Types file from Tiled into Unity](https://supertiled2unity.readthedocs.io/en/latest/manual/custom-properties.html#obejct-types-support) (note this is a separate step) and the object typing is still not working for you then can you send my your project as a Unity Package? Thanks.

**Comment by Seanba** [comment]
Hi again. Without more information or an example project I'm going to close out this bug in a couple of days. Tiled Type seems to be working fine for me but perhaps there is something I am missing? Thanks.

**Comment by firebellys** [comment]
Yeah. Maybe close it for now until I'm back home and can test it. I don't
think it's a defect in the end, but maybe a feature I want. Go ahead and
close for now. Thanks.
