### ISSUE TITLE
How to load one tile or tileset in run time? 

### ISSUE THREAD

**Issue by bingxue102685** [Seanba/SuperTiled2Unity#81]

**Comment by bingxue102685** [comment]
How to load one tile or tileset in run time?

**Comment by Seanba** [comment]
Hi there, @bingxue102685. If you asking about importing a tileset file (TSX extension) at runtime than that is something that Unity doesn't support. All asset importing is done in the editor and not at runtime.

But maybe if you explain a bit more what you'd like to achieve then I can direct further? Thanks.

**Comment by fluttergo** [comment]
I hope ` SuperTiledUnity' can import  the tmx ( with .tsx ) file directly.

For very large tmx maps, it will refer to additional. tsx files. 

For example:

map.tmx 

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<map version="1.2" tiledversion="1.2.4" orientation="orthogonal" renderorder="right-down" width="700" height="700" tilewidth="48" tileheight="32" infinite="0" nextlayerid="4" nextobjectid="1">
 <tileset firstgid="1" source="Tiles.tsx"/>
 <tileset firstgid="31726" source="SmTiles.tsx"/>
 <tileset firstgid="32902" source="Objects.tsx"/>
 <tileset firstgid="42901" source="Objects4.tsx"/>
 <tileset firstgid="52963" source="Objects5.tsx"/>
 <tileset firstgid="63835" source="Objects6.tsx"/>
 <layer id="1" name="base" width="700" height="700">
  <data encoding="csv">
....
</data>
 </layer>
</map>
```

 a tileset file `Tiles.tsx`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.2.4" name="Tiles" tilewidth="96" tileheight="64" tilecount="31725" columns="0">
 <grid orientation="orthogonal" width="1" height="1"/>
 <tile id="0">
  <image width="96" height="64" source="Tiles/0.png"/>
 </tile>
 <tile id="1">
  <image width="96" height="64" source="Tiles/1.png"/>
 </tile>
 <tile id="2">
</tileset>
```

**Comment by bingxue102685** [comment]
Thank you for your reply @Seanba .I want to dynamically add Tiles on the layer. I want to read the .tsx file at runtime, get SuperTile, and then use it.

**Comment by Seanba** [comment]
Hi again, @bingxue102685. You won't be able to do that during runtime because all importing is done in the editor.

I haven't tried this but the closest you can come is to use asset bundles, which can be loaded in runtime. That still requires you to use the Unity Editor to create an asset bundle made up of the extra maps and tilesets, however.
