### ISSUE TITLE
Hexagon map does not import correctly

### ISSUE THREAD

**Issue by icetear** [Seanba/SuperTiled2Unity#82]
<img width="1521" alt="Bildschirmfoto 2019-06-03 um 22 30 50" src="https://user-images.githubusercontent.com/5920121/58832555-77164f80-864f-11e9-8167-32334d1ffdca.png">

As shown in the screenshot, the tiles on a hexagonal map are not placed correctly in Unity3D (2019.1.0f2).

**Comment by Seanba** [comment]
Hi there, @icetear. Could you send me your Unity project as a Unity Package? (mail: sean@seanba.com)

**Comment by icetear** [comment]
sent via mail. Hopefully you can receive a 25MB mail...

**Comment by Seanba** [comment]
I got it (thanks) and I was able to reproduce what you're seeing. I'll investigate a fix but it may be the weekend before it is ready.

**Comment by icetear** [comment]
No haste!

Thank you very much!


Herzliche Grüße
Kind Regards
Mario Gaida

Gaida Internet Services
Dornbuschweg 17
33649 Bielefeld
Tel: 0521 45350537
https://www.gaida.de

worte-wie-sterne.de - Übersetzungen, Korrekturen und weitere Dienstleistungen rund um's Wort.
silversword-rpg.com - The classic CRPG for your iDevice :-)

**Comment by Seanba** [comment]
Hi @icetear just a quick update. I've been working on this and the hex maps have exposed a long-standing issue with all maps. I'm converging on a solution but it's just turning out to be a bigger problem. This will require a major update that I hope to have done in another couple of days. Thanks for the bug report.

**Comment by icetear** [comment]
Thank you very much!
Keep up the good work, we're waiting for the update :-)

**Comment by bjorn** [comment]
@icetear Note that you've previously replied by email and now GitHub has included your email footer in the comment. You may want to delete that part. :-)

> I'm converging on a solution but it's just turning out to be a bigger problem. This will require a major update that I hope to have done in another couple of days.

@Seanba I'm sorry for all the special cases that have grown onto Tiled maps over the years... I really appreciate your continued constructive attitude!

**Comment by Seanba** [comment]
Hi there, @bjorn. No worries. Every piece of valuable software has to grow in complexity and for the most part supporting Tiled has been a good experience. :)

Hello again, @icetear. Version 1.5.1 of SuperTiled2Unity fixes hex maps and supports 60 degree rotations.

https://seanba.itch.io/supertiled2unity/devlog/87454/supertiled2unity-version-151
