### ISSUE TITLE
Grid appears when dragging in map and I am unable to move

### ISSUE THREAD

**Issue by jordanbaron** [Seanba/SuperTiled2Unity#83]
When I follow the steps and drag my map in I get [this](https://i.gyazo.com/50450d1e75fc6e668247fd8a4bb98dab.png) grid and I can't move the map around. I have tried it with an example Tiled map but it gives me the same results

**Comment by Seanba** [comment]
Hi there, @jordanbaron. If you look in the top-left corner of Unity it seems like you have the `Rect Tool` selected. Try clicking on the `Move Tool` instead. :)

![image](https://user-images.githubusercontent.com/6980630/58968708-19335600-877c-11e9-87e8-9ab9a32ceb31.png)
