### ISSUE TITLE
How can I add a custom script to an Object from Tiled that matches a specific type?

### ISSUE THREAD

**Issue by lTyl** [Seanba/SuperTiled2Unity#86]
Heya!

Currently I am working on a top-down RPG. The structure of the project is such that I have one Unity Scene - FieldView - which is responsible for managing all of the levels in the game. The designers use Objects in Tiled to markup a level and to control the Unity prefabs that exist in that level. I am using the Prefab Replacements for this, and it works very well.

What I want to do in addition to the above is to iterate all of the objects on import and then add a collection of custom scripts to that object depending on the type. An example: I have a LevelChange object in Tiled. I want to add the "LevelChanger" script to this object in Unity on import.

Can you point me in the right direction on how to do this?

**Comment by Seanba** [comment]
Hi there, @lTyl. There are two approaches to this:

- If you want to wholesale replace a Tiled Object with a prefab instance then you can use `Prefab Replacements` which I talk about here: https://github.com/Seanba/SuperPrefabReplacement
- If you want to modify objects in your prefab then I recommend writing a custom importer. It means you have to write some code but it's the best way to bend SuperTiled2Unity to your will. See this example for more information: https://github.com/Seanba/SuperMovingPlatform

**Comment by lTyl** [comment]
Thanks for the reply!

I am already using Prefab Replacements, and it is working well. In this case though, I need to retain the Width and Height values that are set on the object in Tiled, and have the collider active for that size object. So a Prefab replacement won't work, since it does not retain the dimensions of the object set in Unity, but uses the Prefab dimensions.

Writing code is not a problem. Imagine I import a Tiled level called "desert". This level has a structure like this:
![desert-1](https://user-images.githubusercontent.com/2981742/61584970-9a696100-ab0e-11e9-9f96-a99eda159722.PNG)

All I want to do is attach additional scripts to the "exitToBeach" and "fromBeach" objects. and I want to do this on Import.

![desert-2](https://user-images.githubusercontent.com/2981742/61584975-af45f480-ab0e-11e9-8287-60855554fd4a.PNG)

My trouble is, I cannot find documentation or an example showing how I can get access to the GameObjects that SuperTiled2Unity creates. I basically just need an array of GameObjects that SuperTiled2Unity creates during its import step, then I modify them as required

**Comment by AberrantWolf** [comment]
I'm doing almost the same thing as you! Here's my custom importer code, which sits in `Assets/Editor/Custom Tile Importers`:

https://gist.github.com/AberrantWolf/635d65059f37c671e644ff65a235b70b

First, I try to get the property name on the incoming object. If it exists, then I add the appropriate behavour to the object (or sometimes its collider, however my behaviours are set up to expect) and set any values I need to. In my setup, each behaviour expects to just get a string copy of the value from the property field (I have a weird JSON-based pseudo-script that I intend to move away from at some point), and then each behaviour figures out what it needs to do based on that value.

But early on I just had normal teleporters/scene transitions where the value of the "change_map" entry was just the name of the map to go to.

**Comment by lTyl** [comment]
@AberrantWolf Thanks for this! This has definitely put me on the right track. Both you and @Seanba are the bomb!

**Comment by Seanba** [comment]
Thanks to @AberrantWolf for helping out.

One additional quick bit of advice: You can use the `AutoCustomTmxImporterAttribute` to force a custom importer to always be applied, regardless of the inspector UI.

```cs
    [AutoCustomTmxImporter()]
    public class MyOrderedTmxImporter : CustomTmxImporter
    {
        public override void TmxAssetImported(TmxAssetImportedArgs args)
        {
            Debug.Log("This custom importer always applied.");
        }
    }
```
