### ISSUE TITLE
Grid incorrect sizes after import

### ISSUE THREAD

**Issue by RisingSunStudios** [Seanba/SuperTiled2Unity#88]
Hi!

I'm hoping this is just an oversight in my settings, but I'm having issues with hexagonal tiles. They look correct in TileD but after import the output doesn't match. This is with unity 2019.1.10f1 Win10.

This is how it appears after import in Unity
![Capture_1](https://user-images.githubusercontent.com/39057393/61992493-23285580-b057-11e9-8330-d43ebff83f79.PNG)

This is how it appears in TileD
![Capture_2](https://user-images.githubusercontent.com/39057393/61992494-23285580-b057-11e9-9ba5-3fe4ea57c260.PNG)

This is how it should appear in Unity
![Capture_3](https://user-images.githubusercontent.com/39057393/61992495-23285580-b057-11e9-912a-4b280110488f.PNG)

As you can see from the settings, its like Unity is switching x and y coordinates and has some weird scaling on the position. 

Any suggestions? 

I can manually change the settings on the grid after import, but then this has to be re-done everytime we make a change to the TMX file which isn't ideal.

Many thanks

**Comment by RisingSunStudios** [comment]
This is using the latest 1.5.3 installer from itch.io

**Comment by Seanba** [comment]
Hi there, @RisingSunStudios. One thing I noticed is that your `Tile Side Length (Hex)` is 0 in Tiled. That is why the background grid (in Tiled) isn't hex-shaped. (It looks like you want that value to be 32, btw.)

Can you try that out and see if it helps? If you're still having an issue can you send me your Unity project, exported as a Unity Package? (email: sean@seanba.com)

**Comment by RisingSunStudios** [comment]
@Seanba Aha! I completely missed that - yep that solves it, looks much better now!

Many thanks!
