### ISSUE TITLE
Feature request: Exception type for custom importers that shows up in console window

### ISSUE THREAD

**Issue by SharlatanY** [Seanba/SuperTiled2Unity#89]
Currently (ST2U 1.5.5, Unity 2019.2), if you throw an exception in a custom importer, it doesn't show up in the Unity console window.

It would be nice to have an exception type, that shows up in the window. I have some importers that search for things like the _Grid_ component etc. and whenever something changes and the components have to be fetched in another way/from another location, I get no indication during import that anything's wrong.
A special exception type (_CustomImporterException_ ?) that showed up in the Unity console would help with noticing and locating this kinds of problems as soon as they arise.
Another solution would be if you could track if any exception was thrown in a custom importer and show all of those. Unless, you have a reason not to do so I don't know about.

Thanks for considering!

**Comment by Seanba** [comment]
Hi there, @SharlatanY. I've added the `CustomImporterException` class with [version 1.5.6 of SuperTiled2Unity](https://seanba.itch.io/supertiled2unity/devlog/94647/supertiled2unity-version-156).

For example:

```
    public class MyThrowingCustomImporter : CustomTmxImporter
    {
        public override void TmxAssetImported(TmxAssetImportedArgs args)
        {
            throw new CustomImporterException("This is my custom importer exception message.");
        }
    }
```
This will print an error in both the inspector and the console window ...

![image](https://user-images.githubusercontent.com/6980630/62882472-f5523a80-bcff-11e9-99d4-7d2705bb816c.png)

![image](https://user-images.githubusercontent.com/6980630/62882492-ff743900-bcff-11e9-94a4-d5e691a6dfef.png)

Let me know in case you were thinking of a different approach. Thanks!

**Comment by SharlatanY** [comment]
@Seanba You're incredibly fast, as always! And I'm super thankful, as always! :)

That's exactly the kind of thing I had in mind! And you even have a button for copying the massage. Even thinking one step ahead! Splendid!

Thanks again and have a nice day!
