### ISSUE TITLE
Errors Loading Unity Package

### ISSUE THREAD

**Issue by MabLuxx** [Seanba/SuperTiled2Unity#9]
<img width="1261" alt="supertiled2unityerrors" src="https://user-images.githubusercontent.com/43322300/48308281-a3894380-e526-11e8-8f35-ed9b73e80ffa.PNG">

I'm attempting to install the unity package into a blank project and I keep running into this list of errors.

My project is completely empty other than the Super Tiled2Unity packcage.

**Comment by Seanba** [comment]
Hi there, MabLuxx. Those are some odd errors. What version of Unity are you using? Are you perhaps on a beta program?

**Comment by MabLuxx** [comment]
Currently I'm working with Unity 2017.4.10f1

Thanks for getting back to me so quickly!

**Comment by Seanba** [comment]
Hi again. I've been able to reproduce those same compiler errors with Unity 2017.4.

I'll try to make SuperTiled2Unity backwards compatible with that version but the new scripted importers in Unity may not be fully cooked enough in Unity 2017 to serve our purposes. If that's the case then I'll at least we get an error that tells us we need a newer version of Unity.

In the meantime can you upgrade to Unity 2018.2 or later?

**Comment by Seanba** [comment]
I was able to resolve the compiler errors but as feared the state of the newer experimental Unity classes in 2017.x do not work against SuperTiled2Unity.

However, with version 1.1.4 of SuperTiled2Unity I warn the user that they need to update their Unity version in the Inspector and Console log.

![image](https://user-images.githubusercontent.com/6980630/48317508-ff9ca800-e5b8-11e8-9af9-63de94dbef2c.png)

![image](https://user-images.githubusercontent.com/6980630/48317512-0b886a00-e5b9-11e8-8bb2-1eb836583c8f.png)

**Comment by MabLuxx** [comment]
Upgraded to Unity 2018.2.15f and Super Tiled2Unity worked perfectly!  Thank you again for helping us through this issue so quickly.

**Comment by Seanba** [comment]
You're welcome. Good luck with your game. :)
