### ISSUE TITLE
How to change the material of Tilemap renderers

### ISSUE THREAD

**Issue by Stefsteenvoorden** [Seanba/SuperTiled2Unity#95]
Hi, me again! It's been a great time working with the asset pack, but I've come across a simple problem that I can't seem to fix by myself, ha ha.

 Is it possible to change the material of the Tilemap Renderer? I'm currently trying to use the new 2d light renderer, but to use the 2d lighting, I need to change a sprite's Material to something else, however, everytime I change the renderer it's material, it changes to it's original material on play. How can I fix this?

![image](https://user-images.githubusercontent.com/29547658/65987705-a6668d00-e486-11e9-9010-93291c266e2d.png)

Thanks,
Stef Steenvoorden

**Comment by Seanba** [comment]
Hi again, @Stefsteenvoorden. I found that once I set up my `Graphics` project to use a 2D lighting pipeline that all the `TilemapRenderer`s would automatically use the `Sprite-Lit-Default` material when a TMX file is re-imported. Can you try that? You can right-click on your TMX file to force a re-import or you can just make a change to your TMX file and re-save.

You can also change what the default material should be in the `SuperTiled2Unity Project Settings` but you shouldn't have to do that if your pipeline is set up correctly.

![image](https://user-images.githubusercontent.com/6980630/65989963-4e149880-e450-11e9-87d8-5884151b8305.png)

**Comment by Seanba** [comment]
@Stefsteenvoorden, I'm going to close this for now but if you're still having issues please re-open with some more details. Thanks.
