### ISSUE TITLE
unity:ignore = "visual" option

### ISSUE THREAD

**Issue by jusw85** [Seanba/SuperTiled2Unity#97]
In Tiled2Unity, you had the unity:ignore="visual" option. This allows me to draw collision on a separate layer. The collision layer will show up on Tiled, but won't be visible on import.

https://github.com/Seanba/Tiled2Unity/issues/20#issuecomment-164498630

I can't find the equivalent in SuperTiled2Unity. Currently, I can workaround by toggling "Visible" in Tiled before saving, but it's tedious since I'm constantly toggling. Is the option available? Thanks!

**Comment by seanb-22ct** [comment]
Hi again, @jusw85. I've put the `unity:ignore` functionality from Tiled2Unity into SuperTiled2Unity with version 1.7.0
https://seanba.itch.io/supertiled2unity/devlog/103661/supertiled2unity-version-170

You seem to know what it does okay but I've put an explainer in the documentation for others:

https://supertiled2unity.readthedocs.io/en/latest/manual/custom-properties-importing.html
