### ISSUE TITLE
unity:isTrigger at layer level

### ISSUE THREAD

**Issue by jusw85** [Seanba/SuperTiled2Unity#98]
In Tiled2Unity, I could specify unity:isTrigger at the layer level. Does not seem to work in ST2U. 

However, it does work if I specify unity:isTrigger on the individual tiles in the layer. Is this intentional? Thanks!

**Comment by seanb-22ct** [comment]
Hi there, @jusw85. I've added this functionality with SuperTiled2Unity 1.7.0.

https://seanba.itch.io/supertiled2unity/devlog/103661/supertiled2unity-version-170

I've also updated the documentation a bit to list the available `unity:propName` custom properties you case use to help direct the importer.

https://supertiled2unity.readthedocs.io/en/latest/manual/custom-properties-importing.html
